### ISSUE TITLE
[mtt] hang in osu_micro_benchmark_collective

### ISSUE THREAD

**Issue by amaslenn** [openucx/ucx#2616] opened 2018-05-16 07:28 UTC
Configuaration
```
OMPI: 3.1.1a1
MOFED: MLNX_OFED_LINUX-4.3-2.0.2.0
Nodes: jazz x5 (ppn=28(x5), nodelist=jazz[06,13-16])
Job: ucx-roce
```

MTT log: http://hpcweb.lab.mtl.com//hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20180515_200343_133975_4568_jazz06/html/test_stdout_kHLnmZ.txt

Test takes ~3 min to finish without UCX (`-mca pml ^ucx`).

Cmd:
`mpirun -np 32 --display-map -mca btl self --tag-output --timestamp-output -mca pml ucx -mca coll '^hcoll' --bind-to core -x UCX_NET_DEVICES=mlx5_1:1 -x UCX_IB_REG_METHODS=rcache,direct -x UCX_IB_ETH_PAUSE_ON=y -x UCX_TLS=rc,sm -mca pmix_base_async_modex 1 -mca mpi_add_procs_cutoff 0 -mca pmix_base_collect_data 0 -x UCX_IB_TRAFFIC_CLASS=106 -x UCX_IB_GID_INDEX=1 --map-by node /hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20180515_200343_133975_4568_jazz06/installs/KWSA/tests/osu_micro_benchmark/osu-micro-benchmarks-5.3.2/mpi/collective/osu_ialltoallw`

Output:
```sh
Wed May 16 10:17:50 2018[1,0]<stdout>:
Wed May 16 10:17:50 2018[1,0]<stdout>:# OSU MPI Non-blocking All-to-Allv Personalized Exchange Latency Test v5.3.2
Wed May 16 10:17:50 2018[1,0]<stdout>:# Overall = Coll. Init + Compute + MPI_Test + MPI_Wait
Wed May 16 10:17:50 2018[1,0]<stdout>:
Wed May 16 10:17:50 2018[1,0]<stdout>:# Size           Overall(us)       Compute(us)    Pure Comm.(us)        Overlap(%)
Wed May 16 10:17:50 2018[1,0]<stdout>:1                      40.69             21.46             20.17              4.69
Wed May 16 10:17:50 2018[1,0]<stdout>:2                      40.00             20.83             19.53              1.86
Wed May 16 10:17:50 2018[1,0]<stdout>:4                      39.96             20.68             19.36              0.39
Wed May 16 10:17:50 2018[1,0]<stdout>:8                      40.00             20.56             19.22              0.00
Wed May 16 10:17:50 2018[1,0]<stdout>:16                     40.37             20.80             19.56              0.00
Wed May 16 10:17:51 2018[1,0]<stdout>:32                     41.05             21.19             19.78              0.00
Wed May 16 10:17:51 2018[1,0]<stdout>:64                     50.39             25.61             24.04              0.00
Wed May 16 10:17:51 2018[1,0]<stdout>:128                    57.43             32.19             30.44             17.09
Wed May 16 10:17:51 2018[1,0]<stdout>:256                    59.99             33.29             31.52             15.26
Wed May 16 10:17:51 2018[1,0]<stdout>:512                    67.24             36.65             34.71             11.88
Wed May 16 10:17:51 2018[1,0]<stdout>:1024                   86.50             46.63             44.36             10.12
Wed May 16 10:18:19 2018[1,0]<stdout>:2048                 7215.23           2250.89           2165.31              0.00
```

**Comment by amaslenn** [comment] 2018-05-16 07:28
Can be related to #2469

**Comment by alinask** [comment] 2018-05-16 07:44
@amaslenn this isn't one-sided, typo in the ticket's name?

**Comment by amaslenn** [comment] 2018-05-16 07:50
This is another one. Both tests have hangs: http://hpcweb.lab.mtl.com//hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20180515_200343_133975_4568_jazz06/

**Comment by alinask** [comment] 2018-05-16 07:54
yes but the name of the ticket indicates that the hang is in one-sided while the command line is from collective. I think we already have a ticket open for one-sided.

**Comment by amaslenn** [comment] 2018-05-16 07:56
Yes, fixed. Thanks!

**Comment by yosefe** [comment] 2018-05-16 09:27
need to run "mlnx_qos -i p1p2 --pfc 0,0,0,1,0,0,0,0" to configure lossless RoCE properly

**Comment by yosefe** [comment] 2018-05-16 10:35
closing this since the problem is cluster misconfig

**Closed by yosefe** 2018-05-16 10:35 UTC
Labels: bug, mtt
