### ISSUE TITLE
ucx_perftest error with RC transport

### ISSUE THREAD

**Issue by pcapuzzi** [openucx/ucx#5318] opened 2020-06-23 15:43 UTC
### Describe the bug
We want to try UCX in our openmpi4 installation and are finding some errors when testing UCX using ucx_perftest.  In particular, the RC transport is giving errors, excluding RC using for instance UCX_TLS=ud,tcp gives no problem.
The logged error is 
```
local QP operation err (QPN 350406, WQE @ 00000883, CQN 9b0083, index 153)
  [ 0] 00350406
  [ 4] 00000000
  [ 8] 00000000
  [ c] 00000000
  [10] 02702711
  [14] 00000000
  [18] 00000883
  [1c] ff100000
[compute-18:26540:0:26540] rc_verbs_iface.c:65   send completion with error: local QP operation error qpn 0x350406 wrid 0x38 vendor_err 0x70

/home/user/devel/ucx/src/uct/ib/rc/verbs/rc_verbs_iface.c: [ uct_rc_verbs_handle_failure() ]
      ...
       60     }
       61 
       62     ucs_log(log_lvl,
==>    63             "send completion with error: %s qpn 0x%x wrid 0x%lx vendor_err 0x%x",
       64             ibv_wc_status_str(wc->status), wc->qp_num, wc->wr_id, wc->vendor_err);
       65 }
       66 
==== backtrace (tid:  16265) ====
 0 0x0000000000027025 uct_rc_verbs_handle_failure()  /home/user/devel/ucx/src/uct/ib/rc/verbs/rc_verbs_iface.c:63
 1 0x0000000000027825 uct_rc_verbs_iface_poll_tx()  /home/user/devel/ucx/src/uct/ib/rc/verbs/rc_verbs_iface.c:104
 2 0x0000000000027825 uct_rc_verbs_iface_progress()  /home/user/devel/ucx/src/uct/ib/rc/verbs/rc_verbs_iface.c:138
 3 0x000000000002ed50 ucs_callbackq_dispatch()  /home/user/devel/ucx/src/ucs/datastruct/callbackq.h:211
 4 0x000000000003577c uct_worker_progress()  /home/user/devel/ucx/src/uct/api/uct.h:2342
 5 0x0000000000043a3f ucp_rma_wait()  /home/user/devel/ucx/src/ucp/rma/rma.inl:68
 6 0x00000000000458b9 ucp_flush_wait()  /home/user/devel/ucx/src/ucp/rma/flush.c:533
 7 0x00000000000458f4 ucp_worker_flush()  /home/user/devel/ucx/src/ucp/rma/flush.c:544
 8 0x00000000004a13e1 ucp_perf_test_runner<(ucx_perf_cmd_t)7, (ucx_perf_test_type_t)1, 0u>::flush()  /home/user/devel/ucx/src/tools/perf/lib/ucp_tests.cc:309
 9 0x0000000000497085 ucp_perf_test_runner<(ucx_perf_cmd_t)7, (ucx_perf_test_type_t)1, 0u>::run_stream_uni()  /home/user/devel/ucx/src/tools/perf/lib/ucp_tests.cc:445
10 0x000000000048e37c ucp_perf_test_runner<(ucx_perf_cmd_t)7, (ucx_perf_test_type_t)1, 0u>::run()  /home/user/devel/ucx/src/tools/perf/lib/ucp_tests.cc:462
11 0x000000000048d295 ucp_perf_test_dispatch()  /home/user/devel/ucx/src/tools/perf/lib/ucp_tests.cc:583
12 0x000000000040d039 ucx_perf_run()  /home/user/devel/ucx/src/tools/perf/lib/libperf.c:1826
13 0x0000000000406bcc run_test_recurs()  /home/user/devel/ucx/src/tools/perf/perftest.c:1579
14 0x0000000000406ea9 run_test()  /home/user/devel/ucx/src/tools/perf/perftest.c:1639
15 0x0000000000406fef main()  /home/user/devel/ucx/src/tools/perf/perftest.c:1715
16 0x0000000000022505 __libc_start_main()  ???:0
17 0x00000000004038a9 _start()  ???:0
=================================

```
At the same time the kernel logs `ib_mthca 0000:42:00.0: Async event 16 for bogus QP 00350406
`

### Steps to Reproduce
Run  `ucx_perftest -c 0`  in a node and `ucx_perftest -c 0 -t tag_lat 192.168.160.1`  in another, where 192.168.160.1 is the IP of IB on first node.  We are using ucx master commit 9267ed9, but with previous versions we observe the same. 
- `ucx_info -v`  is
<code>
# configured with: --disable-optimizations --with-sse42 --with-sse41 --disable-mt --enable-cma --without-cuda --without-gdrcopy --with-verbs --without-cm --without-knem --with-rdmacm --without-rocm --without-xpmem --without-ugni --prefix=/home/user/local/ucx/master/ --enable-gtest --enable-debug --enable-assertions --enable-logging --enable-examples
</code>

### Setup and versions
-  CentOS Linux release 7.7.1908,  rdma-core-22.1-3.el7.x86_64
-  `ibv_devinfo -vv`  gives 
```hca_id: mthca0
        transport:                      InfiniBand (0)
        fw_ver:                         1.1.0
        node_guid:                      0002:c902:0025:1c34
        sys_image_guid:                 0002:c902:0025:1c37
        vendor_id:                      0x02c9
        vendor_part_id:                 25204
        hw_ver:                         0xA0
        board_id:                       MT_03B0140002
        phys_port_cnt:                  1
        max_mr_size:                    0xffffffffffffffff
        page_size_cap:                  0xfffff000
        max_qp:                         64512
        max_qp_wr:                      16384
        device_cap_flags:               0x00001c76
                                        BAD_PKEY_CNTR
                                        BAD_QKEY_CNTR
                                        AUTO_PATH_MIG
                                        CHANGE_PHY_PORT
                                        UD_AV_PORT_ENFORCE
                                        PORT_ACTIVE_EVENT
                                        SYS_IMAGE_GUID
                                        RC_RNR_NAK_GEN
        max_sge:                        27
        max_sge_rd:                     27
        max_cq:                         65408
        max_cqe:                        131071
        max_mr:                         131056
        max_pd:                         32764
        max_qp_rd_atom:                 4
        max_ee_rd_atom:                 0
        max_res_rd_atom:                258048
        max_qp_init_rd_atom:            128
        max_ee_init_rd_atom:            0
        atomic_cap:                     ATOMIC_HCA (1)
        max_ee:                         0
        max_rdd:                        0
        max_mw:                         0
        max_raw_ipv6_qp:                0
        max_raw_ethy_qp:                0
        max_mcast_grp:                  8192
        max_mcast_qp_attach:            56
        max_total_mcast_qp_attach:      458752
        max_ah:                         0
        max_fmr:                        0
        max_srq:                        960
        max_srq_wr:                     16384
        max_srq_sge:                    27
        max_pkeys:                      64
        local_ca_ack_delay:             15
        general_odp_caps:
        rc_odp_caps:
                                        NO SUPPORT
        uc_odp_caps:
                                        NO SUPPORT
        ud_odp_caps:
                                        NO SUPPORT
        completion_timestamp_mask not supported
        core clock not supported
        device_cap_flags_ex:            0x0
        tso_caps:
        max_tso:                        0
        rss_caps:
                max_rwq_indirection_tables:                     0
                max_rwq_indirection_table_size:                 0
                rx_hash_function:                               0x0
                rx_hash_fields_mask:                            0x0
        max_wq_type_rq:                 0
        packet_pacing_caps:
                qp_rate_limit_min:      0kbps
                qp_rate_limit_max:      0kbps
        tag matching not supported
                port:   1
                        state:                  PORT_ACTIVE (4)
                        max_mtu:                2048 (4)
                        active_mtu:             2048 (4)
                        sm_lid:                 1
                        port_lid:               22
                        port_lmc:               0x00
                        link_layer:             InfiniBand
                        max_msg_sz:             0x80000000
                        port_cap_flags:         0x02590a68
                        port_cap_flags2:        0x0000
                        max_vl_num:             4 (3)
                        bad_pkey_cntr:          0x0
                        qkey_viol_cntr:         0x0
                        sm_sl:                  0
                        pkey_tbl_len:           64
                        gid_tbl_len:            32
                        subnet_timeout:         18
                        init_type_reply:        0
                        active_width:           4X (2)
                        active_speed:           5.0 Gbps (2)
                        phys_state:             LINK_UP (5)
                        GID[  0]:               fe80:0000:0000:0000:0002:c902:0025:1c35
```

Thank you very much.

**Comment by yosefe** [comment] 2020-06-23 15:58
@pcapuzzi can you pls try with this patch (just as experiment, it's not a correct fix):
```diff
diff --git a/src/uct/ib/rc/verbs/rc_verbs_ep.c b/src/uct/ib/rc/verbs/rc_verbs_ep.c
index 80656e0..03432dd 100644
--- a/src/uct/ib/rc/verbs/rc_verbs_ep.c
+++ b/src/uct/ib/rc/verbs/rc_verbs_ep.c
@@ -388,13 +388,6 @@ ucs_status_t uct_rc_verbs_ep_flush(uct_ep_h tl_ep, unsigned flags,
         return status;
     }
 
-    if (uct_rc_txqp_unsignaled(&ep->super.txqp) != 0) {
-        status = uct_rc_verbs_ep_put_short(tl_ep, NULL, 0, 0, 0);
-        if (status != UCS_OK) {
-            return status;
-        }
-    }
-
     return uct_rc_txqp_add_flush_comp(&iface->super, &ep->super.super,
                                       &ep->super.txqp, comp, ep->txcnt.pi);
 }
```

**Comment by pcapuzzi** [comment] 2020-06-23 17:24
After printing some headers the command is stuck at least some minutes with both CPUs at 100% , after that I interrumpted it with ctrl-c.  I attach logfile obtained by setting UCX_LOG_LEVEL=data . Thank you very much.
[logdata2.log](https://github.com/openucx/ucx/files/4820907/logdata2.log)

**Comment by yosefe** [comment] 2020-06-23 17:29
> After printing some headers the command is stuck at least some minutes with both CPUs at 100% , after that I interrumpted it with ctrl-c. I attach logfile obtained by setting UCX_LOG_LEVEL=data . Thank you very much.

Does it mean it has passed the point where there was a "local QP operation err" before the patch?

**Comment by pcapuzzi** [comment] 2020-06-23 17:42
Well, what i can tell now is that the message disappeared from the console and there are no messages from kernel. I  don't know if it means it is stuck after or before because I actually don't know the code itself. I'll try to read the code to understand at least some. Thank you.

**Comment by yosefe** [comment] 2020-06-23 17:59
@pcapuzzi actually, i would expect it to stuck, since https://github.com/openucx/ucx/issues/5318#issuecomment-648256596 is not a rela fix, it actually makes flush operation a no-OP. I've just made it to make sure the problem is because of doing RDMA_WRITE with 0-byte length. the real fix would be to use real rkey/vaddr to flush operation on older HCA's.

**Comment by pcapuzzi** [comment] 2020-06-23 18:21
Thank you @yosefe . That means you have a clear idea of what the problem is, right?, Given that these are old HCA's,  do you think the problem will be fixed at some point?.

**Comment by yosefe** [comment] 2020-06-24 14:06
duplicate of https://github.com/openucx/ucx/issues/2951#issuecomment-432644664

**Comment by yosefe** [comment] 2020-06-25 07:59
> Thank you @yosefe . That means you have a clear idea of what the problem is, right?, Given that these are old HCA's, do you think the problem will be fixed at some point?.

Given that this is ~15yo HCA, it's unlikely to be fixed soon.. :(

**Comment by pcapuzzi** [comment] 2020-06-25 13:04
I understand. Thank you for your work!.

**Closed** 2020-07-31 18:06 UTC
Labels: Bug

**Comment by pcapuzzi** [comment] 2020-07-31 22:06
Thank you  @yosefe. I can confirm that the transport error dissapeared. Regards!.
