### ISSUE TITLE
UCX_1.5.1 and process_vm_readv delivered 0 instead of ....

### ISSUE THREAD

**Issue by spikebike** [openucx/ucx#3545] opened 2019-05-01 05:14 UTC
On an ubuntu-18.04 system I built openmpi-4.0.1 with UCX-1.5.1.  Many codes on a single node or multiple node runs "just worked".  However some codes like LAMMPs or ESKM would report errors like:
```
process_vm_readv delivered 0 instead of 480960, error message Operation not permitted
```

The immediate fix is:
```sysctl -w kernel.yama.ptrace_scope=0```

The permanent fix is to make the same change in /etc/sysctl.d/10-ptrace.conf, which will fix things after the next boot.

I didn't see any mention of this in the docs, by ./configure, during ./install, or at runtime.

**Comment by yosefe** [comment] 2019-05-01 06:48
@spikebike the issue is fixed in #3205 which will be part of ucx v1.6 release

**Closed** 2019-06-08 19:49 UTC
Labels: Bug
