### ISSUE TITLE
rc/test_ucp_mmap.reg_mem_type/1 failure on ppc

### ISSUE THREAD

**Issue by dmitrygx** [openucx/ucx#5918] opened 2020-11-18 07:41 UTC
```
[2020-11-17T20:14:17.771Z] [ RUN      ] rc/test_ucp_mmap.reg_mem_type/1 <rc_v/map_nb>
[2020-11-17T20:14:18.387Z] /scrap/jenkins/workspace/ucx-3/contrib/../test/gtest/ucp/test_ucp_mmap.cc:167: Failure
[2020-11-17T20:14:18.387Z] Expected: (&ucp_rma_sw_proto) != (rkey->cache.rma_proto), actual: 0x3fffb0a22940 vs 0x3fffb0a22940
[2020-11-17T20:14:18.643Z] [  FAILED  ] rc/test_ucp_mmap.reg_mem_type/1, where GetParam() = rc_v/map_nb (676 ms)
```
on r-vmb-ppc-jenkins
Job link: http://hpc-master.lab.mtl.com:8080/blue/organizations/jenkins/ucx/detail/ucx/8045/pipeline/770
Log link: http://hpc-master.lab.mtl.com:8080/blue/rest/organizations/jenkins/pipelines/ucx/runs/8045/nodes/73/steps/782/log/?start=0

**Comment by brminich** [comment] 2020-11-18 10:15
seems duplicate of #5840

**Closed** 2020-11-18 19:48 UTC
Labels: Bug, CI (AZP/Jenkins)
