### ISSUE TITLE
[mtt] segfault in mpi-small-tests (armcc)

### ISSUE THREAD

**Issue by amaslenn** [openucx/ucx#2955] opened 2018-10-15 12:06 UTC
Configuration
```
OMPI: 4.0.0rc4
MOFED: MLNX_OFED_LINUX-4.4-2.0.7.0
Module: hpcx-armcc (2018-10-11)
Nodes: hwi-arm x2 (ppn=64(x2), nodelist=hpc-arm-hwi[01-02])
```

MTT log: http://hpcweb.lab.mtl.com//hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20181012_012312_44776_8675_hpc-arm-hwi01/html/test_stdout_SQinap.txt

Cmd:
```sh
module load hpcx-armcc
module load arm-compiler/arm-hpc-compiler
```
`mpirun -np 64 --display-map -mca btl self --tag-output --timestamp-output -mca pml ucx -mca coll '^hcoll' --bind-to core -x UCX_NET_DEVICES=mlx5_0:1 -mca osc '^ucx' -x UCX_IB_ADDR_TYPE=ib_global -x UCX_IB_REG_METHODS=rcache,direct -x UCX_TLS=all -mca pmix_base_async_modex 0 -mca mpi_add_procs_cutoff 100000 -mca pmix_base_collect_data 1 --map-by node /hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20181012_012312_44776_8675_hpc-arm-hwi01/installs/TANH/tests/mpi-small-tests/hpc_tests.git/mpi/misc/assocf`

Output:
```sh
Mon Oct 15 14:59:10 2018[1,1]<stdout>: This test case must be run as a four-way job
Mon Oct 15 14:59:10 2018[1,0]<stdout>: This test case must be run as a four-way job
Mon Oct 15 14:59:10 2018[1,0]<stderr>:[hpc-arm-hwi01:21782:0:21782] Caught signal 11 (Segmentation fault: address not mapped to object at address (nil))
Mon Oct 15 14:59:10 2018[1,0]<stderr>:==== backtrace ====
Mon Oct 15 14:59:10 2018[1,0]<stderr>:    0  /hpc/local/benchmarks/hpcx_install_2018-10-14/hpcx-armcc-redhat7.4/ucx/lib/libucs.so.0(+0x18648) [0xffffb4ee8648]
Mon Oct 15 14:59:10 2018[1,0]<stderr>:    1  /hpc/local/benchmarks/hpcx_install_2018-10-14/hpcx-armcc-redhat7.4/ucx/lib/libucs.so.0(+0x17dd8) [0xffffb4ee7dd8]
Mon Oct 15 14:59:10 2018[1,0]<stderr>:    2  [0xffffb7fc06c0]
Mon Oct 15 14:59:10 2018[1,0]<stderr>:    3  /usr/lib64/libc.so.6(cfree+0x38) [0xffffb77fdb90]
Mon Oct 15 14:59:10 2018[1,0]<stderr>:    4  /usr/lib64/libibverbs.so.1(ibv_close_device+0xe4) [0xffffb500b0ac]
Mon Oct 15 14:59:10 2018[1,0]<stderr>:    5  /hpc/local/benchmarks/hpcx_install_2018-10-14/hpcx-armcc-redhat7.4/ucx/lib/libuct.so.0(uct_ib_md_close+0x88) [0xffffb50970a4]
Mon Oct 15 14:59:10 2018[1,0]<stderr>:    6  /hpc/local/benchmarks/hpcx_install_2018-10-14/hpcx-armcc-redhat7.4/ucx/lib/libucp.so.0(ucp_cleanup+0x58) [0xffffb511d178]
Mon Oct 15 14:59:10 2018[1,0]<stderr>:    7  /hpc/local/benchmarks/hpcx_install_2018-10-14/hpcx-armcc-redhat7.4/ompi/lib/openmpi/mca_pml_ucx.so(mca_pml_ucx_close+0x48) [0xffffb51a45a4]
Mon Oct 15 14:59:10 2018[1,0]<stderr>:    8  /hpc/local/benchmarks/hpcx_install_2018-10-14/hpcx-armcc-redhat7.4/ompi/lib/openmpi/mca_pml_ucx.so(+0x69a0) [0xffffb51a69a0]
Mon Oct 15 14:59:10 2018[1,0]<stderr>:    9  /hpc/local/benchmarks/hpcx_install_2018-10-14/hpcx-armcc-redhat7.4/ompi/lib/libopen-pal.so.40(mca_base_components_close+0x88) [0xffffb75f3834]
Mon Oct 15 14:59:10 2018[1,0]<stderr>:   10  /hpc/local/benchmarks/hpcx_install_2018-10-14/hpcx-armcc-redhat7.4/ompi/lib/libopen-pal.so.40(mca_base_framework_components_close+0x20) [0xffffb75f37a0]
Mon Oct 15 14:59:10 2018[1,0]<stderr>:   11  /hpc/local/benchmarks/hpcx_install_2018-10-14/hpcx-armcc-redhat7.4/ompi/lib/libopen-pal.so.40(mca_base_framework_close+0x1d4) [0xffffb75fed64]
Mon Oct 15 14:59:10 2018[1,0]<stderr>:   12  /hpc/local/benchmarks/hpcx_install_2018-10-14/hpcx-armcc-redhat7.4/ompi/lib/libmpi.so.40(ompi_mpi_finalize+0x6cc) [0xffffb7debb9c]
Mon Oct 15 14:59:10 2018[1,0]<stderr>:   13  /hpc/local/benchmarks/hpcx_install_2018-10-14/hpcx-armcc-redhat7.4/ompi/lib/libmpi_mpifh.so.40(pmpi_finalize__+0x14) [0xffffb7ef8578]
Mon Oct 15 14:59:10 2018[1,0]<stderr>:   14  /hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20181012_012312_44776_8675_hpc-arm-hwi01/installs/TANH/tests/mpi-small-tests/hpc_tests.git/mpi/misc/assocf() [0x40117c]
Mon Oct 15 14:59:10 2018[1,0]<stderr>:   15  /hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20181012_012312_44776_8675_hpc-arm-hwi01/installs/TANH/tests/mpi-small-tests/hpc_tests.git/mpi/misc/assocf() [0x4018b4]
Mon Oct 15 14:59:10 2018[1,0]<stderr>:   16  /usr/lib64/libc.so.6(__libc_start_main+0xf0) [0xffffb77a0d64]
Mon Oct 15 14:59:10 2018[1,0]<stderr>:   17  /hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20181012_012312_44776_8675_hpc-arm-hwi01/installs/TANH/tests/mpi-small-tests/hpc_tests.git/mpi/misc/assocf() [0x400fcc]
Mon Oct 15 14:59:10 2018[1,0]<stderr>:===================
Mon Oct 15 14:59:10 2018[1,1]<stderr>:[hpc-arm-hwi02:22613:0:22613] Caught signal 11 (Segmentation fault: address not mapped to object at address (nil))
Mon Oct 15 14:59:10 2018[1,1]<stderr>:==== backtrace ====
Mon Oct 15 14:59:10 2018[1,1]<stderr>:    0  /hpc/local/benchmarks/hpcx_install_2018-10-14/hpcx-armcc-redhat7.4/ucx/lib/libucs.so.0(+0x18648) [0xffffb4ee8648]
Mon Oct 15 14:59:10 2018[1,1]<stderr>:    1  /hpc/local/benchmarks/hpcx_install_2018-10-14/hpcx-armcc-redhat7.4/ucx/lib/libucs.so.0(+0x17dd8) [0xffffb4ee7dd8]
Mon Oct 15 14:59:10 2018[1,1]<stderr>:    2  [0xffffb7fc06c0]
Mon Oct 15 14:59:10 2018[1,1]<stderr>:    3  /usr/lib64/libc.so.6(cfree+0x38) [0xffffb77fdb90]
Mon Oct 15 14:59:10 2018[1,1]<stderr>:    4  /usr/lib64/libibverbs.so.1(ibv_close_device+0xe4) [0xffffb500b0ac]
Mon Oct 15 14:59:10 2018[1,1]<stderr>:    5  /hpc/local/benchmarks/hpcx_install_2018-10-14/hpcx-armcc-redhat7.4/ucx/lib/libuct.so.0(uct_ib_md_close+0x88) [0xffffb50970a4]
Mon Oct 15 14:59:10 2018[1,1]<stderr>:    6  /hpc/local/benchmarks/hpcx_install_2018-10-14/hpcx-armcc-redhat7.4/ucx/lib/libucp.so.0(ucp_cleanup+0x58) [0xffffb511d178]
Mon Oct 15 14:59:10 2018[1,1]<stderr>:    7  /hpc/local/benchmarks/hpcx_install_2018-10-14/hpcx-armcc-redhat7.4/ompi/lib/openmpi/mca_pml_ucx.so(mca_pml_ucx_close+0x48) [0xffffb51a45a4]
Mon Oct 15 14:59:10 2018[1,1]<stderr>:    8  /hpc/local/benchmarks/hpcx_install_2018-10-14/hpcx-armcc-redhat7.4/ompi/lib/openmpi/mca_pml_ucx.so(+0x69a0) [0xffffb51a69a0]
Mon Oct 15 14:59:10 2018[1,1]<stderr>:    9  /hpc/local/benchmarks/hpcx_install_2018-10-14/hpcx-armcc-redhat7.4/ompi/lib/libopen-pal.so.40(mca_base_components_close+0x88) [0xffffb75f3834]
Mon Oct 15 14:59:10 2018[1,1]<stderr>:   10  /hpc/local/benchmarks/hpcx_install_2018-10-14/hpcx-armcc-redhat7.4/ompi/lib/libopen-pal.so.40(mca_base_framework_components_close+0x20) [0xffffb75f37a0]
Mon Oct 15 14:59:10 2018[1,1]<stderr>:   11  /hpc/local/benchmarks/hpcx_install_2018-10-14/hpcx-armcc-redhat7.4/ompi/lib/libopen-pal.so.40(mca_base_framework_close+0x1d4) [0xffffb75fed64]
Mon Oct 15 14:59:10 2018[1,1]<stderr>:   12  /hpc/local/benchmarks/hpcx_install_2018-10-14/hpcx-armcc-redhat7.4/ompi/lib/libmpi.so.40(ompi_mpi_finalize+0x6cc) [0xffffb7debb9c]
Mon Oct 15 14:59:10 2018[1,1]<stderr>:   13  /hpc/local/benchmarks/hpcx_install_2018-10-14/hpcx-armcc-redhat7.4/ompi/lib/libmpi_mpifh.so.40(pmpi_finalize__+0x14) [0xffffb7ef8578]
Mon Oct 15 14:59:10 2018[1,1]<stderr>:   14  /hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20181012_012312_44776_8675_hpc-arm-hwi01/installs/TANH/tests/mpi-small-tests/hpc_tests.git/mpi/misc/assocf() [0x40117c]
Mon Oct 15 14:59:10 2018[1,1]<stderr>:   15  /hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20181012_012312_44776_8675_hpc-arm-hwi01/installs/TANH/tests/mpi-small-tests/hpc_tests.git/mpi/misc/assocf() [0x4018b4]
Mon Oct 15 14:59:10 2018[1,1]<stderr>:   16  /usr/lib64/libc.so.6(__libc_start_main+0xf0) [0xffffb77a0d64]
Mon Oct 15 14:59:10 2018[1,1]<stderr>:   17  /hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20181012_012312_44776_8675_hpc-arm-hwi01/installs/TANH/tests/mpi-small-tests/hpc_tests.git/mpi/misc/assocf() [0x400fcc]
Mon Oct 15 14:59:10 2018[1,1]<stderr>:===================
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 0 on node hpc-arm-hwi01 exited on signal 11 (Segmentation fault).
--------------------------------------------------------------------------
```

**Comment by shamisp** [comment] 2018-10-15 18:09
@nSircombe FYI

**Comment by nSircombe** [comment] 2018-10-15 21:16
@amaslenn, Which version of the Arm compiler are you using?
Does this only show up with the Open MPI 4.0.0 RC? 
I've not built 4.0.0 with Open UCX yet...

**Comment by amaslenn** [comment] 2018-10-16 08:14
@nSircombe 
```sh
$ armclang --version
Arm C/C++/Fortran Compiler version 18.4 (build number 40) (based on LLVM 5.0.2)
Target: aarch64--linux-gnu
Thread model: posix
InstalledDir: /hpc/local/commercial/arm-compiler-18.4/opt/arm/arm-hpc-compiler-18.4_Generic-AArch64_RHEL-7_aarch64-linux/bin
```
I don't have results for any other OMPI versions.

**Comment by nSircombe** [comment] 2018-10-18 16:14
so, running with np .NE. 4 this is just calling...
```
call MPI_INIT(ier)
call MPI_COMM_SIZE(MPI_COMM_WORLD,size,ier)
call MPI_FINALIZE(ier)
```
...is the failure in the finalize?

does it run at 4 PEs

What's the machine this is being run on? ThunderX2?
I can't reproduce the same conditions on the TX2 test machine here, I'll have to move to a bigger machine and try again.

**Comment by amaslenn** [comment] 2018-10-21 07:27
It was Huawei hosts.

**Comment by hoopoepg** [comment] 2018-10-31 09:14
fixed via https://github.com/openucx/ucx/pull/2969

**Closed by hoopoepg** 2018-10-31 09:14 UTC
Labels: Bug, MTT
