### ISSUE TITLE
hang in all/test_ucp_version with valgrind

### ISSUE THREAD

**Issue by yosefe** [openucx/ucx#932] opened 2016-08-27 20:19 UTC
http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/1632/label=hpc-test-node/console

```
10:57:09 [----------] 2 tests from all/test_ucp_version
10:57:09 [ RUN      ] all/test_ucp_version.version_string/0
12:02:19 make: *** [test_valgrind] Killed
12:02:19 Build step 'Execute shell' marked build as failure
```

**Comment by shssf** [comment] 2016-11-05 13:30
@yosefe Is this bug fixed? I can't reproduce it.

**Comment by yosefe** [comment] 2016-11-05 14:14
niether could i. lets close?

**Comment by shssf** [comment] 2016-11-05 14:25
I tried it on different machines with and without valgrind. The issue wasn't reproduced.
Perhaps, some other conditions (parallel processes or memory lack) have to be took into account.
In case of the issue - let's close it.
Is it possible to implement some additional checks in case of test system hangs? I meant, automatic gstask + meminfo + environment is printed out to the output instead just kill the session.

**Comment by yosefe** [comment] 2016-11-06 12:53
maybe we can add "gstack" if the command times out

**Closed** 2016-11-06 12:54 UTC
Labels: bug
