### ISSUE TITLE
Performance degradation on TX2 with UCXv1.5

### ISSUE THREAD

**Issue by rzambre** [openucx/ucx#2767] opened 2018-07-30 15:53 UTC
Comparing UCXv1.3.0 (stable release) and UCX's master branch:

On ThunderX2 set at 2.2GHz, the message rate of `ucx_perftest -c 0 -t put_bw -d mlx5_0:1 -x rc_mlx5` with UCXv1.3 is 3.4 million but with UCXv1.5 is 0.6 million.

Most likely BlueFlame is failing with v1.5.

Testbed information:
ConnectX-4
MOFED version: MLNX_OFED_LINUX-4.3-1.0.1.0 (OFED-4.3-1.0.1)
Kernel version: 4.11.0-44.el7a.aarch64
OS: RHEL 7.4

**Comment by yosefe** [comment] 2018-07-30 15:56
@hoopoepg can you pls check?
@rzambre which device is it (ConnectX3/4/5/IB)? And what is the MLNX_OFED version?

**Comment by rzambre** [comment] 2018-07-30 16:01
I have updated the first post with testbed information

**Comment by rzambre** [comment] 2018-07-31 13:54
Hi @hoopoepg,

- For UCXv1.3, I tested with both prebuilt modules and with custom builds from source. For UCXv1.5, I tested only with a custom build from source (wasn't able to find a pre-built version)

- Could you point me to UCXv1.4? Wasn't able to find it in releases or tags.

**Comment by hoopoepg** [comment] 2018-07-31 13:57
there is branch v1.4.x in UCX guthub repo: https://github.com/openucx/ucx/tree/v1.4.x

**Comment by rzambre** [comment] 2018-07-31 13:59
Great, I'll test with it and get back to you. I have also updated my previous comment to show the command line I used to build the custom source.

**Comment by rzambre** [comment] 2018-07-31 14:17
The problem still exists in v1.4 as well.

**Comment by shamisp** [comment] 2018-07-31 14:56
I just want to mentioned that it also was observed on 2.0Ghz configuration. So, you should be able to reproduce this in-house.

**Comment by shamisp** [comment] 2018-08-01 14:06
@hoopoepg - did you test with TX2 socket or some other Arm ? There is no remote access to this platform. We observed the problem on multiple servers installed within various organizations (not just ours). It is very consistent. I can help to find you CX4 card within Mellanox if needed ;)

**Comment by shamisp** [comment] 2018-08-01 16:39
@yosefe it is a bit of pain. What was fixed in 4.3-2.0.2.0 ?

**Comment by yosefe** [comment] 2018-08-01 16:40
resource domain

**Comment by shamisp** [comment] 2018-08-01 16:45
in the driver ?

**Comment by yosefe** [comment] 2018-08-01 16:48
yes

**Comment by shamisp** [comment] 2018-08-01 16:51
You didn't make map it properly ?

**Comment by yosefe** [comment] 2018-08-01 16:51
@rzambre pls let us know if upgrading MOFED fixes the problem for you

**Comment by shamisp** [comment] 2018-08-01 16:54
@yosefe it is difficult. There are other deployments where it is even more difficult. I want to see the kernel patch before we even consider this direction. Also, probably we would have to provide backward compatibility patch for older MOFEDs

**Comment by yosefe** [comment] 2018-08-01 17:03
@hoopoepg can you try repro the issue on our TX2 setup with older MOFED?

**Comment by hoopoepg** [comment] 2018-08-01 17:05
Will try tomorrow

**Comment by hoopoepg** [comment] 2018-08-02 07:31
@rzambre new configuration will take time...
could you try this PR: https://github.com/openucx/ucx/pull/2781
it adds parameter to disable multiple IB resource domains.

add argument to your configure command line: --disable-res-domain
and try to run bench

thank you

**Comment by rzambre** [comment] 2018-08-02 14:06
With `--disable-res-domain` the message rate is back to 3.5M, the same as that with UCXv1.3. So, resource domain usage is the problem.

@hoopoepg why does the PR say "multiple" IB resource domains? From my understanding of the changes in the PR, it is simply turning off the use of resource domain, single or multiple. Just clarifying to see if I am missing anything.

**Comment by hoopoepg** [comment] 2018-08-02 14:07
I'm not best in IB internals, but by default there is used any default resource domain across all transports

**Comment by yosefe** [comment] 2018-08-02 14:11
This patch for libmlx5 should fix the issue: [7e1d593.diff.zip](https://github.com/openucx/ucx/files/2253812/7e1d593.diff.zip)

**Comment by shamisp** [comment] 2018-08-02 14:13
@hoopoepg we have to figure out how do we detect broken mlx5 lib (kernel module? ) and autodetect this.  There are external customer that will hit this bug very soon.

**Comment by hoopoepg** [comment] 2018-08-02 14:16
@shamisp and what should be our action? multiple resources are used to fix data corruption issue when used both verbs/accel transports

**Comment by shamisp** [comment] 2018-08-02 14:20
@hoopoepg I just saw the comment on PR. Short version - you screwed. 
Was the domain libmlx5 code upstreamed to rdma-core ?

**Comment by yosefe** [comment] 2018-08-02 14:21
yes, it's called "thread domain" in upstream, and it's fixed there.

**Comment by shamisp** [comment] 2018-08-02 14:29
RHEL is a bit more strict but please check with your maintainer. SLES folks a very flexible....
So, if this is just broken MOFED. Can we ofed_info to disable/enable mlx5 transport on PPC/AARCH64 ?  Probably you have to print huge warning during configure about performance degradation due MOFED version and suggest how to fix it,

We would have to bring it with some of the core customers next week.

**Comment by yosefe** [comment] 2018-08-20 11:33
![](https://github.trello.services/images/mini-trello-icon.png) [UCX osu_bw result on shared memory/ARM is worse than OMPI/vader](https://trello.com/c/v9f8QpUG/10-ucx-osubw-result-on-shared-memory-arm-is-worse-than-ompi-vader)

**Comment by shamisp** [comment] 2018-08-20 15:39
@yosefe @rzambre - tested with latest MOFED 4.4-1 and the problem is still present

**Comment by yosefe** [comment] 2018-08-20 16:06
@shamisp we can reproduce it in-house too, with latest MLNX_OFED, @hoopoepg is looking into this

**Comment by hoopoepg** [comment] 2018-09-03 17:30
MOFED/kernel module should be updated, patch:
```
diff --git a/drivers/infiniband/hw/mlx5/main_exp.c b/drivers/infiniband/hw/mlx5/main_exp.c
index 7d8821c..0bd0467 100644
--- a/drivers/infiniband/hw/mlx5/main_exp.c
+++ b/drivers/infiniband/hw/mlx5/main_exp.c
@@ -2163,6 +2163,23 @@ int alloc_and_map_wc(struct mlx5_ib_dev *dev,
 	}
 
 	vma->vm_page_prot = pgprot_writecombine(vma->vm_page_prot);
+#if defined(MIDR_CPU_MODEL_MASK)
+#if defined(CONFIG_ARM64)
+    /*
+     * Fix up arm64 braindamage of using NORMAL_NC for write
+     * combining when Device GRE exists specifically for the
+     * purpose. Needed on ThunderX2.
+     */
+    switch (read_cpuid_id() & MIDR_CPU_MODEL_MASK) {
+#if defined(ARM_CPU_IMP_BRCM) && defined(BRCM_CPU_PART_VULCAN)
+        case MIDR_CPU_MODEL(ARM_CPU_IMP_BRCM, BRCM_CPU_PART_VULCAN):
+#endif
+        case MIDR_CPU_MODEL(0x43, 0x0af):  /* Cavium ThunderX2 */
+            vma->vm_page_prot = __pgprot_modify(vma->vm_page_prot, PTE_ATTRINDX_MASK,
+                                                PTE_ATTRINDX(MT_DEVICE_GRE) | PTE_PXN | PTE_UXN);
+    }
+#endif
+#endif
 	pfn = idx2pfn(dev, uar_index);
 
 	if (io_remap_pfn_range(vma, vma->vm_start, pfn,
```

**Comment by yosefe** [comment] 2018-09-03 17:35
@shamisp we confirmed that missing DEVICE_GRE for resource domain UAR is the cause of the issue. With the patch above, latency is as expected.

**Comment by yosefe** [comment] 2018-10-22 13:30
Will be fixed in MLNX_OFED 4.5 (fix merged to internal release branch)

**Comment by shamisp** [comment] 2018-10-22 16:13
@yosefe can you please share the release through Casey ?

**Comment by yosefe** [comment] 2018-12-04 15:21
@shamisp @rzambre  MLNX_OFED 4.5 with the fix is available from Mellanox website

**Closed** 2018-12-12 15:02 UTC
Labels: Bug, External
