### ISSUE TITLE
[mtt] osu_alltoall hangs with HW TM TX_POLICY=dcs_quota

### ISSUE THREAD

**Issue by amaslenn** [openucx/ucx#4713] opened 2020-01-30 07:38 UTC
Configuration:
```
OMPI: 4.0.3rc1
MOFED: MLNX_OFED_LINUX-4.6-1.0.1.1
Module: hpcx-gcc (2020-01-27)
Test module: mtt-tests/hpcx-gcc
Nodes: hercules x69 (ppn=32(x69), nodelist=clx-hercules-[001,006,010-018,020-048,050-061,065-075,077-080,127-128])
```

MTT log: http://e2e-gw.mellanox.com:4080/mnt/lustre/users/mtt/scratch/ucx_ompi/20200127_063413_684_534429_clx-hercules-001/html/test_stdout_BU5DSK.txt

The bug is sporadic, but 2-4 runs are enough to catch it. Couldn't reproduce with HW TM disabled and TX_POLICY=rand.

Cmd:
`mpirun -np 32 --display-map -mca btl self --tag-output --timestamp-output -mca pml ucx -mca coll '^hcoll' -x UCX_ERROR_SIGNALS=SIGILL,SIGSEGV,SIGBUS,SIGFPE,SIGABRT -x UCX_HANDLE_ERRORS=bt --bind-to core -x UCX_NET_DEVICES=mlx5_2:1 -mca osc ucx -x UCX_IB_REG_METHODS=rcache,direct -x UCX_TLS=dc_x,self,sm -x UCX_DC_MLX5_TM_ENABLE=y -x UCX_TM_SW_RNDV=y -x UCX_DC_MLX5_TX_POLICY=dcs_quota -x UCX_IB_SL=2 -mca pmix_base_async_modex 1 -mca mpi_add_procs_cutoff 0 -mca pmix_base_collect_data 0 --map-by node /hpc/local/benchmarks/daily/next/2020-01-27/hpcx-gcc-redhat7.4/ompi/tests/osu-micro-benchmarks-5.3.2/osu_alltoall`

Output:
```sh
Mon Jan 27 07:58:01 2020[1,0]<stdout>:# OSU MPI All-to-All Personalized Exchange Latency Test v5.3.2
Mon Jan 27 07:58:01 2020[1,0]<stdout>:# Size       Avg Latency(us)Mon Jan 27 07:58:01 2020[1,0]<stdout>:1                      20.22
Mon Jan 27 07:58:01 2020[1,0]<stdout>:2                      19.87
Mon Jan 27 07:58:01 2020[1,0]<stdout>:4                      20.02
Mon Jan 27 07:58:01 2020[1,0]<stdout>:8                      20.46
Mon Jan 27 07:58:01 2020[1,0]<stdout>:16                     20.90
Mon Jan 27 07:58:01 2020[1,0]<stdout>:32                     21.52
Mon Jan 27 07:58:01 2020[1,0]<stdout>:64                     22.90
Mon Jan 27 07:58:02 2020[1,0]<stdout>:128                    25.67
Mon Jan 27 07:58:02 2020[1,0]<stdout>:256                    24.31
Mon Jan 27 07:58:02 2020[1,0]<stdout>:512                    25.39
Mon Jan 27 07:58:02 2020[1,0]<stdout>:1024                   32.80
Mon Jan 27 07:58:02 2020[1,0]<stdout>:2048                   35.92
Mon Jan 27 07:58:02 2020[1,0]<stdout>:4096                   64.86
Mon Jan 27 07:58:02 2020[1,0]<stdout>:8192                   84.69
Mon Jan 27 07:58:02 2020[1,0]<stdout>:16384                 146.71
Mon Jan 27 07:58:02 2020[1,0]<stdout>:32768                 284.92
Mon Jan 27 07:58:02 2020[1,0]<stdout>:65536                 245.48
Mon Jan 27 07:58:02 2020[1,0]<stdout>:131072                432.31
Mon Jan 27 07:58:02 2020[1,0]<stdout>:262144               1059.87
```

Can also hang on msg_size=65536, haven't seen it hang on smaller messages.

**Comment by brminich** [comment] 2020-01-30 17:45
Can reproduce with:
 mpirun -np 32  -mca btl self -mca pml ucx -mca coll '^hcoll'  --bind-to core -x UCX_NET_DEVICES=mlx5_2:1 -mca osc ucx -x UCX_IB_REG_METHODS=rcache,direct -x UCX_TLS=dc_x,self,sm -x UCX_DC_MLX5_TM_ENABLE=y --map-by node -x UCX_RNDV_THRESH=16K  /hpc/local/benchmarks/daily/next/2020-01-27/hpcx-gcc-redhat7.4/ompi/tests/osu-micro-benchmarks-5.3.2/osu_alltoall

**Comment by brminich** [comment] 2020-01-30 18:07
Also hangs on 1K messages with
```
 mpirun -np 4  -mca btl self -mca pml ucx -mca coll '^hcoll'  --bind-to core -x UCX_NET_DEVICES=mlx5_2:1 -mca osc ucx -x UCX_IB_REG_METHODS=rcache,direct -x UCX_TLS=dc_x -x UCX_DC_MLX5_TM_ENABLE=y --map-by node -x UCX_RNDV_THRESH=1K  /hpc/local/benchmarks/daily/next/2020-01-27/hpcx-gcc-redhat7.4/ompi/tests/osu-micro-benchmarks-5.3.2/osu_alltoall
```

**Comment by brminich** [comment] 2020-01-31 13:22
looks like duplicate of #2934, reproduced on relatively old FW.
Could not reproduce on jazz, where  16.26.0276 FW is installed

**Comment by alinask** [comment] 2020-03-09 16:19
@brminich @amaslenn The duplicate issue was closed. Did this issue reproduce since? Can we close this ticket?

**Comment by amaslenn** [comment] 2020-03-10 06:56
> @brminich @amaslenn The duplicate issue was closed. Did this issue reproduce since? Can we close this ticket?

I haven't seen it for a while.

**Comment by brminich** [comment] 2020-03-10 07:11
should not be reproducible on "fresh" FW

**Closed** 2020-03-10 08:45 UTC
Labels: Bug, MTT
