### ISSUE TITLE
failure on dc_mlx5/uct_p2p_rma_test_alloc_methods.xfer_reg_odp/0

### ISSUE THREAD

**Issue by alinask** [openucx/ucx#2481] opened 2018-04-05 08:47 UTC
```
20:02:59 [ RUN      ] dc_mlx5/uct_p2p_rma_test_alloc_methods.xfer_reg_odp/0
20:02:59 [     INFO ] memory_type:host 0 1073741824 1x{0..1073741824} nocomp 32768 
20:03:02 [     INFO ] memory_type:host 65 [clx-ppc-04:155852:0:155852] ib_mlx5_log.c:113  FATAL: Error on QP 0x28f96 wqe[008]: Local length (synd 0x1 vend 0xda) opcode RDMA_READ
20:03:03 
20:03:03 /scrap/jenkins/workspace/hpc-ucx-pr/label/clx-ppc-04.mtl.labs.mlnx/worker/1/contrib/../src/uct/ib/mlx5/ib_mlx5_log.c: [ uct_ib_mlx5_completion_with_err() ]
20:03:03       ...
20:03:03       108     }
20:03:03       109 
20:03:03       110     ucs_log(log_level, "Error on QP 0x%x wqe[%03d]: %s (synd 0x%x vend 0x%x) opcode %s",
20:03:03 ==>   111             qp_num, wqe_counter, info, ecqe->syndrome, ecqe->vendor_err_synd,
20:03:03       112             uct_ib_mlx5_cqe_err_opcode(ecqe));
20:03:03       113     return status;
20:03:03       114 }
20:03:03 
20:03:03 ==== backtrace ====
20:03:03  0 0x0000000000037b40 uct_ib_mlx5_completion_with_err()  /scrap/jenkins/workspace/hpc-ucx-pr/label/clx-ppc-04.mtl.labs.mlnx/worker/1/contrib/../src/uct/ib/mlx5/ib_mlx5_log.c:111
20:03:03  1 0x0000000000076478 uct_dc_mlx5_iface_handle_failure()  /scrap/jenkins/workspace/hpc-ucx-pr/label/clx-ppc-04.mtl.labs.mlnx/worker/1/contrib/../src/uct/ib/dc/accel/dc_mlx5.c:936
20:03:03  2 0x0000000000038e50 uct_ib_mlx5_check_completion()  /scrap/jenkins/workspace/hpc-ucx-pr/label/clx-ppc-04.mtl.labs.mlnx/worker/1/contrib/../src/uct/ib/mlx5/ib_mlx5.c:262
20:03:03  3 0x000000000007841c uct_ib_mlx5_poll_cq()  /scrap/jenkins/workspace/hpc-ucx-pr/label/clx-ppc-04.mtl.labs.mlnx/worker/1/contrib/../src/uct/ib/mlx5/ib_mlx5.inl:32
20:03:03  4 0x00000000101a1cf4 uct_test::progress()  /scrap/jenkins/workspace/hpc-ucx-pr/label/clx-ppc-04.mtl.labs.mlnx/worker/1/contrib/../src/ucs/datastruct/callbackq.h:208
20:03:03  5 0x000000001019d7a8 uct_p2p_test::blocking_send()  /scrap/jenkins/workspace/hpc-ucx-pr/label/clx-ppc-04.mtl.labs.mlnx/worker/1/contrib/../test/gtest/uct/uct_p2p_test.cc:272
20:03:03  6 0x00000000101692a4 uct_p2p_rma_test::test_xfer()  /scrap/jenkins/workspace/hpc-ucx-pr/label/clx-ppc-04.mtl.labs.mlnx/worker/1/contrib/../test/gtest/uct/test_p2p_rma.cc:68
20:03:03  7 0x00000000101a09b8 uct_p2p_test::test_xfer_print<ucs::detail::message_stream>()  /scrap/jenkins/workspace/hpc-ucx-pr/label/clx-ppc-04.mtl.labs.mlnx/worker/1/contrib/../test/gtest/uct/uct_p2p_test.cc:140
20:03:03  8 0x000000001019c83c uct_p2p_test::test_xfer_multi_mem_type()  /scrap/jenkins/workspace/hpc-ucx-pr/label/clx-ppc-04.mtl.labs.mlnx/worker/1/contrib/../test/gtest/uct/uct_p2p_test.cc:200
20:03:03  9 0x000000001019d4f0 uct_p2p_test::test_xfer_multi()  /scrap/jenkins/workspace/hpc-ucx-pr/label/clx-ppc-04.mtl.labs.mlnx/worker/1/contrib/../test/gtest/uct/uct_p2p_test.cc:162
20:03:03 10 0x000000001043ce18 uct_p2p_rma_test_alloc_methods::test_get_zcopy()  /scrap/jenkins/workspace/hpc-ucx-pr/label/clx-ppc-04.mtl.labs.mlnx/worker/1/contrib/../test/gtest/uct/ib/test_ib_xfer.cc:44
20:03:03 11 0x00000000100ac8a8 ucs::test_base::run()  /scrap/jenkins/workspace/hpc-ucx-pr/label/clx-ppc-04.mtl.labs.mlnx/worker/1/contrib/../test/gtest/common/test.cc:270
20:03:03 12 0x00000000101428dc uct_p2p_test::TestBody()  /scrap/jenkins/workspace/hpc-ucx-pr/label/clx-ppc-04.mtl.labs.mlnx/worker/1/contrib/../test/gtest/uct/uct_p2p_test.h:24
20:03:03 13 0x000000001009da74 testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>()  /scrap/jenkins/workspace/hpc-ucx-pr/label/clx-ppc-04.mtl.labs.mlnx/worker/1/contrib/../test/gtest/common/gtest-all.cc:3562
20:03:03 14 0x000000001008d4fc testing::Test::Run()  /scrap/jenkins/workspace/hpc-ucx-pr/label/clx-ppc-04.mtl.labs.mlnx/worker/1/contrib/../test/gtest/common/gtest-all.cc:3635
20:03:03 15 0x000000001008d64c testing::TestInfo::Run()  /scrap/jenkins/workspace/hpc-ucx-pr/label/clx-ppc-04.mtl.labs.mlnx/worker/1/contrib/../test/gtest/common/gtest-all.cc:3812
20:03:03 16 0x000000001008d898 testing::TestCase::Run()  /scrap/jenkins/workspace/hpc-ucx-pr/label/clx-ppc-04.mtl.labs.mlnx/worker/1/contrib/../test/gtest/common/gtest-all.cc:3930
20:03:03 17 0x00000000100936b8 testing::internal::UnitTestImpl::RunAllTests()  /scrap/jenkins/workspace/hpc-ucx-pr/label/clx-ppc-04.mtl.labs.mlnx/worker/1/contrib/../test/gtest/common/gtest-all.cc:5802
20:03:03 18 0x0000000010093aec testing::internal::UnitTestImpl::RunAllTests()  /scrap/jenkins/workspace/hpc-ucx-pr/label/clx-ppc-04.mtl.labs.mlnx/worker/1/contrib/../test/gtest/common/gtest-all.cc:5719
20:03:03 19 0x0000000010025c14 main()  /scrap/jenkins/workspace/hpc-ucx-pr/label/clx-ppc-04.mtl.labs.mlnx/worker/1/contrib/../test/gtest/common/gtest.h:20059
20:03:03 20 0x0000000000024980 generic_start_main.isra.0()  libc-start.c:0
20:03:03 21 0x0000000000024b74 __libc_start_main()  ???:0
20:03:03 ===================
```
on ppc:
http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6687/label=clx-ppc-04.mtl.labs.mlnx,worker=1/console

**Comment by yosefe** [comment] 2018-04-05 20:17
duplicate of #2433

**Closed** 2018-04-05 20:17 UTC
Labels: bug, duplicate, external, jenkins
