### ISSUE TITLE
hang in dc_mlx5/uct_amo_cswap_test.cswap64/0

### ISSUE THREAD

**Issue by brminich** [openucx/ucx#3008] opened 2018-11-01 06:33 UTC
http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8153/label=hpc-test-node-upstream,worker=0/console

```
12:20:47 [----------] 2 tests from test_mpool (297 ms total)
12:20:47 
12:20:47 [----------] 1 test from dc_mlx5/uct_amo_cswap_test
12:20:47 [ RUN      ] dc_mlx5/uct_amo_cswap_test.cswap64/0
15:00:36 
make: *** [test] Terminated
15:00:36 
Build step 'Execute shell' marked build as failure
15:00:36 TAP Reports Processing: START
15:00:36 Looking for TAP results report in workspace using pattern: **/*.tap
```

**Comment by yosefe** [comment] 2018-11-01 07:38
duplicate of #3007 - dci hang on upstream

**Closed** 2018-11-01 07:39 UTC
Labels: Bug, Duplicate, Jenkins
