### ISSUE TITLE
[mtt] harlem hung

### ISSUE THREAD

**Issue by avildema** [openucx/ucx#5573] opened 2020-08-14 09:32 UTC
Configuration
```
OMPI: 4.0.4rc3
MOFED: MLNX_OFED_LINUX-5.0-1.0.0.0
Module: hpcx-gcc (2020-08-13)
Test module: none
Nodes: jazz x2 (ppn=28(x2), nodelist=jazz[20,26])
```
 
MTT log:
 
http://hpcweb.lab.mtl.com/hpc/mtr_scrap/users/mtt/scratch/shmem/20200813_190931_182086_1675_jazz20.swx.labs.mlnx/html/test_stdout_QU72WJ.txt
 
Cmd:
`hpc/local/benchmarks/daily/next/2020-08-13/hpcx-gcc-redhat7.6/ompi/bin/oshrun -np 56 --bind-to core -mca oshmem_proc_group_cache_size 10000 -mca sshmem ucx -mca atomic ucx -mca coll '^hcoll' -mca coll_hcoll_enable 0 -mca spml ucx -mca pml ucx -x UCX_HANDLE_ERRORS=bt -x UCX_TLS=ud_x -x UCX_UD_TIMEOUT=10m -x UCX_NET_DEVICES=mlx5_2:1 --map-by node -x UCX_IB_REG_MT_THRESH=1 -x UCX_IB_REG_MT_CHUNK=1K -x SHMEM_SYMMETRIC_HEAP_SIZE=2074M /hpc/mtr_scrap/users/mtt/scratch/shmem/20200813_190931_182086_1675_jazz20.swx.labs.mlnx/installs/ISqj/tests/harlem/hamr/hamr -m 1024 -M 65536 --time-init -i 1 108`
 
Output:
```sh
 =============================================================*********************************************************
* HAMR 1.5.0
* GiB of mem                       = 108.00
* Number of PEs                    = 56
* Table size per PE (elements)     = 129424240
* Table size per PE (GiB)          = 1.929
* Max bucket overhead per PE (GiB) = 0.003
* Initial fill count per PE        = 116481816
* Total size (elements)            = 6522981696
* Scratch size (elements)          = 1048576
* Seed value                       = 1597368741
* Sync throttle                    = 90.00%
*********************************************************
Init time: 1.5095 seconds
   Message	 Wall	     B/W per PE (MiB/s)	  (GiB/s)
  size (B)	 time	    MIN	    AVG	    MAX	    TOTAL      1024	2702.7	    0.7	    0.7	    0.7	    0.036

kill by timeout

```

**Comment by brminich** [comment] 2021-07-01 07:20
can't reproduce within 10 hrs.
closing until it is seen again

**Closed by brminich** 2021-07-01 07:20 UTC
Labels: Bug, MTT
