### ISSUE TITLE
transport retry count exceeded in many-to-one tests

### ISSUE THREAD

**Issue by amaslenn** [openucx/ucx#1920] opened 2017-10-17 08:10 UTC
Configuration:
```
OMPI: 4.0.0a1
Hercules x25 (clx-hercules-[036,054-055,057,059-063,069,073,076,080-082,084-085,087,089-092,097-098,112])
```
MTT: http://e2e-gw.mellanox.com:4080//mnt/lustre/users/mtt/scratch/shmem/20171017_051617_17042_17161_clx-hercules-054/html/test_stdout_l1nyGu.txt

All devices are up:
```
$pdsh -w "clx-hercules-[036,054-055,057,059-063,069,073,076,080-082,084-085,087,089-092,097-098,112]" 'ibv_devinfo -d mlx5_0 | grep state' | dshbak -c
----------------
clx-hercules-[036,054-055,057,059-063,069,073,076,080-082,084-085,087,089-092,097-098,112]
----------------
                        state:                  PORT_ACTIVE (4)
```

Cmd:
`env OMPI_MCA_btl_openib_warn_default_gid_prefix=0 OMPI_MCA_sshmem_verbs_hca_name=mlx5_0:1 OMPI_MCA_btl_openib_if_include=mlx5_0:1 MXM_RDMA_PORTS=mlx5_0:1 UCX_NET_DEVICES=mlx5_0:1 OMPI_MCA_osc=ucx OMPI_MCA_sshmem=mmap OMPI_MCA_spml_ucx_heap_reg_nb=0 'OMPI_MCA_coll=^hcoll' OMPI_MCA_coll_hcoll_enable=0 OMPI_MCA_spml=ucx OMPI_MCA_pml=ucx UCX_TLS=dc_x SHMEM_SYMMETRIC_HEAP_SIZE=128M srun --cpu_bind=core -m block --mpi=pmi2 -n 25 --nodes=25 -p hercules /mnt/lustre/users/mtt/scratch/shmem/20171017_051617_17042_17161_clx-hercules-054/installs/h5Tu/tests/verifier/tests-mellanox.git/verifier/install/bin/oshmem_test exec --no-colour --task=analysis:tc2 --task=analysis:tc3 --task=analysis:tc4 --task=analysis:tc5 --duration 10`

Output:
```
[clx-hercules-061:15303] OPAL ERROR: Not found in file btl_openib_component.c at line 2441
...
[clx-hercules-061:15303] OPAL ERROR: Not found in file btl_openib_component.c at line 2441
OpenSHMEM Verification Tool ver."1.2.60"
**********************************
* Log file: none
* Host: clx-hercules-036
* Output level: 4
* Log level: 0
**********************************

[1508227003.991871] [clx-hercules-084:26649:0]    ib_mlx5_log.c:109  UCX  ERROR Error on QP 0xe87a wqe[35]: Transport retry count exceeded (synd 0x15 vend 0x81) opcode SEND
[1508227003.991911] [clx-hercules-084:26649:0]     ucp_worker.c:380  UCX  ERROR Error Endpoint timeout was not handled for ep 0x2366cf0 - dc_mlx5/mlx5_0:1
```

**Comment by amaslenn** [comment] 2017-10-17 08:12
One more: http://e2e-gw.mellanox.com:4080/mnt/lustre/users/mtt/scratch/shmem/20171016_201633_7562_17116_clx-hercules-001/html/test_stdout_XUrCql.txt

**Comment by amaslenn** [comment] 2017-10-19 06:06
One more: http://e2e-gw.mellanox.com:4080//mnt/lustre/users/mtt/scratch/shmem/20171019_011142_14786_17674_clx-hercules-018/html/test_stdout_IDrqye.txt

**Comment by alex--m** [comment] 2018-01-23 09:46
I think I'm getting the same with RC, on 120 orion nodes.

Commandline: `salloc -p orion -N 120 mpirun --bind-to core --report-bindings $HPCX_MPI_TESTS_DIR/osu-micro-benchmarks-5.3.2/osu_gather 1> osu_gather-n120-ppn28.txt 2>>err &`

Output:
```
$cat osu_gather-n120-ppn28.txt

# OSU MPI Gather Latency Test v5.3.2
# Size       Avg Latency(us)
1                       0.91
2                       0.87
4                       0.88
8                       0.92
16                      1.02
32                      1.20
64                      1.29
128                     6.72
256                     7.09
512                    10.13
1024                   12.58
2048                   17.51
4096                   27.58
[1516700569.377563] [clx-orion-059:5831 :0]    ib_mlx5_log.c:113  UCX  ERROR Error on QP 0x6179 wqe[0]: Transport retry count exceeded (synd 0x15 vend 0x81) opcode SEND
[1516700569.378516] [clx-orion-059:5831 :0]     ucp_worker.c:437  UCX  ERROR Error Endpoint timeout was not handled for ep 0x1bdfee0 - rc_mlx5/mlx5_2:1
[1516700569.390309] [clx-orion-114:26149:0]    ib_mlx5_log.c:113  UCX  ERROR Error on QP 0x16495 wqe[0]: Transport retry count exceeded (synd 0x15 vend 0x81) opcode SEND
[1516700569.391567] [clx-orion-114:26149:0]     ucp_worker.c:437  UCX  ERROR Error Endpoint timeout was not handled for ep 0x1a8f610 - rc_mlx5/mlx5_2:1
[1516700569.489246] [clx-orion-009:4360 :0]    ib_mlx5_log.c:113  UCX  ERROR Error on QP 0x827 wqe[0]: Transport retry count exceeded (synd 0x15 vend 0x81) opcode SEND
[1516700569.491537] [clx-orion-009:4360 :0]     ucp_worker.c:437  UCX  ERROR Error Endpoint timeout was not handled for ep 0x1d3d980 - rc_mlx5/mlx5_2:1
[1516700569.491547] [clx-orion-009:4360 :0]    ib_mlx5_log.c:113  UCX  ERROR Error on QP 0x822 wqe[0]: Transport retry count exceeded (synd 0x15 vend 0x81) opcode SEND
[1516700569.492589] [clx-orion-009:4360 :0]     ucp_worker.c:437  UCX  ERROR Error Endpoint timeout was not handled for ep 0x1d19fa0 - rc_mlx5/mlx5_2:1
[1516700569.492597] [clx-orion-009:4360 :0]    ib_mlx5_log.c:113  UCX  ERROR Error on QP 0x825 wqe[0]: Transport retry count exceeded (synd 0x15 vend 0x81) opcode SEND
[1516700569.493696] [clx-orion-009:4360 :0]     ucp_worker.c:437  UCX  ERROR Error Endpoint timeout was not handled for ep 0x1d34c70 - rc_mlx5/mlx5_2:1
[1516700569.493703] [clx-orion-009:4360 :0]    ib_mlx5_log.c:113  UCX  ERROR Error on QP 0x823 wqe[0]: Transport retry count exceeded (synd 0x15 vend 0x81) opcode SEND
[1516700569.494538] [clx-orion-009:4360 :0]     ucp_worker.c:437  UCX  ERROR Error Endpoint timeout was not handled for ep 0x1d22a50 - rc_mlx5/mlx5_2:1
[1516700569.494545] [clx-orion-009:4360 :0]    ib_mlx5_log.c:113  UCX  ERROR Error on QP 0x820 wqe[0]: Transport retry count exceeded (synd 0x15 vend 0x81) opcode SEND
[1516700569.495325] [clx-orion-009:4360 :0]     ucp_worker.c:437  UCX  ERROR Error Endpoint timeout was not handled for ep 0x1d07cd0 - rc_mlx5/mlx5_2:1
[1516700569.495332] [clx-orion-009:4360 :0]    ib_mlx5_log.c:113  UCX  ERROR Error on QP 0x824 wqe[0]: Transport retry count exceeded (synd 0x15 vend 0x81) opcode SEND
[1516700569.496029] [clx-orion-009:4360 :0]     ucp_worker.c:437  UCX  ERROR Error Endpoint timeout was not handled for ep 0x1d225d0 - rc_mlx5/mlx5_2:1
[1516700569.572416] [clx-orion-011:25238:0]    ib_mlx5_log.c:113  UCX  ERROR Error on QP 0x6211 wqe[0]: Transport retry count exceeded (synd 0x15 vend 0x81) opcode SEND
[1516700569.585598] [clx-orion-011:25238:0]     ucp_worker.c:437  UCX  ERROR Error Endpoint timeout was not handled for ep 0x1d44e80 - rc_mlx5/mlx5_2:1
[1516700569.585610] [clx-orion-011:25238:0]    ib_mlx5_log.c:113  UCX  ERROR Error on QP 0x620d wqe[0]: Transport retry count exceeded (synd 0x15 vend 0x81) opcode SEND
[1516700569.586469] [clx-orion-011:25238:0]     ucp_worker.c:437  UCX  ERROR Error Endpoint timeout was not handled for ep 0x1d2af90 - rc_mlx5/mlx5_2:1
[1516700569.586478] [clx-orion-011:25238:0]    ib_mlx5_log.c:113  UCX  ERROR Error on QP 0x620c wqe[0]: Transport retry count exceeded (synd 0x15 vend 0x81) opcode SEND
[1516700569.587419] [clx-orion-011:25238:0]     ucp_worker.c:437  UCX  ERROR Error Endpoint timeout was not handled for ep 0x1d22850 - rc_mlx5/mlx5_2:1
[1516700569.587429] [clx-orion-011:25238:0]    ib_mlx5_log.c:113  UCX  ERROR Error on QP 0x6209 wqe[0]: Transport retry count exceeded (synd 0x15 vend 0x81) opcode SEND
[1516700569.588335] [clx-orion-011:25238:0]     ucp_worker.c:437  UCX  ERROR Error Endpoint timeout was not handled for ep 0x1cf0b20 - rc_mlx5/mlx5_2:1
[1516700569.588344] [clx-orion-011:25238:0]    ib_mlx5_log.c:113  UCX  ERROR Error on QP 0x620f wqe[0]: Transport retry count exceeded (synd 0x15 vend 0x81) opcode SEND
[1516700569.589068] [clx-orion-011:25238:0]     ucp_worker.c:437  UCX  ERROR Error Endpoint timeout was not handled for ep 0x1d44a20 - rc_mlx5/mlx5_2:1
[1516700569.589077] [clx-orion-011:25238:0]    ib_mlx5_log.c:113  UCX  ERROR Error on QP 0x6210 wqe[0]: Transport retry count exceeded (synd 0x15 vend 0x81) opcode SEND
[1516700569.594107] [clx-orion-050:11718:0]    ib_mlx5_log.c:113  UCX  ERROR Error on QP 0x6176 wqe[0]: Transport retry count exceeded (synd 0x15 vend 0x81) opcode SEND
[1516700569.589815] [clx-orion-011:25238:0]     ucp_worker.c:437  UCX  ERROR Error Endpoint timeout was not handled for ep 0x1d45640 - rc_mlx5/mlx5_2:1
[1516700569.598593] [clx-orion-010:31714:0]    ib_mlx5_log.c:113  UCX  ERROR Error on QP 0x61f9 wqe[0]: Transport retry count exceeded (synd 0x15 vend 0x81) opcode SEND
[1516700569.595076] [clx-orion-050:11718:0]     ucp_worker.c:437  UCX  ERROR Error Endpoint timeout was not handled for ep 0x1c18030 - rc_mlx5/mlx5_2:1
[1516700569.600180] [clx-orion-010:31714:0]     ucp_worker.c:437  UCX  ERROR Error Endpoint timeout was not handled for ep 0x1d5e7a0 - rc_mlx5/mlx5_2:1
[1516700569.600192] [clx-orion-010:31714:0]    ib_mlx5_log.c:113  UCX  ERROR Error on QP 0x61f5 wqe[0]: Transport retry count exceeded (synd 0x15 vend 0x81) opcode SEND
[1516700569.601083] [clx-orion-010:31714:0]     ucp_worker.c:437  UCX  ERROR Error Endpoint timeout was not handled for ep 0x1d33870 - rc_mlx5/mlx5_2:1
[1516700569.601092] [clx-orion-010:31714:0]    ib_mlx5_log.c:113  UCX  ERROR Error on QP 0x61f3 wqe[0]: Transport retry count exceeded (synd 0x15 vend 0x81) opcode SEND
[1516700569.602001] [clx-orion-010:31714:0]     ucp_worker.c:437  UCX  ERROR Error Endpoint timeout was not handled for ep 0x1cf8f80 - rc_mlx5/mlx5_2:1
[1516700569.602008] [clx-orion-010:31714:0]    ib_mlx5_log.c:113  UCX  ERROR Error on QP 0x61f6 wqe[0]: Transport retry count exceeded (synd 0x15 vend 0x81) opcode SEND
[1516700569.602731] [clx-orion-010:31714:0]     ucp_worker.c:437  UCX  ERROR Error Endpoint timeout was not handled for ep 0x1d2ab50 - rc_mlx5/mlx5_2:1
[1516700569.602738] [clx-orion-010:31714:0]    ib_mlx5_log.c:113  UCX  ERROR Error on QP 0x61f7 wqe[0]: Transport retry count exceeded (synd 0x15 vend 0x81) opcode SEND
[1516700569.603648] [clx-orion-010:31714:0]     ucp_worker.c:437  UCX  ERROR Error Endpoint timeout was not handled for ep 0x1d33010 - rc_mlx5/mlx5_2:1
[1516700569.603656] [clx-orion-010:31714:0]    ib_mlx5_log.c:113  UCX  ERROR Error on QP 0x61f4 wqe[0]: Transport retry count exceeded (synd 0x15 vend 0x81) opcode SEND
[1516700569.604455] [clx-orion-010:31714:0]     ucp_worker.c:437  UCX  ERROR Error Endpoint timeout was not handled for ep 0x1d33400 - rc_mlx5/mlx5_2:1
[1516700569.717505] [clx-orion-060:11291:0]    ib_mlx5_log.c:113  UCX  ERROR Error on QP 0x5104 wqe[0]: Transport retry count exceeded (synd 0x15 vend 0x81) opcode SEND
[1516700569.719088] [clx-orion-060:11291:0]     ucp_worker.c:437  UCX  ERROR Error Endpoint timeout was not handled for ep 0x1bdf210 - rc_mlx5/mlx5_2:1
[1516700569.759661] [clx-orion-064:1359 :0]    ib_mlx5_log.c:113  UCX  ERROR Error on QP 0x8328 wqe[0]: Transport retry count exceeded (synd 0x15 vend 0x81) opcode SEND
[1516700569.760459] [clx-orion-064:1359 :0]     ucp_worker.c:437  UCX  ERROR Error Endpoint timeout was not handled for ep 0x1ba8bd0 - rc_mlx5/mlx5_2:1
[1516700569.850845] [clx-orion-014:9165 :0]    ib_mlx5_log.c:113  UCX  ERROR Error on QP 0x609a wqe[0]: Transport retry count exceeded (synd 0x15 vend 0x81) opcode SEND
[1516700569.851900] [clx-orion-014:9165 :0]     ucp_worker.c:437  UCX  ERROR Error Endpoint timeout was not handled for ep 0x1d44300 - rc_mlx5/mlx5_2:1
[1516700569.851911] [clx-orion-014:9165 :0]    ib_mlx5_log.c:113  UCX  ERROR Error on QP 0x6098 wqe[0]: Transport retry count exceeded (synd 0x15 vend 0x81) opcode SEND
[1516700569.852642] [clx-orion-014:9165 :0]     ucp_worker.c:437  UCX  ERROR Error Endpoint timeout was not handled for ep 0x1d54bc0 - rc_mlx5/mlx5_2:1
[1516700569.852651] [clx-orion-014:9165 :0]    ib_mlx5_log.c:113  UCX  ERROR Error on QP 0x6095 wqe[0]: Transport retry count exceeded (synd 0x15 vend 0x81) opcode SEND
[1516700569.853268] [clx-orion-014:9165 :0]     ucp_worker.c:437  UCX  ERROR Error Endpoint timeout was not handled for ep 0x1d213d0 - rc_mlx5/mlx5_2:1
[1516700582.936080] [clx-orion-039:7128 :0]    ib_mlx5_log.c:113  UCX  ERROR Error on QP 0x614a wqe[0]: Transport retry count exceeded (synd 0x15 vend 0x81) opcode SEND
[1516700582.936929] [clx-orion-016:9617 :0]    ib_mlx5_log.c:113  UCX  ERROR Error on QP 0x605a wqe[0]: Transport retry count exceeded (synd 0x15 vend 0x81) opcode SEND
[1516700582.936518] [clx-orion-012:12602:0]    ib_mlx5_log.c:113  UCX  ERROR Error on QP 0x603e wqe[0]: Transport retry count exceeded (synd 0x15 vend 0x81) opcode SEND
[1516700582.940829] [clx-orion-039:7128 :0]     ucp_worker.c:437  UCX  ERROR Error Endpoint timeout was not handled for ep 0x16c4770 - rc_mlx5/mlx5_2:1
[1516700582.937968] [clx-orion-016:9617 :0]     ucp_worker.c:437  UCX  ERROR Error Endpoint timeout was not handled for ep 0x1c07930 - rc_mlx5/mlx5_2:1
[1516700582.937981] [clx-orion-016:9617 :0]    ib_mlx5_log.c:113  UCX  ERROR Error on QP 0x605f wqe[0]: Transport retry count exceeded (synd 0x15 vend 0x81) opcode SEND
[1516700582.938739] [clx-orion-016:9617 :0]     ucp_worker.c:437  UCX  ERROR Error Endpoint timeout was not handled for ep 0x1c21a10 - rc_mlx5/mlx5_2:1
[1516700582.941628] [clx-orion-012:12602:0]     ucp_worker.c:437  UCX  ERROR Error Endpoint timeout was not handled for ep 0x16c5250 - rc_mlx5/mlx5_2:1
8192                 7488.32
16384                8727.08
32768               12060.72
65536               22148.32
131072              40553.41
<hang?>
```

**Comment by evgeny-leksikov** [comment] 2018-01-26 11:38
@alex--m seems like your case was environment or hcoll related but not related with original issue. I can't reproduce it today but it was stable during last 3 days. Could you confirm if it works now for you as well?

**Comment by evgeny-leksikov** [comment] 2018-01-27 17:50
@amaslenn `oshmem_test` and `mx_bug` works fine duling 12h loop, pls check latest mtt logs if it's still reproducible.

**Comment by amaslenn** [comment] 2018-01-29 09:11
Don't see these anymore.

**Comment by alinask** [comment] 2018-01-29 09:54
let's wait for @alex--m 's response before closing.

**Comment by alex--m** [comment] 2018-02-07 09:06
Checked yesterday, looks good now. Let's close it.

**Closed** 2018-02-07 09:11 UTC
Labels: bug, mtt
