### ISSUE TITLE
[mtt] segfault in mpich_tests_mpi_pt2pt

### ISSUE THREAD

**Issue by amaslenn** [openucx/ucx#2223] opened 2018-01-28 10:23 UTC
Configuration:
```
OMPI: 3.1.0rc1
Orion x10 (clx-orion-[057-064,127-128])
```

MTT log: http://e2e-gw.mellanox.com:4080//mnt/lustre/users/mtt/scratch/ucx_ompi/20180128_040152_862_53002_clx-orion-057/html/test_stdout_V5k4Au.txt

Cmd:
`mpirun -np 280 -mca btl self --tag-output --timestamp-output -mca pml ucx -mca coll '^hcoll' --bind-to core -x UCX_NET_DEVICES=mlx5_2:1 -x UCX_IB_GID_INDEX=3 -mca osc ucx -x UCX_IB_ETH_PAUSE_ON=y -x UCX_TLS=rc_x,sm -mca opal_pmix_base_async_modex 0 -mca mpi_add_procs_cutoff 100000 --map-by node /mnt/lustre/users/mtt/scratch/ucx_ompi/20180128_040152_862_53002_clx-orion-057/installs/uMIJ/tests/mpich_tests/mpich-mellanox.git/test/mpi/pt2pt/rcancel`

Output:
```sh
Sun Jan 28 12:09:59 2018[1,279]<stderr>:[clx-orion-056:16633:0:16633] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x140)
Sun Jan 28 12:09:59 2018[1,279]<stderr>:==== backtrace ====
Sun Jan 28 12:09:59 2018[1,279]<stderr>: 0 0x0000000000039792 ompi_errhandler_request_invoke()  /hpc/local/benchmarks/hpcx_install_2018-01-27/src/hpcx-gcc-redhat7.4/ompi-v3.1.x/ompi/errhandler/errhandler_invoke.c:169
Sun Jan 28 12:09:59 2018[1,279]<stderr>: 1 0x0000000000402770 main()  ???:0
Sun Jan 28 12:09:59 2018[1,279]<stderr>: 2 0x0000000000021c05 __libc_start_main()  ???:0
Sun Jan 28 12:09:59 2018[1,279]<stderr>: 3 0x00000000004024d9 _start()  ???:0
Sun Jan 28 12:09:59 2018[1,279]<stderr>:===================
Sun Jan 28 12:09:59 2018[1,279]<stderr>:[clx-orion-056:16633:0:16633] Process frozen...
```

**Note** that it reproduces from time to time.

**Comment by yosefe** [comment] 2018-01-28 10:27
seems like duplicate of #1928?

**Comment by amaslenn** [comment] 2018-01-28 10:50
Can be, but this one is ROCE.

**Closed** 2018-01-30 10:22 UTC
Labels: bug, mtt
