### ISSUE TITLE
(title changed) OpenMPI bogus warnings "UCX is unable to handle VM_UNMAP"

### ISSUE THREAD

**Issue by zerothi** [openucx/ucx#3686] opened 2019-06-11 09:22 UTC
I am running:

```bash
$> ucx_info -v
# UCT version=1.5.1 revision 7e67a4b
# configured with: --enable-optimizations --disable-logging --disable-debug --disable-assertions --disable-params-check --with-rc --with-ud --with-dc --with-cm --with-mlx5-dv --with-ib-hw-tm --with-dm --with-mcpu --with-march --prefix=/opt/gnu/9.1.0/ucx/1.5.1
```
and OpenMPI 4.0.1 and GCC 9.1.0.

I am running on a local machine, which of course does not make sense with all the options, but configure just disables the extended features.

However, when running the simplest MPI program (only `MPI_init` and `MPI_finalize`) I get the following error:

```bash
[1560244589.726560] [nicpa-dtu:6527 :0]            sys.c:619  UCX  ERROR shmget(size=2097152 flags=0xfb0) for mm_recv_desc failed: Operation not permitted, please check shared memory limits by 'ipcs -l'
[1560244589.726561] [nicpa-dtu:6528 :0]            sys.c:619  UCX  ERROR shmget(size=2097152 flags=0xfb0) for mm_recv_desc failed: Operation not permitted, please check shared memory limits by 'ipcs -l'
```

```bash
$> ipcs -l

------ Messages Limits --------
max queues system wide = 32000
max size of message (bytes) = 8192
default max size of queue (bytes) = 16384

------ Shared Memory Limits --------
max number of segments = 4096
max seg size (kbytes) = 18014398509465599
max total shared memory (kbytes) = 18014398442373116
min seg size (bytes) = 1

------ Semaphore Limits --------
max number of arrays = 32000
max semaphores per array = 32000
max semaphores system wide = 1024000000
max ops per semop call = 500
semaphore max value = 32767
```

It seems unrelated to #3023 and #3668 since this is a local machine.

**Comment by yosefe** [comment] 2019-06-11 09:24
actually, it seems like #3023. 
what is the output of `capsh --print|grep ipc`?
can you pls check if UCX master branch works?

**Comment by zerothi** [comment] 2019-06-11 09:32
```bash
$> capsh --print|grep ipc
Bounding set =cap_chown,cap_dac_override,cap_dac_read_search,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_linux_immutable,cap_net_bind_service,cap_net_broadcast,cap_net_admin,cap_net_raw,cap_ipc_lock,cap_ipc_owner,cap_sys_module,cap_sys_rawio,cap_sys_chroot,cap_sys_ptrace,cap_sys_pacct,cap_sys_admin,cap_sys_boot,cap_sys_nice,cap_sys_resource,cap_sys_time,cap_sys_tty_config,cap_mknod,cap_lease,cap_audit_write,cap_audit_control,cap_setfcap,cap_mac_override,cap_mac_admin,cap_syslog,cap_wake_alarm,cap_block_suspend,cap_audit_read
```

I'll check with master

**Comment by zerothi** [comment] 2019-06-11 09:33
@yosefe but #3023 was fixed before 1.5.1 was released? Ok, i'll try master ;)

**Comment by yosefe** [comment] 2019-06-11 09:36
@zerothi v1.5.x was branched before the fix (on Nov'18, fix was in Jan'18)

**Comment by zerothi** [comment] 2019-06-11 09:38
ah, ok. :)

**Comment by yosefe** [comment] 2019-06-17 07:34
@shamisp as we discussed on the dev call, we would not port it to v1.5.2

@zerothi, did v1.6.x/master solve the problem?

**Comment by zerothi** [comment] 2019-06-17 08:23
@yosefe thanks for following up!

I just tried with 1.6.0-rc2. It seems to be resolved. However, now I get:
```bash
[nicpa-dtu:24568] ../../../../../opal/mca/common/ucx/common_ucx.c:146  Warning: UCX is unable to handle VM_UNMAP event. This may cause performance degradation or data corruption. Pls try adding --mca opal_common_ucx_opal_mem_hooks 1 to mpirun/oshrun command line to resolve this issue.
[nicpa-dtu:24569] ../../../../../opal/mca/common/ucx/common_ucx.c:146  Warning: UCX is unable to handle VM_UNMAP event. This may cause performance degradation or data corruption. Pls try adding --mca opal_common_ucx_opal_mem_hooks 1 to mpirun/oshrun command line to resolve this issue.
```
which could be OMPI, but it seems related to UCX?

**Comment by yosefe** [comment] 2019-06-17 10:57
@zerothi it's probably a real issue, which UCX detects as of v1.6.x. 
Can you try running with "-mca btl ^uct"?
see also https://github.com/openucx/ucx/issues/3581

**Comment by zerothi** [comment] 2019-06-17 11:26
I did this:
```bash
mpirun --mca opal_common_ucx_opal_mem_hooks 1 --mca btl ^uct -np 2 ./test
```
and got the same:
```bash
[nicpa-dtu:29789] ../../../../../opal/mca/common/ucx/common_ucx.c:146  Warning: UCX is unable to handle VM_UNMAP event. This may cause performance degradation or data corruption. 
[nicpa-dtu:29790] ../../../../../opal/mca/common/ucx/common_ucx.c:146  Warning: UCX is unable to handle VM_UNMAP event. This may cause performance degradation or data corruption. 
      ```

**Comment by zerothi** [comment] 2019-06-17 11:28
@yosefe should I move this to the mentioned ticket?

**Comment by yosefe** [comment] 2019-06-17 11:46
@zerothi can you try just this:
`mpirun --mca opal_common_ucx_opal_mem_hooks 1 --mca btl ^uct -np 2 ./test` ?

(There is also other issue (fixed in UCX master, @hoopoepg port it to v1.6.x as well) that when you would pass '--mca opal_common_ucx_opal_mem_hooks 1' as recommended by the warning message, the warning still shows)

**Comment by zerothi** [comment] 2019-06-17 11:54
I get the same output:
```bash
$> mpirun --mca btl ^uct -np 2 ./test                                                                                                                                                                                           
[nicpa-dtu:20776] ../../../../../opal/mca/common/ucx/common_ucx.c:146  Warning: UCX is unable to handle VM_UNMAP event. This may cause performance degradation or data corruption. Pls try adding --mca opal_common_ucx_opal_mem_hooks 1 to mpirun/oshrun command line to resolve this issue.
[nicpa-dtu:20777] ../../../../../opal/mca/common/ucx/common_ucx.c:146  Warning: UCX is unable to handle VM_UNMAP event. This may cause performance degradation or data corruption. Pls try adding --mca opal_common_ucx_opal_mem_hooks 1 to mpirun/oshrun command line to resolve this issue.

```

**Comment by zerothi** [comment] 2019-06-17 11:56
You can see my `config.log` here:
https://gist.github.com/zerothi/a2a7822417e5c312787d8a9f0012a8dd

if it helps?

**Comment by yosefe** [comment] 2019-06-17 11:57
probably some other OpenMPI component is initializing memory patcher framework, which overrides UCX hooks.. can yous pls try:
`$ mpirun --mca btl self -np 2 ./test   `?

Also, is it possible to provide config.log for OpenMPI?

**Comment by zerothi** [comment] 2019-06-17 12:04
@yosefe same thing :(

```bash
$> mpirun --mca btl self -np 2 ./test                                                                                                                                                                                           
[nicpa-dtu:21644] ../../../../../opal/mca/common/ucx/common_ucx.c:146  Warning: UCX is unable to handle VM_UNMAP event. This may cause performance degradation or data corruption. Pls try adding --mca opal_common_ucx_opal_mem_hooks 1 to mpirun/oshrun command line to resolve this issue.
[nicpa-dtu:21645] ../../../../../opal/mca/common/ucx/common_ucx.c:146  Warning: UCX is unable to handle VM_UNMAP event. This may cause performance degradation or data corruption. Pls try adding --mca opal_common_ucx_opal_mem_hooks 1 to mpirun/oshrun command line to resolve this issue.
```

I have amended the gist with ompi-config.log as well.

**Comment by yosefe** [comment] 2019-06-17 14:25
@zerothi unfortunately, i've tried to reproduce the issue with same versions and configuration on my system, and no luck..
can you pls rebuild UCX with debug like this (--disable-logging replaced by --enable-logging)?
`../configure --enable-optimizations --enable-logging --disable-debug --disable-assertions --disable-params-check --with-rc --with-ud --with-dc --with-dm --with-mcpu --with-march ...`

And then run like this:
`mpirun -x UCX_MEM_LOG_LEVEL=debug -mca btl self -n 2  ./a.out `

This should produce some logging output to help identify the problem

**Comment by zerothi** [comment] 2019-06-17 19:50
I got this:
```bash
[1560801008.017671] [nicpa-dtu:585]          install.c:124  UCX  DEBUG mmap test: got 0x0 out of 0x2007f
[1560801008.017669] [nicpa-dtu:586]          install.c:124  UCX  DEBUG mmap test: got 0x0 out of 0x2007f
[nicpa-dtu:00585] ../../../../../opal/mca/common/ucx/common_ucx.c:146  Warning: UCX is unable to handle VM_UNMAP event. This may cause performance degradation or data corruption. Pls try adding --mca opal_common_ucx_opal_mem_hooks 1 to mpirun/oshrun command line to resolve this issue.
[nicpa-dtu:00586] ../../../../../opal/mca/common/ucx/common_ucx.c:146  Warning: UCX is unable to handle VM_UNMAP event. This may cause performance degradation or data corruption. Pls try adding --mca opal_common_ucx_opal_mem_hooks 1 to mpirun/oshrun command line to resolve this issue.

```

**Comment by zerothi** [comment] 2019-06-17 19:51
Woops, you had way more stuff than I had! ;) Wait a minute!

**Comment by zerothi** [comment] 2019-06-18 08:37
@yosefe If you need anything more, please do not hesitate to contact me :)

**Comment by yosefe** [comment] 2019-06-18 08:39
@zerothi i guess you don't have any IB/RDMA device, or knem driver, right?
seems the issue is bogus warning when memhooks are not installed because rcache was not created. i'm preparing a fix for it and will update when have a PR

**Comment by zerothi** [comment] 2019-06-18 08:58
Correct, I don't have *anything* on my machine. :)
It is because I am doing a "software stack" that I sort of check on my own laptop/stationary, and thus I don't have exactly the same setup with advanced devices. :)

**Comment by zerothi** [comment] 2019-06-18 08:59
My guess is that you could actually run CI tests on travis/azure/... for such a non-use case?

**Comment by yosefe** [comment] 2019-06-18 09:42
@zerothi the warnings should be fixed by #3716

**Comment by yosefe** [comment] 2019-06-20 07:18
@zerothi FYI, ucx [v1.6.0-rc3](https://github.com/openucx/ucx/releases/tag/v1.6.0-rc3) contains a fix for this issue. any chance you can give it a try?

**Comment by zerothi** [comment] 2019-06-20 07:20
I am running installation! Will return! ;) Thanks

**Comment by zerothi** [comment] 2019-06-20 07:47
Now I get:
```bash
$> mpirun -np 2 ./test
<nothing>

$> mpirun -x UCX_MEM_LOG_LEVEL=debug -mca btl self -n 2 ./test
[1561016808.820435] [nicpa-dtu:8984]          install.c:192  UCX  DEBUG mmap test: got 0x0 out of 0x0
[1561016808.820435] [nicpa-dtu:8985]          install.c:192  UCX  DEBUG mmap test: got 0x0 out of 0x0
```

I guess this means it can be closed!

**Closed** 2019-06-20 08:03 UTC
Labels: Bug
