### ISSUE TITLE
[mtt] Transport retry count exceeded RoCE

### ISSUE THREAD

**Issue by amaslenn** [openucx/ucx#3390] opened 2019-03-18 09:11 UTC
Configuration
```
OMPI: 4.0.1rc1
MOFED: MLNX_OFED_LINUX-4.5-1.0.1.0
Module: hpcx-gcc (2019-03-15)
Test module: mtt-tests/hpcx-gcc
Nodes: jazz x3 (ppn=28(x3), nodelist=jazz[03,09,32])
```

MTT log: http://hpcweb.lab.mtl.com/hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20190316_002332_167047_18715_jazz03/html/test_stdout_6QeZYU.txt

Cmd:
`$ mpirun -np 9 -mca btl self --tag-output --timestamp-output -mca pml ucx -mca coll '^hcoll' --bind-to core -x UCX_NET_DEVICES=mlx5_3:1 -mca osc ucx -x UCX_IB_REG_ME
THODS=rcache,direct -x UCX_TLS=dc_x,self,sm -x UCX_DC_MLX5_TX_POLICY=dcs_quota -mca pmix_base_async_modex 1 -mca mpi_add_procs_cutoff 0 -mca pmix_base_collect_data 0
 --map-by node /hpc/local/benchmarks/hpcx_install_2019-03-15/hpcx-gcc-redhat7.4/ompi/tests/osu-micro-benchmarks-5.6/osu_alltoallv`

```sh
Mon Mar 18 06:53:56 2019[1,0]<stdout>:
Mon Mar 18 06:53:56 2019[1,0]<stdout>:# OSU MPI All-to-Allv Personalized Exchange Latency Test v5.6
Mon Mar 18 06:53:56 2019[1,0]<stdout>:# Size       Avg Latency(us)
Mon Mar 18 06:53:56 2019[1,0]<stdout>:1                      12.08
Mon Mar 18 06:53:56 2019[1,0]<stdout>:2                      11.11
Mon Mar 18 06:53:56 2019[1,0]<stdout>:4                      11.11
Mon Mar 18 06:53:56 2019[1,0]<stdout>:8                      11.00
Mon Mar 18 06:53:59 2019[1,0]<stdout>:16                   2111.58
Mon Mar 18 06:53:59 2019[1,0]<stdout>:32                     12.09
Mon Mar 18 06:53:59 2019[1,0]<stdout>:64                     13.30
Mon Mar 18 06:53:59 2019[1,0]<stdout>:128                    13.60
Mon Mar 18 06:53:59 2019[1,0]<stdout>:256                    15.55
Mon Mar 18 06:53:59 2019[1,0]<stdout>:512                    16.64
Mon Mar 18 06:53:59 2019[1,0]<stdout>:1024                   19.44
Mon Mar 18 06:54:16 2019[1,0]<stderr>:[jazz06:64666:0:64666] ib_mlx5_log.c:139  Transport retry count exceeded on mlx5_3:1/RoCE (synd 0x15 vend 0x81 hw_synd 0/0)
Mon Mar 18 06:54:16 2019[1,0]<stderr>:[jazz06:64666:0:64666] ib_mlx5_log.c:139  DCI QP 0x19fed wqe[361]: SEND s-e [rqpn 0x1b20a rmac ec:0d:9a:46:9e:25 sgix 3 dgid ::2.1.3.7 tc 106] [va 0x7
f810bdf9d40 len 2058 lkey 0x13e90b]
Mon Mar 18 06:54:16 2019[1,0]<stderr>:
Mon Mar 18 06:54:16 2019[1,0]<stderr>:/hpc/local/benchmarks/hpcx_install_2019-03-17/src/hpcx-gcc-redhat7.4/ucx-master/src/ucs/debug/assert.c: [ ucs_fatal_error_message() ]
Mon Mar 18 06:54:16 2019[1,0]<stderr>:      ...
Mon Mar 18 06:54:16 2019[1,0]<stderr>:       33     }
Mon Mar 18 06:54:16 2019[1,0]<stderr>:       34
Mon Mar 18 06:54:16 2019[1,0]<stderr>:       35     ucs_handle_error(message_buf);
Mon Mar 18 06:54:16 2019[1,0]<stderr>:==>    36     abort();
Mon Mar 18 06:54:16 2019[1,0]<stderr>:       37 }
Mon Mar 18 06:54:16 2019[1,0]<stderr>:       38
Mon Mar 18 06:54:16 2019[1,0]<stderr>:       39 void ucs_fatal_error_format(const char *file, unsigned line,
Mon Mar 18 06:54:16 2019[1,0]<stderr>:
Mon Mar 18 06:54:16 2019[1,0]<stderr>:==== backtrace ====
Mon Mar 18 06:54:16 2019[1,0]<stderr>: 0 0x00000000000482e8 ucs_fatal_error_message()  /hpc/local/benchmarks/hpcx_install_2019-03-17/src/hpcx-gcc-redhat7.4/ucx-master/src/ucs/debug/assert.
c:36
Mon Mar 18 06:54:16 2019[1,0]<stderr>: 1 0x000000000004b34c ucs_log_default_handler()  /hpc/local/benchmarks/hpcx_install_2019-03-17/src/hpcx-gcc-redhat7.4/ucx-master/src/ucs/debug/log.c:1
40
Mon Mar 18 06:54:16 2019[1,0]<stderr>: 2 0x000000000004b474 ucs_log_dispatch()  /hpc/local/benchmarks/hpcx_install_2019-03-17/src/hpcx-gcc-redhat7.4/ucx-master/src/ucs/debug/log.c:193
Mon Mar 18 06:54:16 2019[1,0]<stderr>: 3 0x000000000001cdb3 uct_ib_mlx5_completion_with_err()  /hpc/local/benchmarks/hpcx_install_2019-03-17/src/hpcx-gcc-redhat7.4/ucx-master/src/uct/ib/ml
x5/ib_mlx5_log.c:132
Mon Mar 18 06:54:16 2019[1,0]<stderr>: 4 0x00000000000387f5 uct_ib_mlx5_poll_cq()  /hpc/local/benchmarks/hpcx_install_2019-03-17/src/hpcx-gcc-redhat7.4/ucx-master/src/uct/ib/mlx5/ib_mlx5.i
nl:38
Mon Mar 18 06:54:16 2019[1,0]<stderr>: 5 0x00000000000190a2 ucs_callbackq_dispatch()  /hpc/local/benchmarks/hpcx_install_2019-03-17/src/hpcx-gcc-redhat7.4/ucx-master/src/ucs/datastruct/cal
lbackq.h:211
Mon Mar 18 06:54:16 2019[1,0]<stderr>: 6 0x0000000000003767 mca_pml_ucx_progress()  /hpc/local/benchmarks/hpcx_install_2019-03-17/src/hpcx-gcc-redhat7.4/ompi/ompi/mca/pml/ucx/pml_ucx.c:510
Mon Mar 18 06:54:16 2019[1,0]<stderr>: 7 0x00000000000370dc opal_progress()  /hpc/local/benchmarks/hpcx_install_2019-03-17/src/hpcx-gcc-redhat7.4/ompi/opal/runtime/opal_progress.c:231
Mon Mar 18 06:54:16 2019[1,0]<stderr>: 8 0x000000000004b945 ompi_request_wait_completion()  /hpc/local/benchmarks/hpcx_install_2019-03-17/src/hpcx-gcc-redhat7.4/ompi/ompi/../ompi/request/r
equest.h:415
Mon Mar 18 06:54:16 2019[1,0]<stderr>: 9 0x0000000000087339 ompi_coll_base_sendrecv_actual()  /hpc/local/benchmarks/hpcx_install_2019-03-17/src/hpcx-gcc-redhat7.4/ompi/ompi/mca/coll/base/c
oll_base_util.c:59
Mon Mar 18 06:54:16 2019[1,0]<stderr>:10 0x000000000008ca63 ompi_coll_base_sendrecv()  /hpc/local/benchmarks/hpcx_install_2019-03-17/src/hpcx-gcc-redhat7.4/ompi/ompi/mca/coll/base/coll_bas
e_util.h:67
Mon Mar 18 06:54:16 2019[1,0]<stderr>:11 0x000000000005f411 PMPI_Alltoallv()  /hpc/local/benchmarks/hpcx_install_2019-03-17/src/hpcx-gcc-redhat7.4/ompi/ompi/mpi/c/profile/palltoallv.c:129
Mon Mar 18 06:54:16 2019[1,0]<stderr>:12 0x0000000000401a1b main()  /hpc/local/benchmarks/hpcx_install_2019-03-15/src/hpcx-gcc-redhat7.4/ompi/mpi_tests/mpitests/osu-micro-benchmarks-5.6/mp
i/collective/osu_alltoallv.c:129
Mon Mar 18 06:54:16 2019[1,0]<stderr>:13 0x0000000000021c05 __libc_start_main()  ???:0
Mon Mar 18 06:54:16 2019[1,0]<stderr>:14 0x0000000000401e11 _start()  ???:0
Mon Mar 18 06:54:16 2019[1,0]<stderr>:===================
```

All devices were active during the testing.

Originally reported here: #3305

**Comment by amaslenn** [comment] 2019-03-19 05:22
Reproduced in `kmi_hash` test.

Configuration
```
OMPI: 4.0.1rc1
MOFED: MLNX_OFED_LINUX-4.5-1.0.1.0
Module: hpcx-gcc (2019-03-17)
Test module: mtt-tests/hpcx-gcc
Nodes: jazz x4 (ppn=28(x4), nodelist=jazz[02,12-14])
```

MTT log: http://hpcweb.lab.mtl.com/hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20190318_115606_75105_18857_jazz02/html/test_stdout_T3rksC.txt

Cmd (min np to reproduce is 8):
`mpirun -np 112 --report-bindings -mca btl self --tag-output --timestamp-output -mca pml ucx -mca coll '^hcoll' --bind-to core -x UCX_NET_DEVICES=mlx5_3:1 -mca osc ucx -x UCX_IB_REG_METHODS=rcache,direct -x UCX_TLS=dc_x,self,sm -x UCX_DC_MLX5_TX_POLICY=dcs_quota -mca pmix_base_async_modex 0 -mca mpi_add_procs_cutoff 100000 -mca pmix_base_collect_data 1 --map-by node /hpc/local/benchmarks/hpcx_install_2019-03-17/mtt-tests-gcc/installs/bhhA/tests/hash/mtt-tests.git/kmi_hash/tests/BENCH_QUERY -n 4000 -m 4000`

Output from manual run:
```sh
Tue Mar 19 07:19:00 2019[1,0]<stdout>:Histogram sort sampling finish, num_pivots = 92, screw ratio=1.098875
Tue Mar 19 07:19:16 2019[1,3]<stderr>:[jazz27:108731:0:108731] ib_mlx5_log.c:139  Transport retry count exceeded on mlx5_3:1/RoCE (synd 0x15 vend 0x81 hw_synd 0/0)
Tue Mar 19 07:19:16 2019[1,3]<stderr>:[jazz27:108731:0:108731] ib_mlx5_log.c:139  DCI QP 0x27837 wqe[8]: SEND s-e [rqpn 0x5b9b rmac ec:0d:9a:46:9e:0d sgix 3 dgid ::2
.1.3.14 tc 106] [va 0x7fb454fdfa00 len 8192 lkey 0x1854e1]                                                                                                           Tue Mar 19 07:19:16 2019[1,7]<stderr>:[jazz27:108732:0:108732] ib_mlx5_log.c:139  Transport retry count exceeded on mlx5_3:1/RoCE (synd 0x15 vend 0x81 hw_synd 0/0)
Tue Mar 19 07:19:16 2019[1,7]<stderr>:[jazz27:108732:0:108732] ib_mlx5_log.c:139  DCI QP 0x2783e wqe[10]: SEND s-e [rqpn 0x7b0f rmac ec:0d:9a:8c:cc:ef sgix 3 dgid ::2.1.3.12 tc 106] [va 0x7fe3b8ff7d00 len 8192 lkey 0x1860ed]
Tue Mar 19 07:19:16 2019[1,7]<stderr>:
Tue Mar 19 07:19:16 2019[1,7]<stderr>:/hpc/local/benchmarks/hpcx_install_2019-03-18/src/hpcx-gcc-redhat7.4/ucx-master/src/ucs/debug/assert.c: [ ucs_fatal_error_message() ]
Tue Mar 19 07:19:16 2019[1,7]<stderr>:      ...
Tue Mar 19 07:19:16 2019[1,7]<stderr>:       33     }
Tue Mar 19 07:19:16 2019[1,7]<stderr>:       34
Tue Mar 19 07:19:16 2019[1,7]<stderr>:       35     ucs_handle_error(message_buf);                                                                                   Tue Mar 19 07:19:16 2019[1,7]<stderr>:==>    36     abort();
Tue Mar 19 07:19:16 2019[1,7]<stderr>:       37 }                                                                                                                    Tue Mar 19 07:19:16 2019[1,7]<stderr>:       38
Tue Mar 19 07:19:16 2019[1,7]<stderr>:       39 void ucs_fatal_error_format(const char *file, unsigned line,                                                         Tue Mar 19 07:19:16 2019[1,7]<stderr>:
Tue Mar 19 07:19:16 2019[1,3]<stderr>:                                                                                                                               Tue Mar 19 07:19:16 2019[1,3]<stderr>:/hpc/local/benchmarks/hpcx_install_2019-03-18/src/hpcx-gcc-redhat7.4/ucx-master/src/ucs/debug/assert.c: [ ucs_fatal_error_messa
ge() ]
Tue Mar 19 07:19:16 2019[1,3]<stderr>:      ...
Tue Mar 19 07:19:16 2019[1,3]<stderr>:       33     }
Tue Mar 19 07:19:16 2019[1,3]<stderr>:       34
Tue Mar 19 07:19:16 2019[1,3]<stderr>:       35     ucs_handle_error(message_buf);
Tue Mar 19 07:19:16 2019[1,3]<stderr>:==>    36     abort();
Tue Mar 19 07:19:16 2019[1,3]<stderr>:       37 }
Tue Mar 19 07:19:16 2019[1,3]<stderr>:       38
Tue Mar 19 07:19:16 2019[1,3]<stderr>:       39 void ucs_fatal_error_format(const char *file, unsigned line,
Tue Mar 19 07:19:16 2019[1,3]<stderr>:
Tue Mar 19 07:19:16 2019[1,3]<stderr>:==== backtrace (tid: 108731) ====
Tue Mar 19 07:19:16 2019[1,3]<stderr>: 0 0x0000000000048298 ucs_fatal_error_message()  /hpc/local/benchmarks/hpcx_install_2019-03-18/src/hpcx-gcc-redhat7.4/ucx-maste
r/src/ucs/debug/assert.c:36
Tue Mar 19 07:19:16 2019[1,3]<stderr>: 1 0x000000000004b2cc ucs_log_default_handler()  /hpc/local/benchmarks/hpcx_install_2019-03-18/src/hpcx-gcc-redhat7.4/ucx-maste
r/src/ucs/debug/log.c:140
Tue Mar 19 07:19:16 2019[1,3]<stderr>: 2 0x000000000004b3f4 ucs_log_dispatch()  /hpc/local/benchmarks/hpcx_install_2019-03-18/src/hpcx-gcc-redhat7.4/ucx-master/src/u
cs/debug/log.c:193
Tue Mar 19 07:19:16 2019[1,3]<stderr>: 3 0x000000000001cdb3 uct_ib_mlx5_completion_with_err()  /hpc/local/benchmarks/hpcx_install_2019-03-18/src/hpcx-gcc-redhat7.4/u
cx-master/src/uct/ib/mlx5/ib_mlx5_log.c:132
Tue Mar 19 07:19:16 2019[1,3]<stderr>: 4 0x00000000000387f5 uct_ib_mlx5_poll_cq()  /hpc/local/benchmarks/hpcx_install_2019-03-18/src/hpcx-gcc-redhat7.4/ucx-master/sr
c/uct/ib/mlx5/ib_mlx5.inl:38
Tue Mar 19 07:19:16 2019[1,3]<stderr>: 5 0x00000000000190a2 ucs_callbackq_dispatch()  /hpc/local/benchmarks/hpcx_install_2019-03-18/src/hpcx-gcc-redhat7.4/ucx-master
/src/ucs/datastruct/callbackq.h:211
Tue Mar 19 07:19:16 2019[1,3]<stderr>: 6 0x0000000000003767 mca_pml_ucx_progress()  /hpc/local/benchmarks/hpcx_install_2019-03-18/src/hpcx-gcc-redhat7.4/ompi/ompi/mc
a/pml/ucx/pml_ucx.c:510
Tue Mar 19 07:19:16 2019[1,3]<stderr>: 7 0x00000000000370dc opal_progress()  /hpc/local/benchmarks/hpcx_install_2019-03-18/src/hpcx-gcc-redhat7.4/ompi/opal/runtime/o
pal_progress.c:231
Tue Mar 19 07:19:16 2019[1,3]<stderr>: 8 0x000000000004b945 ompi_request_wait_completion()  /hpc/local/benchmarks/hpcx_install_2019-03-18/src/hpcx-gcc-redhat7.4/ompi
/ompi/../ompi/request/request.h:415
Tue Mar 19 07:19:16 2019[1,3]<stderr>: 9 0x000000000008fd54 ompi_coll_base_sendrecv_zero()  /hpc/local/benchmarks/hpcx_install_2019-03-18/src/hpcx-gcc-redhat7.4/ompi
/ompi/mca/coll/base/coll_base_barrier.c:64
Tue Mar 19 07:19:16 2019[1,3]<stderr>:10 0x000000000005fa38 PMPI_Barrier()  /hpc/local/benchmarks/hpcx_install_2019-03-18/src/hpcx-gcc-redhat7.4/ompi/ompi/mpi/c/prof
ile/pbarrier.c:74
Tue Mar 19 07:19:16 2019[1,3]<stderr>:11 0x0000000000406506 KMI_table_commit_fixed_length()  /hpc/local/benchmarks/hpcx_install_2019-03-17/mtt-tests-gcc/installs/bhh
A/tests/hash/mtt-tests.git/kmi_hash/src/table.c:892
Tue Mar 19 07:19:16 2019[1,3]<stderr>:12 0x0000000000406e85 KMI_table_commit()  /hpc/local/benchmarks/hpcx_install_2019-03-17/mtt-tests-gcc/installs/bhhA/tests/hash/
mtt-tests.git/kmi_hash/src/table.c:1271
Tue Mar 19 07:19:16 2019[1,3]<stderr>:13 0x0000000000401433 main()  ???:0
Tue Mar 19 07:19:16 2019[1,3]<stderr>:14 0x0000000000021c05 __libc_start_main()  ???:0
Tue Mar 19 07:19:16 2019[1,3]<stderr>:15 0x00000000004015d1 _start()  ???:0
Tue Mar 19 07:19:16 2019[1,3]<stderr>:=================================
```

**Comment by brminich** [comment] 2019-08-08 14:30
duplicate of #3305

**Comment by brminich** [comment] 2019-08-08 14:31
https://redmine.mellanox.com/issues/1706553
(MLNX internal link)

**Comment by brminich** [comment] 2019-08-09 10:50
closing it as duplicate of #3305

**Closed by brminich** 2019-08-09 10:50 UTC
Labels: Bug, Duplicate, MTT
