### ISSUE TITLE
Non-thread safe code in UGNI

### ISSUE THREAD

**Issue by MattBBaker** [openucx/ucx#327] opened 2015-07-28 15:19 UTC
The get_cookie() function in in UGNI uses the non-thread safe getenv() function. This should be replaced with a thread safe alternative.

**Comment by shamisp** [comment] 2015-07-28 15:43
I don't think there is a thread safe alternative https://sourceware.org/bugzilla/show_bug.cgi?id=5069

**Comment by shamisp** [comment] 2015-07-28 15:53
@miked-mellanox  @MattBBaker : In our case, we know that the process was bootstrapped by PMI and we don't have any other thread that can change it…. I think we can put a comment in the code but overall I don't expect us to run in scenario where we have UCX threads changing the variable. I would say we can ignore it for now. I don't see any alternative.

**Comment by yosefe** [comment] 2015-07-28 22:35
the problem is that it will segfault if any variable is changed/added in another thread in the same time

**Comment by shamisp** [comment] 2015-07-28 22:54
The variable set once by the runtime environment (alps). Once we get to the UCX init we know for sure that it is set and constant. So we should be safe there

**Comment by shamisp** [comment] 2015-07-31 21:49
I close this for now. I don't think this is an issue for our case.

**Closed by shamisp** 2015-07-31 21:49 UTC
