### ISSUE TITLE
hang in dc_mlx5/uct_p2p_mix_test.mix_10000/0 on hpc-test-node-upstream,1

### ISSUE THREAD

**Issue by brminich** [openucx/ucx#3007] opened 2018-11-01 06:20 UTC
```
16:57:11 [----------] 1 test from dc_mlx5/uct_amo_fand_for_test
16:57:11 [ RUN      ] dc_mlx5/uct_amo_fand_for_test.fand32/0
16:57:11 [     SKIP ] (unsupported)
16:57:11 [       OK ] dc_mlx5/uct_amo_fand_for_test.fand32/0 (140 ms)
16:57:11 [----------] 1 test from dc_mlx5/uct_amo_fand_for_test (140 ms total)
16:57:11 
16:57:11 [----------] 1 test from dc_mlx5/uct_p2p_mix_test
16:57:11 [ RUN      ] dc_mlx5/uct_p2p_mix_test.mix_10000/0
19:36:59 
make: *** [test] Terminated
19:37:00 
Build step 'Execute shell' marked build as failure
19:37:00 TAP Reports Processing: START
19:37:00 Looking for TAP results report in workspace using pattern: **/*.tap
```

**Comment by yosefe** [comment] 2018-11-20 09:37
probably duplicate of #2934

**Comment by alinask** [comment] 2019-05-06 07:38
Failure on the same test, on a different transport:

```
10:43:10 [----------] 1 test from rc_mlx5/uct_p2p_mix_test
10:43:10 [ RUN      ] rc_mlx5/uct_p2p_mix_test.mix_10000/0
10:58:10 /scrap/jenkins/workspace/gh-ucx-pr/label/ARM_test_node/worker/3/contrib/../test/gtest/common/test_helpers.cc:42: Failure
10:58:10 Failed
10:58:10 Connection timed out - abort testing
10:58:10 [juno003:18197:0:18197] Caught signal 6 (Aborted: tkill(2) or tgkill(2))
10:58:12 
10:58:12 /scrap/jenkins/workspace/gh-ucx-pr/label/ARM_test_node/worker/3/contrib/../src/uct/ib/mlx5/ib_mlx5.inl: [ uct_ib_mlx5_get_cqe() ]
10:58:12       ...
10:58:12        10 uct_ib_mlx5_get_cqe(uct_ib_mlx5_cq_t *cq,  unsigned index)
10:58:12        11 {
10:58:12        12     return cq->cq_buf + ((index & (cq->cq_length - 1)) << cq->cqe_size_log);
10:58:12 ==>    13 }
10:58:12        14 
10:58:12        15 static UCS_F_ALWAYS_INLINE int
10:58:12        16 uct_ib_mlx5_cqe_is_hw_owned(uint8_t op_own, unsigned index, unsigned mask)
10:58:12 
10:58:14 ==== backtrace (tid:  18197) ====
10:58:14  0 0x000000000003ce68 uct_ib_mlx5_get_cqe()  /scrap/jenkins/workspace/gh-ucx-pr/label/ARM_test_node/worker/3/contrib/../src/uct/ib/mlx5/ib_mlx5.inl:13
10:58:14  1 0x000000000003ce68 uct_rc_mlx5_iface_poll_rx_cq()  /scrap/jenkins/workspace/gh-ucx-pr/label/ARM_test_node/worker/3/contrib/../src/uct/ib/rc/accel/rc_mlx5.inl:126
10:58:14  2 0x000000000003ce68 uct_rc_mlx5_iface_common_poll_rx()  /scrap/jenkins/workspace/gh-ucx-pr/label/ARM_test_node/worker/3/contrib/../src/uct/ib/rc/accel/rc_mlx5.inl:1049
10:58:14  3 0x000000000003ce68 uct_rc_mlx5_iface_progress()  /scrap/jenkins/workspace/gh-ucx-pr/label/ARM_test_node/worker/3/contrib/../src/uct/ib/rc/accel/rc_mlx5_iface.c:120
10:58:14  4 0x000000000062cc30 uct_test::progress()  /scrap/jenkins/workspace/gh-ucx-pr/label/ARM_test_node/worker/3/contrib/../src/ucs/datastruct/callbackq.h:211
10:58:14  5 0x000000000062cc30 uct_worker_progress()  /scrap/jenkins/workspace/gh-ucx-pr/label/ARM_test_node/worker/3/contrib/../src/uct/api/uct.h:1926
10:58:14  6 0x000000000062cc30 uct_test::entity::progress()  /scrap/jenkins/workspace/gh-ucx-pr/label/ARM_test_node/worker/3/contrib/../test/gtest/uct/uct_test.cc:657
10:58:14  7 0x000000000062cc30 uct_test::progress()  /scrap/jenkins/workspace/gh-ucx-pr/label/ARM_test_node/worker/3/contrib/../test/gtest/uct/uct_test.cc:418
10:58:14  8 0x00000000005f9024 uct_p2p_mix_test::random_op()  /scrap/jenkins/workspace/gh-ucx-pr/label/ARM_test_node/worker/3/contrib/../test/gtest/uct/test_p2p_mix.cc:132
10:58:14  9 0x00000000005fa3e0 uct_p2p_mix_test::run()  /scrap/jenkins/workspace/gh-ucx-pr/label/ARM_test_node/worker/3/contrib/../test/gtest/uct/test_p2p_mix.cc:156
10:58:14 10 0x000000000055cfec ucs::test_base::run()  /scrap/jenkins/workspace/gh-ucx-pr/label/ARM_test_node/worker/3/contrib/../test/gtest/common/test.cc:276
10:58:14 11 0x000000000055cfec ucs::test_base::TestBodyProxy()  /scrap/jenkins/workspace/gh-ucx-pr/label/ARM_test_node/worker/3/contrib/../test/gtest/common/test.cc:302
10:58:14 12 0x000000000054a934 testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>()  /scrap/jenkins/workspace/gh-ucx-pr/label/ARM_test_node/worker/3/contrib/../test/gtest/common/gtest-all.cc:3562
10:58:14 13 0x000000000054a934 testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>()  /scrap/jenkins/workspace/gh-ucx-pr/label/ARM_test_node/worker/3/contrib/../test/gtest/common/gtest-all.cc:3598
10:58:14 14 0x000000000053f0ec testing::Test::Run()  /scrap/jenkins/workspace/gh-ucx-pr/label/ARM_test_node/worker/3/contrib/../test/gtest/common/gtest-all.cc:3635
10:58:14 15 0x000000000053f1bc testing::TestInfo::Run()  /scrap/jenkins/workspace/gh-ucx-pr/label/ARM_test_node/worker/3/contrib/../test/gtest/common/gtest-all.cc:3812
10:58:14 16 0x000000000053f32c testing::TestCase::Run()  /scrap/jenkins/workspace/gh-ucx-pr/label/ARM_test_node/worker/3/contrib/../test/gtest/common/gtest-all.cc:3930
10:58:14 17 0x000000000054373c testing::internal::UnitTestImpl::RunAllTests()  /scrap/jenkins/workspace/gh-ucx-pr/label/ARM_test_node/worker/3/contrib/../test/gtest/common/gtest-all.cc:5802
10:58:14 18 0x0000000000543a58 testing::internal::UnitTestImpl::RunAllTests()  /scrap/jenkins/workspace/gh-ucx-pr/label/ARM_test_node/worker/3/contrib/../test/gtest/common/gtest-all.cc:5719
10:58:14 19 0x0000000000543a58 HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>()  /scrap/jenkins/workspace/gh-ucx-pr/label/ARM_test_node/worker/3/contrib/../test/gtest/common/gtest-all.cc:3618
10:58:14 20 0x0000000000543a58 testing::UnitTest::Run()  /scrap/jenkins/workspace/gh-ucx-pr/label/ARM_test_node/worker/3/contrib/../test/gtest/common/gtest-all.cc:5416
10:58:14 21 0x00000000004ee160 main()  /scrap/jenkins/workspace/gh-ucx-pr/label/ARM_test_node/worker/3/contrib/../test/gtest/common/gtest.h:20059
10:58:14 22 0x0000000000020c94 __libc_start_main()  :0
10:58:14 23 0x0000000000529a64 _start()  :0
10:58:14 =================================
```

http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/7247/label=ARM_test_node,worker=3/console

on ARM_test_node

**Comment by dmitrygladkov** [comment] 2019-06-05 07:58
```
08:49:51 [ RUN      ] rc_mlx5/uct_p2p_mix_test_alloc_methods.mix1000_odp/1
09:04:51 /scrap/jenkins/workspace/hpc-ucx-pr-2/label/hpc-test-node3/worker/0/contrib/../test/gtest/common/test_helpers.cc:46: Failure
09:04:51 Failed
09:04:51 Connection timed out - abort testing
09:04:51 [hpc-test-node3:39271:0:39271] Caught signal 6 (Aborted: tkill(2) or tgkill(2))
09:04:52 
09:04:52 /scrap/jenkins/workspace/hpc-ucx-pr-2/label/hpc-test-node3/worker/0/contrib/../src/uct/ib/rc/accel/rc_mlx5.inl: [ uct_rc_mlx5_iface_common_poll_rx() ]
09:04:52       ...
09:04:52      1043 #endif
09:04:52      1044 
09:04:52      1045     ucs_assert(uct_ib_mlx5_srq_get_wqe(&iface->rx.srq,
09:04:52 ==>  1046                                        iface->rx.srq.mask)->srq.next_wqe_index == 0);
09:04:52      1047 
09:04:52      1048     cqe = uct_rc_mlx5_iface_poll_rx_cq(iface);
09:04:52      1049     if (cqe == NULL) {
09:04:52 
09:04:52 ==== backtrace (tid:  39271) ====
09:04:52  0 0x000000000003deee uct_rc_mlx5_iface_common_poll_rx()  /scrap/jenkins/workspace/hpc-ucx-pr-2/label/hpc-test-node3/worker/0/contrib/../src/uct/ib/rc/accel/rc_mlx5.inl:1046
09:04:52  1 0x000000000062bbda uct_test::progress()  /scrap/jenkins/workspace/hpc-ucx-pr-2/label/hpc-test-node3/worker/0/contrib/../src/ucs/datastruct/callbackq.h:211
09:04:52  2 0x00000000005f8b78 uct_p2p_mix_test::random_op()  /scrap/jenkins/workspace/hpc-ucx-pr-2/label/hpc-test-node3/worker/0/contrib/../test/gtest/uct/test_p2p_mix.cc:132
09:04:52  3 0x00000000005fa130 uct_p2p_mix_test::run()  /scrap/jenkins/workspace/hpc-ucx-pr-2/label/hpc-test-node3/worker/0/contrib/../test/gtest/uct/test_p2p_mix.cc:156
09:04:52  4 0x000000000055eef6 ucs::test_base::run()  /scrap/jenkins/workspace/hpc-ucx-pr-2/label/hpc-test-node3/worker/0/contrib/../test/gtest/common/test.cc:276
09:04:52  5 0x0000000000549a33 testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>()  /scrap/jenkins/workspace/hpc-ucx-pr-2/label/hpc-test-node3/worker/0/contrib/../test/gtest/common/gtest-all.cc:3562
09:04:52  6 0x000000000053dead testing::Test::Run()  /scrap/jenkins/workspace/hpc-ucx-pr-2/label/hpc-test-node3/worker/0/contrib/../test/gtest/common/gtest-all.cc:3635
09:04:52  7 0x000000000053df7c testing::TestInfo::Run()  /scrap/jenkins/workspace/hpc-ucx-pr-2/label/hpc-test-node3/worker/0/contrib/../test/gtest/common/gtest-all.cc:3812
09:04:52  8 0x000000000053e0df testing::TestCase::Run()  /scrap/jenkins/workspace/hpc-ucx-pr-2/label/hpc-test-node3/worker/0/contrib/../test/gtest/common/gtest-all.cc:3930
09:04:52  9 0x0000000000542a77 testing::internal::UnitTestImpl::RunAllTests()  /scrap/jenkins/workspace/hpc-ucx-pr-2/label/hpc-test-node3/worker/0/contrib/../test/gtest/common/gtest-all.cc:5802
09:04:52 10 0x0000000000542d7b testing::internal::UnitTestImpl::RunAllTests()  /scrap/jenkins/workspace/hpc-ucx-pr-2/label/hpc-test-node3/worker/0/contrib/../test/gtest/common/gtest-all.cc:5719
09:04:52 11 0x00000000004ea2b3 main()  /scrap/jenkins/workspace/hpc-ucx-pr-2/label/hpc-test-node3/worker/0/contrib/../test/gtest/common/gtest.h:20059
09:04:52 12 0x0000000000021c05 __libc_start_main()  ???:0
09:04:52 13 0x0000000000528637 _start()  ???:0
09:04:52 =================================
```
http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/label=hpc-test-node3,worker=0/10498/console

**Comment by yosefe** [comment] 2019-08-11 07:40
duplicate of #2934

**Closed by yosefe** 2019-08-11 07:40 UTC
Labels: Bug, Jenkins
