### ISSUE TITLE
[mtt] ERROR failed to unpack address, resource[0] is not valid

### ISSUE THREAD

**Issue by amaslenn** [openucx/ucx#5103] opened 2020-04-29 10:48 UTC
Configuration
```
OMPI: 4.0.3rc4
MOFED: MLNX_OFED_LINUX-5.0-1.0.0.0
Module: hpcx-gcc (2020-04-27)
Test module: none
Nodes: jazz x2 (ppn=28(x2), nodelist=jazz[03-04])
```

MTT log: http://hpcweb.lab.mtl.com/hpc/mtr_scrap/users/mtt/scratch/shmem/20200427_063030_129021_26624_jazz03.swx.labs.mlnx/html/test_stdout_WRljRK.txt

Need to run in a loop to reproduce (up to 7 iterations or even more).

Cmd:
`oshrun -np 32 --display-map --bind-to core -mca oshmem_proc_group_cache_size 10000 -mca sshmem ucx -mca atomic ucx -mca coll_hcoll_enable 1 -x HCOLL_POLLING_LEVEL=1 -x HCOLL_ENABLE_MCAST_ALL=0 -x HCOLL_BCOL=basesmuma,ucx_p2p -x HCOLL_SBGP=basesmsocket,p2p -mca spml ucx -mca pml ucx -x UCX_HANDLE_ERRORS=bt -x UCX_TLS=rc_x,self,sm -x UCX_NET_DEVICES=mlx5_2:1 -x UCX_UNIFIED_MODE=y --map-by node -x SHMEM_SYMMETRIC_HEAP_SIZE=128M /hpc/mtr_scrap/users/mtt/scratch/shmem/20200427_063030_129021_26624_jazz03.swx.labs.mlnx/installs/HyrN/tests/gups-shmem/mtt-tests.git/gups-shmem/gups`

Output:
```sh
=============================================================[1587959490.755358] [jazz03:139712:0]        address.c:449  UCX  ERROR failed to unpack address, resource[0] is not valid
[1587959490.755406] [jazz03:139712:0]         wireup.c:652  UCX  ERROR failed to unpack address: Invalid parameter
[1587959490.755329] [jazz03:139711:0]        address.c:449  UCX  ERROR failed to unpack address, resource[0] is not valid
[1587959490.755376] [jazz03:139711:0]         wireup.c:652  UCX  ERROR failed to unpack address: Invalid parameter[1587959490.755303] [jazz03:139721:0]        address.c:449  UCX  ERROR failed to unpack address, resource[0] is not valid
[1587959490.755359] [jazz03:139721:0]         wireup.c:652  UCX  ERROR failed to unpack address: Invalid parameter
node=jazz03, pid=139726:
```

**Comment by yosefe** [comment] 2020-05-01 11:53
duplicate of #5063, probably related to old xpmem

**Comment by yosefe** [comment] 2020-05-17 08:54
fixed by updating to latest xpmem, @amaslenn pls reopen if you see it again

**Closed** 2020-05-24 18:24 UTC
Labels: Bug, External, MTT
