### ISSUE TITLE
hang in shm/test_ucp_rma.nonblocking_stream_put_nbi_flush_ep/0

### ISSUE THREAD

**Issue by alinask** [openucx/ucx#1948] opened 2017-10-26 10:29 UTC
```
10:23:32 [ RUN      ] shm/test_ucp_rma.nonblocking_stream_put_nbi_flush_ep/0
12:41:37 Build timed out (after 150 minutes). Marking the build as failed.
12:41:37 Build was aborted
```

http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/4930/label=hpc-test-node2,worker=0/console

**Comment by yosefe** [comment] 2017-10-26 11:58
duplicate of #1641

**Closed** 2017-10-26 11:58 UTC
Labels: bug, duplicate, jenkins
