### ISSUE TITLE
GTEST: test_ucp_tag_match_rndv fails on DPU

### ISSUE THREAD

**Issue by evgeny-leksikov** [openucx/ucx#9680] opened 2024-02-09 09:14 UTC
https://dev.azure.com/ucfconsort/0b36e3f0-8ab9-4a48-b68b-4b2350e02c88/_apis/build/builds/76320/logs/369
```
[ RUN      ] dcx/test_ucp_tag_match_rndv.exp_huge_mix/1 <dc_x/auto,proto_v1>
/scrap/azure/agent-03/AZP_WORKSPACE/1/s/contrib/../test/gtest/ucp/test_ucp_tag_match.cc:883: Failure
Expected equality of these values:
  sendbuf.size()
    Which is: 2064126976
  my_recv_req->info.length
    Which is: 8000
/scrap/azure/agent-03/AZP_WORKSPACE/1/s/contrib/../test/gtest/ucp/test_ucp_tag_match.cc:886: Failure
Expected equality of these values:
  sendbuf
    Which is: { 'q' (113, 0x71), '\xCC' (204), '\xB8' (184), '\x17' (23), '\0', '\0', '\0', '\0', '{' (123, 0x7B), '\xFC' (252), '7' (55, 0x37), '\xED' (237), '\0', '\0', '\0', '\0', '\xDF' (223), '\xDC' (220), '/' (47, 0x2F), 'D' (68, 0x44), '\t' (9), '\0', '\0', '\0', '\xC7' (199), '\xA0' (160), '\xDE' (222), '\xA9' (169), '\\' (92, 0x5C), '\0', '\0', '\0', ... }
  recvbuf
    Which is: { 'q' (113, 0x71), '\xCC' (204), '\xB8' (184), '\x17' (23), '\0', '\0', '\0', '\0', '{' (123, 0x7B), '\xFC' (252), '7' (55, 0x37), '\xED' (237), '\0', '\0', '\0', '\0', '\xDF' (223), '\xDC' (220), '/' (47, 0x2F), 'D' (68, 0x44), '\t' (9), '\0', '\0', '\0', '\xC7' (199), '\xA0' (160), '\xDE' (222), '\xA9' (169), '\\' (92, 0x5C), '\0', '\0', '\0', ... }
/scrap/azure/agent-03/AZP_WORKSPACE/1/s/contrib/../test/gtest/common/test_helpers.cc:55: Failure
Failed
Connection timed out - abort testing
[swx-rain02-bf1:4055842:0:4055842] Caught signal 6 (Aborted: tkill(2) or tgkill(2))
==== backtrace (tid:4055842) ====
 0  /scrap/azure/agent-03/AZP_WORKSPACE/1/s/build-test/src/ucs/.libs/libucs.so.0(ucs_handle_error+0x2cc) [0xffff8fa37bac]
 1  /scrap/azure/agent-03/AZP_WORKSPACE/1/s/build-test/src/ucs/.libs/libucs.so.0(+0x37d5c) [0xffff8fa37d5c]
 2  /scrap/azure/agent-03/AZP_WORKSPACE/1/s/build-test/src/ucs/.libs/libucs.so.0(+0x37fe4) [0xffff8fa37fe4]
 3  linux-vdso.so.1(__kernel_rt_sigreturn+0) [0xffff8fae77dc]
 4  /lib/aarch64-linux-gnu/libc.so.6(__sched_yield+0xc) [0xffff8f27eccc]
 5  /scrap/azure/agent-03/AZP_WORKSPACE/1/s/build-test/test/gtest/gtest(+0x960a74) [0xaaaab3ce0a74]
 6  /scrap/azure/agent-03/AZP_WORKSPACE/1/s/build-test/test/gtest/gtest(+0x80222c) [0xaaaab3b8222c]
 7  /scrap/azure/agent-03/AZP_WORKSPACE/1/s/build-test/test/gtest/gtest(+0x8033f8) [0xaaaab3b833f8]
 8  /scrap/azure/agent-03/AZP_WORKSPACE/1/s/build-test/test/gtest/gtest(+0x750f38) [0xaaaab3ad0f38]
 9  /scrap/azure/agent-03/AZP_WORKSPACE/1/s/build-test/test/gtest/gtest(+0x3e9e4c) [0xaaaab3769e4c]
10  /scrap/azure/agent-03/AZP_WORKSPACE/1/s/build-test/test/gtest/gtest(+0x3eb6f8) [0xaaaab376b6f8]
11  /scrap/azure/agent-03/AZP_WORKSPACE/1/s/build-test/test/gtest/gtest(+0xc378ac) [0xaaaab3fb78ac]
12  /scrap/azure/agent-03/AZP_WORKSPACE/1/s/build-test/test/gtest/gtest(+0xc2dcec) [0xaaaab3fadcec]
13  /scrap/azure/agent-03/AZP_WORKSPACE/1/s/build-test/test/gtest/gtest(+0xc2de44) [0xaaaab3fade44]
14  /scrap/azure/agent-03/AZP_WORKSPACE/1/s/build-test/test/gtest/gtest(+0xc2df28) [0xaaaab3fadf28]
15  /scrap/azure/agent-03/AZP_WORKSPACE/1/s/build-test/test/gtest/gtest(+0xc2e4b4) [0xaaaab3fae4b4]
16  /scrap/azure/agent-03/AZP_WORKSPACE/1/s/build-test/test/gtest/gtest(+0xc2e738) [0xaaaab3fae738]
17  /scrap/azure/agent-03/AZP_WORKSPACE/1/s/build-test/test/gtest/gtest(+0x344b68) [0xaaaab36c4b68]
18  /lib/aarch64-linux-gnu/libc.so.6(+0x273fc) [0xffff8f1d73fc]
19  /lib/aarch64-linux-gnu/libc.so.6(__libc_start_main+0x98) [0xffff8f1d74cc]
20  /scrap/azure/agent-03/AZP_WORKSPACE/1/s/build-test/test/gtest/gtest(+0x3d2b70) [0xaaaab3752b70]
=================================
make: *** [Makefile:3988: test] Aborted (core dumped)
make: Leaving directory '/scrap/azure/agent-03/AZP_WORKSPACE/1/s/build-test/test/gtest'

```

https://dev.azure.com/ucfconsort/0b36e3f0-8ab9-4a48-b68b-4b2350e02c88/_apis/build/builds/76320/logs/282
```
[ RUN      ] dcx/test_ucp_tag_match_rndv.exp_huge_mix/7 <dc_x/rndv_get_zcopy,proto_v1,many_lanes>
/scrap/azure/agent-03/AZP_WORKSPACE/1/s/contrib/../test/gtest/ucp/test_ucp_tag_match.cc:883: Failure
Expected equality of these values:
  sendbuf.size()
    Which is: 2064126976
  my_recv_req->info.length
    Which is: 8000
/scrap/azure/agent-03/AZP_WORKSPACE/1/s/contrib/../test/gtest/ucp/test_ucp_tag_match.cc:886: Failure
Expected equality of these values:
  sendbuf
    Which is: { '\xC1' (193), '\xAE' (174), 's' (115, 0x73), 'n' (110, 0x6E), '\0', '\0', '\0', '\0', '\x9B' (155), '\xD3' (211), '\x84' (132), 'P' (80, 0x50), '\x4' (4), '\0', '\0', '\0', '\x1F' (31), 'D' (68, 0x44), '0' (48, 0x30), '%' (37, 0x25), '+' (43, 0x2B), '\0', '\0', '\0', 'G' (71, 0x47), '\xA9' (169), '\xE2' (226), 's' (115, 0x73), '\xAF' (175), '\x1' (1), '\0', '\0', ... }
  recvbuf
    Which is: { '\xC1' (193), '\xAE' (174), 's' (115, 0x73), 'n' (110, 0x6E), '\0', '\0', '\0', '\0', '\x9B' (155), '\xD3' (211), '\x84' (132), 'P' (80, 0x50), '\x4' (4), '\0', '\0', '\0', '\x1F' (31), 'D' (68, 0x44), '0' (48, 0x30), '%' (37, 0x25), '+' (43, 0x2B), '\0', '\0', '\0', 'G' (71, 0x47), '\xA9' (169), '\xE2' (226), 's' (115, 0x73), '\xAF' (175), '\x1' (1), '\0', '\0', ... }
/scrap/azure/agent-03/AZP_WORKSPACE/1/s/contrib/../test/gtest/common/test_helpers.cc:55: Failure
Failed
Connection timed out - abort testing
[swx-rain02-bf1:3915257:0:3915257] Caught signal 6 (Aborted: tkill(2) or tgkill(2))
==== backtrace (tid:3915257) ====
 0  /scrap/azure/agent-03/AZP_WORKSPACE/1/s/build-test/src/ucs/.libs/libucs.so.0(ucs_handle_error+0x2cc) [0xffff84e17bac]
 1  /scrap/azure/agent-03/AZP_WORKSPACE/1/s/build-test/src/ucs/.libs/libucs.so.0(+0x37d5c) [0xffff84e17d5c]
 2  /scrap/azure/agent-03/AZP_WORKSPACE/1/s/build-test/src/ucs/.libs/libucs.so.0(+0x37fe4) [0xffff84e17fe4]
 3  linux-vdso.so.1(__kernel_rt_sigreturn+0) [0xffff84ec17dc]
 4  /lib/aarch64-linux-gnu/libc.so.6(__sched_yield+0xc) [0xffff8465eccc]
 5  /scrap/azure/agent-03/AZP_WORKSPACE/1/s/build-test/test/gtest/gtest(+0x960a74) [0xaaaae2ef0a74]
 6  /scrap/azure/agent-03/AZP_WORKSPACE/1/s/build-test/test/gtest/gtest(+0x80222c) [0xaaaae2d9222c]
 7  /scrap/azure/agent-03/AZP_WORKSPACE/1/s/build-test/test/gtest/gtest(+0x8033f8) [0xaaaae2d933f8]
 8  /scrap/azure/agent-03/AZP_WORKSPACE/1/s/build-test/test/gtest/gtest(+0x750f38) [0xaaaae2ce0f38]
 9  /scrap/azure/agent-03/AZP_WORKSPACE/1/s/build-test/test/gtest/gtest(+0x3e9e4c) [0xaaaae2979e4c]
10  /scrap/azure/agent-03/AZP_WORKSPACE/1/s/build-test/test/gtest/gtest(+0x3eb6f8) [0xaaaae297b6f8]
11  /scrap/azure/agent-03/AZP_WORKSPACE/1/s/build-test/test/gtest/gtest(+0xc378ac) [0xaaaae31c78ac]
12  /scrap/azure/agent-03/AZP_WORKSPACE/1/s/build-test/test/gtest/gtest(+0xc2dcec) [0xaaaae31bdcec]
13  /scrap/azure/agent-03/AZP_WORKSPACE/1/s/build-test/test/gtest/gtest(+0xc2de44) [0xaaaae31bde44]
14  /scrap/azure/agent-03/AZP_WORKSPACE/1/s/build-test/test/gtest/gtest(+0xc2df28) [0xaaaae31bdf28]
15  /scrap/azure/agent-03/AZP_WORKSPACE/1/s/build-test/test/gtest/gtest(+0xc2e4b4) [0xaaaae31be4b4]
16  /scrap/azure/agent-03/AZP_WORKSPACE/1/s/build-test/test/gtest/gtest(+0xc2e738) [0xaaaae31be738]
17  /scrap/azure/agent-03/AZP_WORKSPACE/1/s/build-test/test/gtest/gtest(+0x344b68) [0xaaaae28d4b68]
18  /lib/aarch64-linux-gnu/libc.so.6(+0x273fc) [0xffff845b73fc]
19  /lib/aarch64-linux-gnu/libc.so.6(__libc_start_main+0x98) [0xffff845b74cc]
20  /scrap/azure/agent-03/AZP_WORKSPACE/1/s/build-test/test/gtest/gtest(+0x3d2b70) [0xaaaae2962b70]
=================================
```

**Comment by tvegas1** [comment] 2024-02-19 16:27
I was reproducing that issue last week but it is not visible anymore post-reboot of the machine, shall we close it?

**Comment by yosefe** [comment] 2024-02-19 16:38
it happened because of driver/fw issue and was fixed by rebooting the DPU

**Closed by yosefe** 2024-02-19 16:38 UTC
