### ISSUE TITLE
Go bindings don't build

### ISSUE THREAD

**Issue by waarmond** [openucx/ucx#9734] opened 2024-03-08 16:17 UTC
### Describe the bug
After successfully compiling C sources from current git the Go bindings fail:
```
go build
# ucx
./request.go:32:10: cannot define new methods on non-local type *C.ucp_request_param_t
# ucx
../../ucx/request.go:32:10: cannot define new methods on non-local type *C.ucp_request_param_t
```

### Steps to Reproduce
```
  ./autogen.sh
  ./configure 
  # prevent excessive overlinking due to libtool
  sed -i -e 's/ -shared / -Wl,-O1,--as-needed\0/g' libtool
  make V=1
```

### Setup and versions
- Linux main 6.8.0-rc7 / ArchLinux

### Additional information (depending on the issue)
I would prefer to completely disable the Go bindings.

**Comment by yosefe** [comment] 2024-03-10 17:28
@waarmond can you pls post the full command line and output of the build failure, and config.log?
in order to disable go bindings, can add `--without-go` to `./configure` command

**Comment by rakhmets** [comment] 2024-03-11 08:43
The same issue was reported here https://github.com/openucx/ucx/issues/9482.

**Comment by waarmond** [comment] 2024-03-13 08:58
Actually I've already done `--disable-go` to progress. Go > 1.20 seems to be incompatible

**Comment by rakhmets** [comment] 2024-04-09 14:23
Closed as duplicate of https://github.com/openucx/ucx/issues/9482

**Closed** 2024-04-09 14:23 UTC
Labels: Bug
