### ISSUE TITLE
[mtt] fail on osu_micro_benchmark_collective on arm

### ISSUE THREAD

**Issue by avildema** [openucx/ucx#6727] opened 2021-04-28 08:26 UTC
Configuration
```
OMPI: 4.1.1rc1
MOFED: MLNX_OFED_LINUX-5.2-2.2.0.0
Module: hpcx-gcc (2021-04-26)
Test module: mtt-tests/hpcx-gcc
Nodes: hp-arm x2 (ppn=224(x2), nodelist=hpc-arm-hp[02-03])
```
 
MTT log:

http://hpcweb.lab.mtl.com/hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20210426_112256_93096_8866_hpc-arm-hp02/html/test_stdout_ysC9r9.txt
 
Cmd:
`/hpc/local/benchmarks/daily/next/2021-04-26/hpcx-gcc-redhat7.6/ompi/bin/mpirun -np 32 --display-map -mca btl self --tag-output --timestamp-output -mca pml ucx -mca coll '^hcoll' -x UCX_ERROR_SIGNALS=SIGILL,SIGSEGV,SIGBUS,SIGFPE,SIGABRT -x UCX_HANDLE_ERRORS=bt -x UCX_IB_PCI_RELAXED_ORDERING=off --bind-to hwthread -x UCX_NET_DEVICES=mlx5_0:1,mlx5_3:1 -mca osc ucx -x UCX_IB_ADDR_TYPE=ib_global -x UCX_IB_REG_METHODS=rcache,direct -x UCX_TLS=dc_x,self,sm -x UCX_DC_MLX5_TX_POLICY=dcs_quota -mca pmix_base_async_modex 0 -mca mpi_add_procs_cutoff 100000 -mca pmix_base_collect_data 1 --map-by node /hpc/local/benchmarks/daily/next/2021-04-26/hpcx-gcc-redhat7.6/ompi/tests/osu-micro-benchmarks-5.6.2/osu_allgather`
 
Output:
```sh
node=hpc-arm-hp02, pid=71735:
Thread 4 (Thread 0xffffaaf6f1e0 (LWP 71759)):
#0  0x0000ffffab77f7d4 in epoll_pwait () from /lib64/libc.so.6
#1  0x0000ffffab4e8e70 in epoll_dispatch (base=0x3e5f6d80, tv=<optimized out>) at epoll.c:407
#2  0x0000ffffab4ec8c4 in opal_libevent2022_event_base_loop (base=0x3e5f6d80, flags=flags@entry=1) at event.c:1630
#3  0x0000ffffab4abf10 in progress_engine (obj=<optimized out>) at runtime/opal_progress_threads.c:105
#4  0x0000ffffab837c48 in start_thread () from /lib64/libpthread.so.0
#5  0x0000ffffab77f600 in thread_start () from /lib64/libc.so.6
Thread 3 (Thread 0xffffaa17f1e0 (LWP 71767)):
#0  0x0000ffffab77f7d4 in epoll_pwait () from /lib64/libc.so.6
#1  0x0000ffffab4e8e70 in epoll_dispatch (base=0x3e61ca00, tv=<optimized out>) at epoll.c:407
#2  0x0000ffffab4ec8c4 in opal_libevent2022_event_base_loop (base=0x3e61ca00, flags=flags@entry=1) at event.c:1630
#3  0x0000ffffaa621da4 in progress_engine (obj=<optimized out>) at runtime/pmix_progress_threads.c:232
#4  0x0000ffffab837c48 in start_thread () from /lib64/libpthread.so.0
#5  0x0000ffffab77f600 in thread_start () from /lib64/libc.so.6
Thread 2 (Thread 0xffffa89ef1e0 (LWP 71778)):
#0  0x0000ffffab77f7d4 in epoll_pwait () from /lib64/libc.so.6
#1  0x0000ffffa8d89504 in ucs_event_set_wait (event_set=<optimized out>, num_events=num_events@entry=0xffffa89ee9a0, timeout_ms=<optimized out>, event_set_handler=event_set_handler@entry=0xffffa8d72b94 <ucs_async_thread_ev_handler>, arg=arg@entry=0xffffa89ee9b0) at sys/event_set.c:198
#2  0x0000ffffa8d72ebc in ucs_async_thread_func (arg=0x3e6c6370) at async/thread.c:130
#3  0x0000ffffab837c48 in start_thread () from /lib64/libpthread.so.0
#4  0x0000ffffab77f600 in thread_start () from /lib64/libc.so.6
Thread 1 (Thread 0xffffabada200 (LWP 71735)):
#0  0x0000ffffa8c49058 in uct_ib_mlx5_get_cqe (cqe_index=<optimized out>, cq=<optimized out>) at /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/uct/ib/mlx5/ib_mlx5.inl:13
#1  uct_rc_mlx5_iface_poll_rx_cq (poll_flags=8, iface=<optimized out>) at /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/uct/ib/rc/accel/rc_mlx5.inl:265
#2  uct_rc_mlx5_iface_common_poll_rx (poll_flags=8, iface=<optimized out>) at /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/uct/ib/rc/accel/rc_mlx5.inl:1416
#3  uct_dc_mlx5_iface_progress (flags=8, arg=<optimized out>) at dc/dc_mlx5.c:245
#4  uct_dc_mlx5_iface_progress_ll (arg=0x3e8c0050) at dc/dc_mlx5.c:260
#5  0x0000ffffa8f10b48 in ucs_callbackq_dispatch (cbq=<optimized out>) at /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/ucs/datastruct/callbackq.h:211
#6  uct_worker_progress (worker=<optimized out>) at /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/uct/api/uct.h:2592
#7  ucp_worker_progress (worker=0x3e740010) at core/ucp_worker.c:2530
#8  0x0000ffffab4a6254 in opal_progress () at runtime/opal_progress.c:231
#9  0x0000ffffab8bc3ec in ompi_request_wait_completion (req=0x3e90dfd0) at ../ompi/request/request.h:415
#10 ompi_request_default_wait (req_ptr=0xffffc5021050, status=0xffffc5021058) at request/req_wait.c:42
#11 0x0000ffffab8f7acc in ompi_coll_base_sendrecv_actual (sendbuf=0xffff982e0000, scount=scount@entry=524288, sdatatype=sdatatype@entry=0x4204c0 <ompi_mpi_char>, dest=dest@entry=31, stag=stag@entry=-10, recvbuf=<optimized out>, rcount=rcount@entry=524288, rdatatype=rdatatype@entry=0x4204c0 <ompi_mpi_char>, source=source@entry=29, rtag=rtag@entry=-10, comm=comm@entry=0x421c00 <ompi_mpi_comm_world>, status=status@entry=0x0) at base/coll_base_util.c:62
#12 0x0000ffffab8f6424 in ompi_coll_base_sendrecv (stag=-10, rtag=-10, status=0x0, myid=<optimized out>, comm=<optimized out>, source=<optimized out>, rdatatype=0x4204c0 <ompi_mpi_char>, rcount=524288, recvbuf=<optimized out>, dest=31, sdatatype=0x4204c0 <ompi_mpi_char>, scount=524288, sendbuf=<optimized out>) at base/coll_base_util.h:133
#13 ompi_coll_base_allgather_intra_ring (sbuf=<optimized out>, scount=<optimized out>, sdtype=<optimized out>, rbuf=0xffff97be0000, rcount=524288, rdtype=0x4204c0 <ompi_mpi_char>, comm=0x421c00 <ompi_mpi_comm_world>, module=<optimized out>) at base/coll_base_allgather.c:408
#14 0x0000ffffa8196914 in ompi_coll_tuned_allgather_intra_dec_fixed (sbuf=<optimized out>, scount=<optimized out>, sdtype=<optimized out>, rbuf=<optimized out>, rcount=<optimized out>, rdtype=<optimized out>, comm=<optimized out>, module=<optimized out>) at coll_tuned_decision_fixed.c:1225
#15 0x0000ffffab8cc7d0 in PMPI_Allgather (sendbuf=<optimized out>, sendcount=sendcount@entry=524288, sendtype=sendtype@entry=0x4204c0 <ompi_mpi_char>, recvbuf=<optimized out>, recvcount=recvcount@entry=524288, recvtype=recvtype@entry=0x4204c0 <ompi_mpi_char>, comm=comm@entry=0x421c00 <ompi_mpi_comm_world>) at pallgather.c:125
#16 0x0000000000401984 in main (argc=1, argv=0xffffc5021398) at osu_allgather.c:97
```

**Comment by yosefe** [comment] 2021-10-30 11:48
closing the issue since it cannot be reproduced

**Closed by yosefe** 2021-10-30 11:48 UTC
Labels: Bug, MTT
