### ISSUE TITLE
[mtt] hang in various benchmarks with rc_x

### ISSUE THREAD

**Issue by amaslenn** [openucx/ucx#2470] opened 2018-04-01 13:04 UTC
Configuration:
```
OMPI: 3.1.0rc4
jazz x16 (ppn=28(x16), nodelist=jazz[05-08,18-20,23-29,31-32])
Job: ucx
```

MTT log: http://hpcweb.lab.mtl.com//hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20180330_220555_133271_370_jazz05/html/test_stdout_bSSKDb.txt

Cmd:
`mpirun -np 2 -mca btl self --tag-output --timestamp-output -mca pml ucx -mca coll '^hcoll' --bind-to core -x UCX_NET_DEVICES=mlx5_0:1 -x UCX_IB_REG_METHODS=rcache,direct -x UCX_TLS=rc,sm -x UCX_RC_TM_ENABLE=n -mca pmix_base_async_modex 0 -mca mpi_add_procs_cutoff 100000 -mca pmix_base_collect_data 1 --map-by node /hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20180330_220555_133271_370_jazz05/installs/eAww/tests/osu_micro_benchmark/osu-micro-benchmarks-5.3.2/mpi/one-sided/osu_get_latency`

Output:
```sh
Sun Apr  1 16:01:28 2018[1,0]<stdout>:# OSU MPI_Get latency Test v5.3.2
Sun Apr  1 16:01:28 2018[1,0]<stdout>:# Window creation: MPI_Win_allocate
Sun Apr  1 16:01:28 2018[1,0]<stdout>:# Synchronization: MPI_Win_flush
Sun Apr  1 16:01:28 2018[1,0]<stdout>:# Size          Latency (us)
--------------------------------------------------------------------------
At least one pair of MPI processes are unable to reach each other for
MPI communications.  This means that no Open MPI device has indicated
that it can be used to communicate between these processes.  This is
an error; Open MPI requires that all MPI processes be able to reach
each other.  This error can sometimes be the result of forgetting to
specify the "self" BTL.

  Process 1 ([[18353,1],0]) is on host: jazz05
  Process 2 ([[18353,1],1]) is on host: unknown!
  BTLs attempted: self

Your MPI job is now going to abort; sorry.
--------------------------------------------------------------------------
[hpchead:27083] 1 more process has sent help message help-mca-bml-r2.txt / unreachable proc
[hpchead:27083] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
```

Test works with TLS `dc`.

Looks similar to #2454.

edit: yossi: this particular hang looks like deadlock because osc component is using blocking AMO

**Comment by amaslenn** [comment] 2018-04-03 09:32
I see a hang in `atest` which is reproducible with `rc`/`rc_x` only, `dc`/`ud` works nice.

MTT log: http://hpcweb.lab.mtl.com//hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20180401_003813_94681_432_jazz18/html/test_stdout_XKCWGf.txt

Cmd:
`mpirun -np 308 -mca btl self --tag-output --timestamp-output -mca pml ucx -mca coll '^hcoll' --bind-to core -x UCX_NET_DEVICES=mlx5_0:1 -x UCX_IB_REG_METHODS=rcache,direct -x UCX_TLS=rc_x,sm --map-by node /hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20180401_003813_94681_432_jazz18/installs/WUMF/tests/atest/atest.git/src/atest -l 1000 --test-cross 0`

**Comment by alinask** [comment] 2018-04-11 16:02
An additional hang on osu - may be related:

mpirun -np 32  -mca btl self  -mca pml ucx -mca coll '^hcoll' --bind-to core -x UCX_NET_DEVICES=mlx5_0:1 -x UCX_IB_REG_METHODS=rcache,direct -x UCX_TLS=rc_x,sm -x UCX_RC_MLX5_TM_ENABLE=y -mca pmix_base_async_modex 1 -mca mpi_add_procs_cutoff 0 -mca pmix_base_collect_data 0 --map-by node /mnt/lustre/users/mtt/scratch/ucx_ompi/20180410_161318_13428_74745_clx-vega-001/installs/GO4e/tests/osu_micro_benchmark/osu-micro-benchmarks-5.3.2/mpi/collective/osu_iscatterv

```
# OSU MPI Non-blocking Scatterv Latency Test v5.3.2
# Overall = Coll. Init + Compute + MPI_Test + MPI_Wait

# Size           Overall(us)       Compute(us)    Pure Comm.(us)        Overlap(%)
1                       8.28              7.34              6.56             85.56
2                       8.26              7.34              6.56             86.00
4                       8.22              7.31              6.55             86.15
8                       8.24              7.36              6.58             86.54
16                      8.26              7.31              6.54             85.43
32                      8.73              7.78              7.00             86.41
64                      9.19              8.08              7.26             84.71
128                     9.55              8.40              7.60             84.86
<hang>
```

May need to run a few times to reproduce. Doesn't seem to reproduce with dc.

•Nodes: vega x8 (ppn=36(x8), nodelist=clx-vega-[001-005,007-009])
•Module: hpcx-gcc

```
hca_id: mlx5_0
        transport:                      InfiniBand (0)
        fw_ver:                         16.22.1002
        node_guid:                      f452:1403:0025:0080
        sys_image_guid:                 f452:1403:0025:0080
        vendor_id:                      0x02c9
        vendor_part_id:                 4121
        hw_ver:                         0x0
        board_id:                       MT_0000000009
        phys_port_cnt:                  1
        Device ports:
                port:   1
                        state:                  PORT_ACTIVE (4)
                        max_mtu:                4096 (5)
                        active_mtu:             4096 (5)
                        sm_lid:                 1
                        port_lid:               133
                        port_lmc:               0x00
                        link_layer:             InfiniBand
```

MLNX_OFED_LINUX-4.3-1.0.1.0

**Comment by yosefe** [comment] 2018-04-23 16:44
closing this issue, since the first osu_get_latency hang is a duplicate of #2454, and the other 2 hangs are a duplicate of #2469

**Closed by yosefe** 2018-04-23 16:44 UTC
Labels: bug, mtt
