### ISSUE TITLE
[mtt][ucx-emulation] Fail test mpp_pingpong

### ISSUE THREAD

**Issue by avildema** [openucx/ucx#7595] opened 2021-10-28 08:43 UTC
Configuration
```
OMPI: 4.1.2rc2
MOFED: MLNX_OFED_LINUX-5.4-1.0.3.0
Module: hpcx-gcc (2021-10-26)
Test module: none
Nodes: hp-arm x2 (ppn=224(x2), nodelist=hpc-arm-hp[01,03])
```
 
MTT log:
http://hpcweb.lab.mtl.com/hpc/mtl_scrap/users/mtt/scratch/shmem/20211026_233453_64762_78449_hpc-arm-hp01/html/test_stdout_Rq3WIW.txt

Cmd:
`/hpc/local/benchmarks/daily/next/2021-10-26/hpcx-gcc-redhat7.6/ompi/bin/oshrun -np 224 --display-map --bind-to hwthread -mca oshmem_proc_group_cache_size 10000 -mca sshmem ucx -mca atomic ucx -x UCX_DC_MLX5_DCI_FULL_HANDSHAKE=off -x UCX_DC_MLX5_DCT_FULL_HANDSHAKE=off -mca coll '^hcoll' -mca coll_hcoll_enable 0 -mca spml ucx -mca pml ucx -x UCX_HANDLE_ERRORS=bt -x UCX_TLS=ud_x -x UCX_UD_TIMEOUT=10m -x UCX_NET_DEVICES=mlx5_0:1,mlx5_3:1 --map-by node -x SHMEM_SYMMETRIC_HEAP_SIZE=716M /hpc/mtl_scrap/users/mtt/scratch/shmem/20211026_233453_64762_78449_hpc-arm-hp01/installs/xjGC/tests/mpp_24/mtt-tests.git/mpp_bench_v1.0/bin/pingpong.shmem 0 4 16`
 
Output:
```sh
pair       0: 217 ->  89:       1 iters in 2.491e-05 wall secs (2.491e-05 /iter)
pair       0: 217 ->  89:       2 iters in 1.347e-05 wall secs (6.735e-06 /iter)
pair       0: 217 ->  89:       4 iters in 2.253e-05 wall secs (5.633e-06 /iter)
pair       0: 217 ->  89:       8 iters in 4.256e-05 wall secs (5.320e-06 /iter)
pair       0: 217 ->  89:      16 iters in 8.345e-05 wall secs (5.215e-06 /iter)
pair       1: 155 -> 118:       1 iters in 3.946e-05 wall secs (3.946e-05 /iter)
pair       1: 155 -> 118:       2 iters in 1.597e-05 wall secs (7.987e-06 /iter)
pair       1: 155 -> 118:       4 iters in 2.503e-05 wall secs (6.258e-06 /iter)
pair       1: 155 -> 118:       8 iters in 4.303e-05 wall secs (5.379e-06 /iter)
pair       1: 155 -> 118:      16 iters in 8.392e-05 wall secs (5.245e-06 /iter)pair       2:   7 -> 158:       1 iters in 2.849e-05 wall secs (2.849e-05 /iter)
pair       2:   7 -> 158:       2 iters in 1.502e-05 wall secs (7.510e-06 /iter)
pair       2:   7 -> 158:       4 iters in 2.599e-05 wall secs (6.497e-06 /iter)
pair       2:   7 -> 158:       8 iters in 4.447e-05 wall secs (5.558e-06 /iter)
pair       2:   7 -> 158:      16 iters in 8.404e-05 wall secs (5.253e-06 /iter)pair       3:  31 ->  33:       1 iters in 2.241e-05 wall secs (2.241e-05 /iter)
pair       3:  31 ->  33:       2 iters in 1.693e-05 wall secs (8.464e-06 /iter)pair       3:  31 ->  33:       4 iters in 3.147e-05 wall secs (7.868e-06 /iter)
pair       3:  31 ->  33:       8 iters in 4.303e-05 wall secs (5.379e-06 /iter)pair       3:  31 ->  33:      16 iters in 8.297e-05 wall secs (5.186e-06 /iter)
[hpc-arm-hp03:162296:a:162517] ib_mlx5_log.c:170  Local QP operation on mlx5_0:1/IB (synd 0x2 vend 0x17 hw_synd 0/163)
[hpc-arm-hp03:162296:a:162517] ib_mlx5_log.c:170  UD QP 0x11fae wqe[1678]: opcode RECV [hpc-arm-hp03:162279:a:162514] ib_mlx5_log.c:170  Local QP operation on mlx5_0:1/IB (synd 0x2 vend 0x17 hw_synd 0/163)
[hpc-arm-hp03:162279:a:162514] ib_mlx5_log.c:170  UD QP 0x11faf wqe[1669]: opcode RECV [hpc-arm-hp03:162281:a:162525] ib_mlx5_log.c:170  Local QP operation on mlx5_0:1/IB (synd 0x2 vend 0x17 hw_synd 0/163)
[hpc-arm-hp03:162281:a:162525] ib_mlx5_log.c:170  UD QP 0x11fad wqe[1680]: opcode RECV [hpc-arm-hp03:162284:a:162523] ib_mlx5_log.c:170  Local QP operation on mlx5_0:1/IB (synd 0x2 vend 0x17 hw_synd 0/163)
[hpc-arm-hp03:162284:a:162523] ib_mlx5_log.c:170  UD QP 0x11fac wqe[1675]: opcode RECV 
==== backtrace (tid: 162517) ====
 0 0x00000000000249ac uct_ib_mlx5_completion_with_err()  /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/uct/ib/mlx5/ib_mlx5_log.c:162 1 0x00000000000588b8 uct_ib_mlx5_poll_cq()  /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/uct/ib/mlx5/ib_mlx5.inl:91
 2 0x00000000000588b8 uct_ud_mlx5_iface_async_progress()  /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/uct/ib/ud/accel/ud_mlx5.c:580
 3 0x000000000004f79c uct_ud_iface_async_progress()  /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/uct/ib/ud/base/ud_iface.c:254
 4 0x000000000004f79c uct_ud_iface_timer()  /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/uct/ib/ud/base/ud_iface.c:284
 5 0x00000000000420a8 ucs_async_handler_invoke()  /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/ucs/async/async.c:251
 6 0x00000000000420a8 ucs_async_handler_dispatch()  /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/ucs/async/async.c:273
 7 0x00000000000420a8 ucs_async_dispatch_handlers()  /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/ucs/async/async.c:305
 8 0x00000000000423b4 ucs_async_dispatch_timerq()  /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/ucs/async/async.c:332
 9 0x0000000000045128 ucs_async_thread_func()  /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/ucs/async/thread.c:141
10 0x0000000000007c48 start_thread()  :0
11 0x00000000000df600 thread_start()  :0
=================================
[hpc-arm-hp03:162296] *** Process received signal ***
[hpc-arm-hp03:162296] Signal: Aborted (6)
[hpc-arm-hp03:162296] Signal code:  (-6)
[hpc-arm-hp03:162296] [ 0] [0xffff8717066c]
[hpc-arm-hp03:162296] [ 1] /lib64/libc.so.6(gsignal+0x4c)[0xffff86d450e8]
[hpc-arm-hp03:162296] [ 2] /lib64/libc.so.6(abort+0x11c)[0xffff86d46760]
[hpc-arm-hp03:162296] [ 3] /hpc/local/benchmarks/daily/next/2021-10-26/hpcx-gcc-redhat7.6/ucx/lib/libucs.so.0(ucs_fatal_error_message+0x58)[0xffff843348dc]
[hpc-arm-hp03:162296] [ 4] /hpc/local/benchmarks/daily/next/2021-10-26/hpcx-gcc-redhat7.6/ucx/lib/libucs.so.0(ucs_log_default_handler+0x590)[0xffff843392b0]
[hpc-arm-hp03:162296] [ 5] /hpc/local/benchmarks/daily/next/2021-10-26/hpcx-gcc-redhat7.6/ucx/lib/libucs.so.0(ucs_log_dispatch+0xf0)[0xffff843396c8]
[hpc-arm-hp03:162296] [ 6] /hpc/local/benchmarks/daily/next/2021-10-26/hpcx-gcc-redhat7.6/ucx/lib/ucx/libuct_ib.so.0(uct_ib_mlx5_completion_with_err+0x3e8)[0xffff841c49ac]
[hpc-arm-hp03:162296] [ 7] /hpc/local/benchmarks/daily/next/2021-10-26/hpcx-gcc-redhat7.6/ucx/lib/ucx/libuct_ib.so.0(+0x588b8)[0xffff841f88b8]
[hpc-arm-hp03:162296] [ 8] /hpc/local/benchmarks/daily/next/2021-10-26/hpcx-gcc-redhat7.6/ucx/lib/ucx/libuct_ib.so.0(+0x4f79c)[0xffff841ef79c]
[hpc-arm-hp03:162296] [ 9] /hpc/local/benchmarks/daily/next/2021-10-26/hpcx-gcc-redhat7.6/ucx/lib/libucs.so.0(ucs_async_dispatch_handlers+0xb8)[0xffff843220a8]
[hpc-arm-hp03:162296] [10] /hpc/local/benchmarks/daily/next/2021-10-26/hpcx-gcc-redhat7.6/ucx/lib/libucs.so.0(ucs_async_dispatch_timerq+0x100)[0xffff843223b4]
[hpc-arm-hp03:162296] [11] /hpc/local/benchmarks/daily/next/2021-10-26/hpcx-gcc-redhat7.6/ucx/lib/libucs.so.0(+0x45128)[0xffff84325128]
[hpc-arm-hp03:162296] [12] /lib64/libpthread.so.0(+0x7c48)[0xffff86ea7c48]
[hpc-arm-hp03:162296] [13] /lib64/libc.so.6(+0xdf600)[0xffff86def600]
[hpc-arm-hp03:162296] *** End of error message ***--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------==== backtrace (tid: 162525) ====
 0 0x00000000000249ac uct_ib_mlx5_completion_with_err()  /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/uct/ib/mlx5/ib_mlx5_log.c:162
 1 0x00000000000588b8 uct_ib_mlx5_poll_cq()  /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/uct/ib/mlx5/ib_mlx5.inl:91
 2 0x00000000000588b8 uct_ud_mlx5_iface_async_progress()  /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/uct/ib/ud/accel/ud_mlx5.c:580
 3 0x000000000004f79c uct_ud_iface_async_progress()  /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/uct/ib/ud/base/ud_iface.c:254
 4 0x000000000004f79c uct_ud_iface_timer()  /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/uct/ib/ud/base/ud_iface.c:284
 5 0x00000000000420a8 ucs_async_handler_invoke()  /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/ucs/async/async.c:251
 6 0x00000000000420a8 ucs_async_handler_dispatch()  /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/ucs/async/async.c:273
 7 0x00000000000420a8 ucs_async_dispatch_handlers()  /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/ucs/async/async.c:305
 8 0x00000000000423b4 ucs_async_dispatch_timerq()  /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/ucs/async/async.c:332
 9 0x0000000000045128 ucs_async_thread_func()  /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/ucs/async/thread.c:141
10 0x0000000000007c48 start_thread()  :0
11 0x00000000000df600 thread_start()  :0
=================================
```

**Comment by rakhmets** [comment] 2022-02-03 11:09
The issue is fixed in frames of another issue. Here is a link to the corresponding issue: https://redmine.mellanox.com/issues/2865981 (NVIDIA internal link).

**Closed by rakhmets** 2022-02-03 11:09 UTC
Labels: Bug, MTT
