### ISSUE TITLE
First AM with TLS posix get's dropped on 1.10-rc4

### ISSUE THREAD

**Issue by vchuravy** [openucx/ucx#6394] opened 2021-02-24 02:13 UTC
### Describe the bug
The first active message that is send with `UCP_AM_SEND_FLAG_REPLY` after wireup is dropped.

I am sending active messages with `UCP_AM_SEND_FLAG_REPLY` using UCX 1.10-rc4 and I observe the following:

```
    From worker 2:	[1614131887.522129] [odin:768998:0]       mm_iface.c:232  UCX  DATA  RX: AM_SHORT am_id 26 len 24 
      From worker 2:	[1614131887.522130] [odin:768998:0]         ucp_am.c:1181 UCX  DATA  worker 0x2124f80: ep id 0xffffffffffffffff was not found, dropAM (reply proto)
      From worker 2:	[1614131887.522132] [odin:768998:0]     ucp_worker.c:738  UCX  TRACE wiface 0x18c8460 progress returned 2, but no active messages were received
```
The full log is attached here: https://gist.github.com/vchuravy/bcffcc5a9d6e5b2af9ca6284ce0df797

Subsequent messages are received.

### Steps to Reproduce
- Command line
- 1.10-rc4
```
# UCT version=1.10.0 revision 
# configured with: --prefix=/workspace/destdir --build=x86_64-linux-musl --host=x86_64-linux-gnu --disable-debug --disable-assertions --disable-params-check --disable-static --disable-profiling --enable-shared --enable-mt --enable-frame-pointer --enable-cma --with-rdmacm=/workspace/destdir --with-cuda=/workspace/destdir/cuda --with-rocm=/workspace/destdir
```
- `UCX_TLS=posix,self`

I haven't written a reproducer in C, and found this while working on the Julia bindings for UCX.
My test case can be found here https://github.com/JuliaParallel/UCX.jl/pull/34/commits/97dca1496cef285d8053dcfdb1bc01f723df4dbe

**Comment by yosefe** [comment] 2021-02-24 18:20
@brminich IMO the issue is that we send short with reply ep message from ucp_am_try_send_short() before doing ucp_ep_resolve_remote_id(). should be easy to reproduce in a gtest which sends short-with-reply over mm transport.

**Comment by brminich** [comment] 2021-02-24 18:31
no, we have such gtest
https://github.com/openucx/ucx/blob/master/src/ucp/core/ucp_am.c#L531

**Comment by yosefe** [comment] 2021-02-24 18:34
it happens before taking proto:
https://github.com/openucx/ucx/blob/master/src/ucp/core/ucp_am.c#L927

**Comment by brminich** [comment] 2021-02-24 18:39
reply proto uses this func https://github.com/openucx/ucx/blob/master/src/ucp/core/ucp_am.c#L930
resolving id is inside

**Comment by yosefe** [comment] 2021-02-24 18:41
ohh the problem is you take am_ep before calling resolve id..

**Comment by brminich** [comment] 2021-02-24 18:49
yeah and the tests are not initializing ep error handling

**Closed** 2021-02-25 05:18 UTC
Labels: Bug, Release Blocker
