### ISSUE TITLE
[mtt] Pls try adding --mca opal_common_ucx_opal_mem_hooks 1 to mpirun/oshrun

### ISSUE THREAD

**Issue by avildema** [openucx/ucx#7708] opened 2021-11-25 12:05 UTC
Configuration
```
OMPI: master-202111250241-ed05ee1
MOFED: MLNX_OFED_LINUX-5.4-1.0.3.0
Module: none
Test module: none
Nodes: jazz x2 (ppn=28(x2), nodelist=jazz[15,29])
```
 
MTT log:
http://hpcweb.lab.mtl.com/hpc/mtr_scrap/users/mtt/scratch/pmi/20211125_083438_20540_82569_jazz15.swx.labs.mlnx/html/test_stdout_3FZ5Tt.txt

Comment:
See a same message on other tests
ex:

http://hpcweb.lab.mtl.com/hpc/mtr_scrap/users/mtt/scratch/ucc/20211124_142110_30826_82498_vulcan02.swx.labs.mlnx/html/test_stdout_UhdMKX.txt
http://hpcweb.lab.mtl.com/hpc/mtr_scrap/users/mtt/scratch/ucc/20211124_142110_30826_82498_vulcan02.swx.labs.mlnx/html/test_stdout_0WX5Q7.txt

 
Output:
```sh
+ env OMPI_MCA_btl_openib_if_include=mlx5_2:1 OMPI_MCA_btl_openib_allow_ib=true OMPI_MCA_mpi_add_procs_cutoff=0 OMPI_MCA_pmix_base_async_modex=1 OMPI_MCA_pmix_base_collect_data=0 /tmp/mtt_82569_slurm_deploy/slurm/bin/srun -N 2 -n 56 --mpi=pmix -p deploy /hpc/mtr_scrap/users/mtt/scratch/pmi/20211125_083438_20540_82569_jazz15.swx.labs.mlnx/installs/_GsZ/tests/trivial/test_get__trivial/ring_usempi[jazz15.swx.labs.mlnx:119671] /hpc/mtr_scrap/users/mtt/scratch/pmi/20211125_083438_20540_82569_jazz15.swx.labs.mlnx/slurm_deploy/source/ompi/opal/mca/common/ucx/common_ucx.c:393  Warning: UCX is unable to handle VM_UNMAP event. This may cause performance degradation or data corruption. Pls try adding --mca opal_common_ucx_opal_mem_hooks 1 to mpirun/oshrun command line to resolve this issue.
[jazz15.swx.labs.mlnx:119693] /hpc/mtr_scrap/users/mtt/scratch/pmi/20211125_083438_20540_82569_jazz15.swx.labs.mlnx/slurm_deploy/source/ompi/opal/mca/common/ucx/common_ucx.c:393  Warning: UCX is unable to handle VM_UNMAP event. This may cause performance degradation or data corruption. Pls try adding --mca opal_common_ucx_opal_mem_hooks 1 to mpirun/oshrun command line to resolve this issue.
[jazz15.swx.labs.mlnx:119690] /hpc/mtr_scrap/users/mtt/scratch/pmi/20211125_083438_20540_82569_jazz15.swx.labs.mlnx/slurm_deploy/source/ompi/opal/mca/common/ucx/common_ucx.c:393  Warning: UCX is unable to handle VM_UNMAP event. This may cause performance degradation or data corruption. Pls try adding --mca opal_common_ucx_opal_mem_hooks 1 to mpirun/oshrun command line to resolve this issue.
[jazz15.swx.labs.mlnx:119691] /hpc/mtr_scrap/users/mtt/scratch/pmi/20211125_083438_20540_82569_jazz15.swx.labs.mlnx/slurm_deploy/source/ompi/opal/mca/common/ucx/common_ucx.c:393  Warning: UCX is unable to handle VM_UNMAP event. This may cause performance degradation or data corruption. Pls try adding --mca opal_common_ucx_opal_mem_hooks 1 to mpirun/oshrun command line to resolve this issue.
[jazz15.swx.labs.mlnx:119689] /hpc/mtr_scrap/users/mtt/scratch/pmi/20211125_083438_20540_82569_jazz15.swx.labs.mlnx/slurm_deploy/source/ompi/opal/mca/common/ucx/common_ucx.c:393  Warning: UCX is unable to handle VM_UNMAP event. This may cause performance degradation or data corruption. Pls try adding --mca opal_common_ucx_opal_mem_hooks 1 to mpirun/oshrun command line to resolve this issue.
[jazz15.swx.labs.mlnx:119672] /hpc/mtr_scrap/users/mtt/scratch/pmi/20211125_083438_20540_82569_jazz15.swx.labs.mlnx/slurm_deploy/source/ompi/opal/mca/common/ucx/common_ucx.c:393  Warning: UCX is unable to handle VM_UNMAP event. This may cause performance degradation or data corruption. Pls try adding --mca opal_common_ucx_opal_mem_hooks 1 to mpirun/oshrun command line to resolve this issue.
[jazz15.swx.labs.mlnx:119673] /hpc/mtr_scrap/users/mtt/scratch/pmi/20211125_083438_20540_82569_jazz15.swx.labs.mlnx/slurm_deploy/source/ompi/opal/mca/common/ucx/common_ucx.c:393  Warning: UCX is unable to handle VM_UNMAP event. This may cause performance degradation or data corruption. Pls try adding --mca opal_common_ucx_opal_mem_hooks 1 to mpirun/oshrun command line to resolve this issue.
[jazz15.swx.labs.mlnx:119682] /hpc/mtr_scrap/users/mtt/scratch/pmi/20211125_083438_20540_82569_jazz15.swx.labs.mlnx/slurm_deploy/source/ompi/opal/mca/common/ucx/common_ucx.c:393  Warning: UCX is unable to handle VM_UNMAP event. This may cause performance degradation or data corruption. Pls try adding --mca opal_common_ucx_opal_mem_hooks 1 to mpirun/oshrun command line to resolve this issue.
[jazz15.swx.labs.mlnx:119681] /hpc/mtr_scrap/users/mtt/scratch/pmi/20211125_083438_20540_82569_jazz15.swx.labs.mlnx/slurm_deploy/source/ompi/opal/mca/common/ucx/common_ucx.c:393  Warning: UCX is unable to handle VM_UNMAP event. This may cause performance degradation or data corruption. Pls try adding --mca opal_common_ucx_opal_mem_hooks 1 to mpirun/oshrun command line to resolve this issue.
[1637823237.001992] [jazz15:119681:0]          wireup.c:1038 UCX  ERROR   old: am_lane 0 wireup_msg_lane 1 cm_lane <none> reachable_mds 0x78 ep_check_map 0x0
[1637823237.002029] [jazz15:119681:0]          wireup.c:1048 UCX  ERROR   old: lane[0]: 19:rc_mlx5/mlx5_4:1.0 md[6]      -> md[4]/ib/sysdev[255] rma_bw#0 am am_bw#0[1637823237.002036] [jazz15:119681:0]          wireup.c:1048 UCX  ERROR   old: lane[1]:  9:rc_mlx5/mlx5_0:1.0 md[4]      -> md[6]/ib/sysdev[255] rma_bw#1 wireup
[1637823237.002041] [jazz15:119681:0]          wireup.c:1038 UCX  ERROR   new: am_lane 0 wireup_msg_lane 3 cm_lane <none> reachable_mds 0x2f9 ep_check_map 0x0
[1637823237.002045] [jazz15:119681:0]          wireup.c:1048 UCX  ERROR   new: lane[0]:  0:posix/memory.0 md[0]          -> md[0]/posix/sysdev[255] am am_bw#0
[1637823237.002050] [jazz15:119681:0]          wireup.c:1048 UCX  ERROR   new: lane[1]: 25:xpmem/memory.0 md[9]          -> md[9]/xpmem/sysdev[255] rkey_ptr
[1637823237.002054] [jazz15:119681:0]          wireup.c:1048 UCX  ERROR   new: lane[2]: 23:cma/memory.0 md[7]            -> md[7]/cma/sysdev[255] rma_bw#0
[1637823237.002059] [jazz15:119681:0]          wireup.c:1048 UCX  ERROR   new: lane[3]: 19:rc_mlx5/mlx5_4:1.0 md[6]      -> md[4]/ib/sysdev[255] rma_bw#1 wireup
```

**Comment by brminich** [comment] 2021-11-25 12:22
Checking whether it is regression:


```
degradation or data corruption. Pls try adding --mca opal_common_ucx_opal_mem_hooks 1 to mpirun/oshrun command line to resolve this issue.
[1637823237.001992] [jazz15:119681:0]          wireup.c:1038 UCX  ERROR   old: am_lane 0 wireup_msg_lane 1 cm_lane <none> reachable_mds 0x78 ep_check_map 0x0
[1637823237.002029] [jazz15:119681:0]          wireup.c:1048 UCX  ERROR   old: lane[0]: 19:rc_mlx5/mlx5_4:1.0 md[6]      -> md[4]/ib/sysdev[255] rma_bw#0 am am_bw#0[1637823237.002036] [jazz15:119681:0]          wireup.c:1048 UCX  ERROR   old: lane[1]:  9:rc_mlx5/mlx5_0:1.0 md[4]      -> md[6]/ib/sysdev[255] rma_bw#1 wireup
[1637823237.002041] [jazz15:119681:0]          wireup.c:1038 UCX  ERROR   new: am_lane 0 wireup_msg_lane 3 cm_lane <none> reachable_mds 0x2f9 ep_check_map 0x0
[1637823237.002045] [jazz15:119681:0]          wireup.c:1048 UCX  ERROR   new: lane[0]:  0:posix/memory.0 md[0]          -> md[0]/posix/sysdev[255] am am_bw#0
[1637823237.002050] [jazz15:119681:0]          wireup.c:1048 UCX  ERROR   new: lane[1]: 25:xpmem/memory.0 md[9]          -> md[9]/xpmem/sysdev[255] rkey_ptr
[1637823237.002054] [jazz15:119681:0]          wireup.c:1048 UCX  ERROR   new: lane[2]: 23:cma/memory.0 md[7]            -> md[7]/cma/sysdev[255] rma_bw#0
[1637823237.002059] [jazz15:119681:0]          wireup.c:1048 UCX  ERROR   new: lane[3]: 19:rc_mlx5/mlx5_4:1.0 md[6]      -> md[4]/ib/sysdev[255] rma_bw#1 wireup
[jazz15:119681:0:119681]      wireup.c:1336 Fatal: endpoint reconfiguration not supported yet[jazz15.swx.labs.mlnx:119666] 
```

**Comment by yosefe** [comment] 2022-01-03 09:01
1. In UCC, the message `Warning: UCX is unable to handle VM_UNMAP event. This may cause performance degradation or data corruption` seem to be caused by the presence of btl_uct. 
   * Adding `--mca btl ^uct` to the command removes the message
   * OpenMPI in UCC MTT should be configured with ` --with-platform=contrib/platform/mellanox/optimized` to disable build of btl_uct
2. The logs of PMI MTT are deleted. @avildema can you please repost the full command lines to reproduce the issue?

**Comment by karasevb** [comment] 2022-01-11 05:41
To avoid this failure: following the commit https://github.com/Mellanox/hpc-mtt-conf/commit/af74e721d9a207e4d44b7dbcb17ecf3607ffeb38, the run cmd should contain the env: `PMIX_MCA_gds=^ds12,ds21`, that is not presented in the mtt's cmd line:
```
+ env OMPI_MCA_btl_openib_if_include=mlx5_2:1 OMPI_MCA_btl_openib_allow_ib=true OMPI_MCA_mpi_add_procs_cutoff=0 OMPI_MCA_pmix_base_async_modex=1 OMPI_MCA_pmix_base_collect_data=0 /tmp/mtt_82569_slurm_deploy/slurm/bin/srun -N 2 -n 56 --mpi=pmix -p deploy /hpc/mtr_scrap...
```
The dstor component is no longer supported for OMPI starting with version 5.x, which caused issues for async modex.

**Comment by karasevb** [comment] 2022-01-11 05:41
@avildema please fix

**Comment by karasevb** [comment] 2022-01-13 07:08
should be fixed by https://github.com/Mellanox/hpc-mtt-conf/pull/739

**Comment by brminich** [comment] 2022-01-16 13:49
@avildema, closing this one, as it is fixed in MTT config

**Closed by brminich** 2022-01-16 13:49 UTC
Labels: Bug, MTT
