### ISSUE TITLE
failure on tcp/uct_p2p_mix_test.mix_10000/0 with valgrind

### ISSUE THREAD

**Issue by alinask** [openucx/ucx#4419] opened 2019-11-10 07:42 UTC
```
[2019-11-09T10:49:57.960Z] [----------] 1 test from tcp/uct_p2p_mix_test
[2019-11-09T10:49:57.960Z] [ RUN      ] tcp/uct_p2p_mix_test.mix_10000/0 <tcp/enp4s0>
[2019-11-09T11:05:04.598Z] /scrap/jenkins/workspace/ucx-5/contrib/../test/gtest/common/test_helpers.cc:49: Failure
[2019-11-09T11:05:04.598Z] Failed
[2019-11-09T11:05:04.598Z] Connection timed out - abort testing
[2019-11-09T11:05:04.598Z] [hpc-test-node-upstream-01:25859:0:25859] Caught signal 6 (Aborted: tkill(2) or tgkill(2))
[2019-11-09T11:07:40.987Z] ==== backtrace (tid:  25859) ====
[2019-11-09T11:07:40.987Z]  0 0x00000000000526a8 ucs_debug_print_backtrace()  /scrap/jenkins/workspace/ucx-5/contrib/../src/ucs/debug/debug.c:625
[2019-11-09T11:07:40.987Z]  1 0x00000000000f8921 __epoll_wait_nocancel()  :0
[2019-11-09T11:07:40.987Z]  2 0x0000000000060803 ucs_event_set_wait()  /scrap/jenkins/workspace/ucx-5/contrib/../src/ucs/sys/event_set.c:196
[2019-11-09T11:07:40.987Z]  3 0x000000000001ebbb uct_tcp_iface_progress()  /scrap/jenkins/workspace/ucx-5/contrib/../src/uct/tcp/tcp_iface.c:211
[2019-11-09T11:07:40.987Z]  4 0x00000000006649aa uct_test::entity::progress()  /scrap/jenkins/workspace/ucx-5/contrib/../src/ucs/datastruct/callbackq.h:211
[2019-11-09T11:07:40.987Z]  5 0x0000000000666e50 uct_test::entity::flush()  /scrap/jenkins/workspace/ucx-5/contrib/../test/gtest/uct/uct_test.cc:1118
[2019-11-09T11:07:40.987Z]  6 0x000000000062d8af uct_p2p_mix_test::run()  /scrap/jenkins/workspace/ucx-5/contrib/../test/gtest/uct/test_p2p_mix.cc:159
[2019-11-09T11:07:40.987Z]  7 0x0000000000579f92 ucs::test_base::run()  /scrap/jenkins/workspace/ucx-5/contrib/../test/gtest/common/test.cc:280
[2019-11-09T11:07:40.987Z]  8 0x000000000057a0a1 ucs::test_base::TestBodyProxy()  /scrap/jenkins/workspace/ucx-5/contrib/../test/gtest/common/test.cc:306
[2019-11-09T11:07:40.987Z]  9 0x000000000056266e testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>()  /scrap/jenkins/workspace/ucx-5/contrib/../test/gtest/common/gtest-all.cc:3562
[2019-11-09T11:07:40.987Z] 10 0x000000000055a2a0 testing::Test::Run()  /scrap/jenkins/workspace/ucx-5/contrib/../test/gtest/common/gtest-all.cc:3634
[2019-11-09T11:07:40.987Z] 11 0x000000000055a615 testing::Test::Run()  /scrap/jenkins/workspace/ucx-5/contrib/../test/gtest/common/gtest-all.cc:3626
[2019-11-09T11:07:40.987Z] 12 0x000000000055a755 testing::TestInfo::Run()  /scrap/jenkins/workspace/ucx-5/contrib/../test/gtest/common/gtest-all.cc:3929
[2019-11-09T11:07:40.987Z] 13 0x000000000055b185 testing::TestCase::Run()  /scrap/jenkins/workspace/ucx-5/contrib/../test/gtest/common/gtest-all.cc:5806
[2019-11-09T11:07:40.987Z] 14 0x000000000055b3fd testing::internal::UnitTestImpl::RunAllTests()  /scrap/jenkins/workspace/ucx-5/contrib/../test/gtest/common/gtest-all.cc:5725
[2019-11-09T11:07:40.987Z] 15 0x000000000054287b RUN_ALL_TESTS()  /scrap/jenkins/workspace/ucx-5/contrib/../test/gtest/common/gtest.h:20059
[2019-11-09T11:07:40.987Z] 16 0x0000000000021c05 __libc_start_main()  ???:0
[2019-11-09T11:07:40.987Z] 17 0x00000000005435e8 _start()  ???:0
[2019-11-09T11:07:40.987Z] =================================
[2019-11-09T11:07:40.987Z] Sending notification to alinas@mellanox.com
[2019-11-09T11:10:02.359Z] [hpc-test-node-upstream-01:25859:0:25859] Process frozen...
[2019-11-09T13:52:05.740Z] Sending interrupt signal to process
[2019-11-09T13:52:12.455Z] ==25859== 
[2019-11-09T13:52:12.455Z] ==25859== Process terminating with default action of signal 15 (SIGTERM)
[2019-11-09T13:52:12.455Z] ==25859==    at 0x6739F0D: ??? (in /usr/lib64/libpthread-2.17.so)
[2019-11-09T13:52:12.455Z] ==25859==    by 0x5089904: ucs_debug_freeze (debug.c:789)
[2019-11-09T13:52:12.455Z] ==25859==    by 0x508D2FD: ucs_error_freeze (debug.c:908)
[2019-11-09T13:52:12.455Z] ==25859==    by 0x508D2FD: ucs_handle_error (debug.c:1071)
[2019-11-09T13:52:12.455Z] ==25859==    by 0x508D59D: ucs_debug_handle_error_signal (debug.c:1020)
[2019-11-09T13:52:12.455Z] ==25859==    by 0x508D642: ucs_error_signal_handler (debug.c:1052)
[2019-11-09T13:52:12.455Z] ==25859==    by 0x673A5DF: ??? (in /usr/lib64/libpthread-2.17.so)
[2019-11-09T13:52:12.455Z] ==25859==    by 0x77A9920: ??? (in /usr/lib64/libc-2.17.so)
[2019-11-09T13:52:12.455Z] ==25859== 
[2019-11-09T13:52:12.455Z] ==25859== HEAP SUMMARY:
[2019-11-09T13:52:12.455Z] ==25859==     in use at exit: 42,265,915 bytes in 55,796 blocks
[2019-11-09T13:52:12.455Z] ==25859==   total heap usage: 6,669,066 allocs, 4,702,593 frees, 27,236,559,016 bytes allocated
[2019-11-09T13:52:12.455Z] ==25859== 
[2019-11-09T13:52:12.455Z] ==25859== 5 bytes in 1 blocks are possibly lost in loss record 33 of 5,320
[2019-11-09T13:52:12.455Z] ==25859==    at 0x4C29BE3: malloc (vg_replace_malloc.c:299)
[2019-11-09T13:52:12.455Z] ==25859==    by 0x7737949: strdup (in /usr/lib64/libc-2.17.so)
[2019-11-09T13:52:12.455Z] ==25859==    by 0x7CF6444: __trans_list_add (in /usr/lib64/libnl-3.so.200.23.0)
[2019-11-09T13:52:12.455Z] ==25859==    by 0x7A8D810: ??? (in /usr/lib64/libnl-route-3.so.200.23.0)
[2019-11-09T13:52:12.455Z] ==25859==    by 0x400F502: _dl_init (in /usr/lib64/ld-2.17.so)
[2019-11-09T13:52:12.455Z] ==25859==    by 0x40011A9: ??? (in /usr/lib64/ld-2.17.so)
[2019-11-09T13:52:12.455Z] ==25859==    by 0x5: ???
[2019-11-09T13:52:12.455Z] ==25859==    by 0xFFEFFFAEA: ???
[2019-11-09T13:52:12.455Z] ==25859==    by 0xFFEFFFB25: ???
[2019-11-09T13:52:12.455Z] ==25859==    by 0xFFEFFFB36: ???
[2019-11-09T13:52:12.455Z] ==25859==    by 0xFFEFFFB39: ???
[2019-11-09T13:52:12.456Z] ==25859==    by 0xFFEFFFB3C: ???
[2019-11-09T13:52:12.456Z] ==25859==    by 0xFFEFFFB3F: ???
```

http://hpc-master.lab.mtl.com:8080/blue/organizations/jenkins/ucx/detail/ucx/2518/pipeline/113

**Comment by yosefe** [comment] 2019-11-10 08:51
potentially duplicate of #3769

**Comment by alinask** [comment] 2019-12-09 14:10
```
[2019-12-09T13:47:08.942Z] [----------] 1 test from tcp/uct_p2p_mix_test

[2019-12-09T13:47:08.942Z] [ RUN      ] tcp/uct_p2p_mix_test.mix_10000/0 <tcp/enp4s0>

[2019-12-09T14:02:15.594Z] /scrap/jenkins/workspace/ucx-3/contrib/../test/gtest/common/test_helpers.cc:49: Failure

[2019-12-09T14:02:15.594Z] Failed

[2019-12-09T14:02:15.594Z] Connection timed out - abort testing

[2019-12-09T14:02:15.594Z] [hpc-test-node-upstream-02:27269:0:27269] Caught signal 6 (Aborted: tkill(2) or tgkill(2))

[2019-12-09T14:04:06.979Z] ==== backtrace (tid:  27269) ====

[2019-12-09T14:04:06.979Z]  0 0x0000000000054548 ucs_debug_print_backtrace()  /scrap/jenkins/workspace/ucx-3/contrib/../src/ucs/debug/debug.c:625

[2019-12-09T14:04:06.979Z]  1 0x00000000000f8921 __epoll_wait_nocancel()  :0

[2019-12-09T14:04:06.979Z]  2 0x0000000000060fa3 ucs_event_set_wait()  /scrap/jenkins/workspace/ucx-3/contrib/../src/ucs/sys/event_set.c:196

[2019-12-09T14:04:06.979Z]  3 0x000000000001e2a4 uct_tcp_iface_progress()  /scrap/jenkins/workspace/ucx-3/contrib/../src/uct/tcp/tcp_iface.c:211

[2019-12-09T14:04:06.979Z]  4 0x0000000000666c9a uct_test::entity::flush()  /scrap/jenkins/workspace/ucx-3/contrib/../src/ucs/datastruct/callbackq.h:211

[2019-12-09T14:04:06.979Z]  5 0x0000000000630857 uct_p2p_mix_test::run()  /scrap/jenkins/workspace/ucx-3/contrib/../test/gtest/uct/test_p2p_mix.cc:159

[2019-12-09T14:04:06.979Z]  6 0x0000000000585fd6 ucs::test_base::run()  /scrap/jenkins/workspace/ucx-3/contrib/../test/gtest/common/test.cc:280

[2019-12-09T14:04:06.979Z]  7 0x000000000056d019 testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>()  /scrap/jenkins/workspace/ucx-3/contrib/../test/gtest/common/gtest-all.cc:3562

[2019-12-09T14:04:06.979Z]  8 0x000000000056125d testing::Test::Run()  /scrap/jenkins/workspace/ucx-3/contrib/../test/gtest/common/gtest-all.cc:3635

[2019-12-09T14:04:06.979Z]  9 0x0000000000561335 testing::TestInfo::Run()  /scrap/jenkins/workspace/ucx-3/contrib/../test/gtest/common/gtest-all.cc:3812

[2019-12-09T14:04:06.979Z] 10 0x000000000056149f testing::TestCase::Run()  /scrap/jenkins/workspace/ucx-3/contrib/../test/gtest/common/gtest-all.cc:3930

[2019-12-09T14:04:06.979Z] 11 0x0000000000565c4d testing::internal::UnitTestImpl::RunAllTests()  /scrap/jenkins/workspace/ucx-3/contrib/../test/gtest/common/gtest-all.cc:5808

[2019-12-09T14:04:06.979Z] 12 0x0000000000565f30 testing::internal::UnitTestImpl::RunAllTests()  /scrap/jenkins/workspace/ucx-3/contrib/../test/gtest/common/gtest-all.cc:5725

[2019-12-09T14:04:06.979Z] 13 0x0000000000505c98 main()  /scrap/jenkins/workspace/ucx-3/contrib/../test/gtest/common/gtest.h:20059

[2019-12-09T14:04:06.979Z] 14 0x0000000000021c05 __libc_start_main()  ???:0

[2019-12-09T14:04:06.979Z] 15 0x000000000054b5cf _start()  ???:0

[2019-12-09T14:04:06.979Z] =================================

http://hpc-master.lab.mtl.com:8080/blue/organizations/jenkins/ucx/detail/ucx/2985/pipeline/113
```

**Closed** 2019-12-12 14:44 UTC
Labels: Bug, Jenkins
