### ISSUE TITLE
UCX memory hooks cause bad performance for multithreaded apps

### ISSUE THREAD

**Issue by alexvm** [openucx/ucx#1047] opened 2016-10-09 10:38 UTC
Seems that there is contention when UCX performs memory related logic.
Setting UCX_MEM_MALLOC_HOOKS=no resolves the issue.
See gdb output:

```
(gdb) info threads
 Id   Target Id         Frame
  28   Thread 0x7f7191b9f700 (LWP 30411) "echo_server" 0x00007f7193f388ad in nanosleep () from /lib64/libc.so.6
  27   Thread 0x7f7191198700 (LWP 30412) "echo_server" 0x00007f7193f6bbb9 in syscall () from /lib64/libc.so.6
  26   Thread 0x7f7190997700 (LWP 30413) "echo_server" 0x00007f7193f56497 in sched_yield () from /lib64/libc.so.6
  25   Thread 0x7f718bfff700 (LWP 30414) "echo_server" 0x00007f7193f56497 in sched_yield () from /lib64/libc.so.6
  24   Thread 0x7f718b7fe700 (LWP 30415) "echo_server" 0x00007f7193f56497 in sched_yield () from /lib64/libc.so.6
  23   Thread 0x7f718affd700 (LWP 30416) "echo_server" pthread_acquire_lock (sl=0x7f7195c09e30 <_gm_+880>) at ptmalloc3/malloc.c:1568
  22   Thread 0x7f718a7fc700 (LWP 30417) "echo_server" pthread_acquire_lock (sl=0x7f7195c09e30 <_gm_+880>) at ptmalloc3/malloc.c:1568
  21   Thread 0x7f7189ffb700 (LWP 30418) "echo_server" pthread_acquire_lock (sl=0x7f7195c09e30 <_gm_+880>) at ptmalloc3/malloc.c:1568
  20   Thread 0x7f71897fa700 (LWP 30419) "echo_server" pthread_acquire_lock (sl=0x7f7195c09e30 <_gm_+880>) at ptmalloc3/malloc.c:1568
  19   Thread 0x7f7188ff9700 (LWP 30420) "echo_server" pthread_acquire_lock (sl=0x7f7195c09e30 <_gm_+880>) at ptmalloc3/malloc.c:1568
  18   Thread 0x7f7167fff700 (LWP 30421) "echo_server" pthread_acquire_lock (sl=0x7f7195c09e30 <_gm_+880>) at ptmalloc3/malloc.c:1568
  17   Thread 0x7f71677fe700 (LWP 30422) "echo_server" 0x00007f7193f719b3 in epoll_wait () from /lib64/libc.so.6
* 16   Thread 0x7f7164aa0700 (LWP 30423) "echo_server" pthread_acquire_lock (sl=0x7f7195c09e30 <_gm_+880>) at ptmalloc3/malloc.c:1568
  15   Thread 0x7f715ffff700 (LWP 30424) "echo_server" pthread_acquire_lock (sl=<optimized out>) at ptmalloc3/malloc.c:1568
  14   Thread 0x7f715f7fe700 (LWP 30425) "echo_server" pthread_acquire_lock (sl=<optimized out>) at ptmalloc3/malloc.c:1568
  13   Thread 0x7f715effd700 (LWP 30426) "echo_server" pthread_acquire_lock (sl=0x7f7195c09e30 <_gm_+880>) at ptmalloc3/malloc.c:1568
  12   Thread 0x7f715e7fc700 (LWP 30427) "echo_server" 0x00007f7193f56497 in sched_yield () from /lib64/libc.so.6
  11   Thread 0x7f715dffb700 (LWP 30428) "echo_server" pthread_acquire_lock (sl=0x7f7195c09e30 <_gm_+880>) at ptmalloc3/malloc.c:1568
  10   Thread 0x7f715d7fa700 (LWP 30429) "echo_server" pthread_acquire_lock (sl=<optimized out>) at ptmalloc3/malloc.c:1568
  9    Thread 0x7f715cff9700 (LWP 30430) "echo_server" pthread_acquire_lock (sl=0x7f7195c09e30 <_gm_+880>) at ptmalloc3/malloc.c:1568
  8    Thread 0x7f7157fff700 (LWP 30431) "echo_server" pthread_acquire_lock (sl=0x7f7195c09e30 <_gm_+880>) at ptmalloc3/malloc.c:1568
  7    Thread 0x7f71577fe700 (LWP 30432) "echo_server" pthread_acquire_lock (sl=0x7f7195c09e30 <_gm_+880>) at ptmalloc3/malloc.c:1568
  6    Thread 0x7f7156ffd700 (LWP 30433) "echo_server" pthread_acquire_lock (sl=0x7f7195c09e30 <_gm_+880>) at ptmalloc3/malloc.c:1568
  5    Thread 0x7f71567fc700 (LWP 30434) "echo_server" pthread_acquire_lock (sl=0x7f7195c09e30 <_gm_+880>) at ptmalloc3/malloc.c:1568
  4    Thread 0x7f7155ffb700 (LWP 30435) "echo_server" pthread_acquire_lock (sl=0x7f7195c09e30 <_gm_+880>) at ptmalloc3/malloc.c:1568
  3    Thread 0x7f71557fa700 (LWP 30436) "echo_server" internal_memalign (m=<optimized out>, bytes=<optimized out>, alignment=<optimized out>) at ptmalloc3/malloc.c:4291
  2    Thread 0x7f7154ff9700 (LWP 30437) "echo_server" pthread_acquire_lock (sl=0x7f7195c09e30 <_gm_+880>) at ptmalloc3/malloc.c:1568
  1    Thread 0x7f7196481b00 (LWP 30410) "echo_server" 0x00007f7193f388ad in nanosleep () from /lib64/libc.so.6
(gdb) thread 16
[Switching to thread 16 (Thread 0x7f7164aa0700 (LWP 30423))]
#1  ucm_dlfree (mem=0x309a8a0) at ptmalloc3/malloc.c:4586
4586        if (!PREACTION(fm)) {
(gdb) bt
#0  pthread_acquire_lock (sl=0x7f7195c09e30 <_gm_+880>) at ptmalloc3/malloc.c:1568
#1  ucm_dlfree (mem=0x309a8a0) at ptmalloc3/malloc.c:4586
.
.
.
(gdb) thread 22
[Switching to thread 22 (Thread 0x7f718a7fc700 (LWP 30417))]
#0  pthread_acquire_lock (sl=0x7f7195c09e30 <_gm_+880>) at ptmalloc3/malloc.c:1568
1568          if(!ret) {
(gdb) bt
#0  pthread_acquire_lock (sl=0x7f7195c09e30 <_gm_+880>) at ptmalloc3/malloc.c:1568
#1  ucm_dlmalloc (bytes=136) at ptmalloc3/malloc.c:4460
#2  0x00007f7195a035d2 in internal_memalign (m=<optimized out>, bytes=<optimized out>, alignment=<optimized out>) at ptmalloc3/malloc.c:4237
#3  ucm_dlmemalign (alignment=136, bytes=72) at ptmalloc3/malloc.c:4717
#4  0x00007f71959ff074 in ucm_malloc_impl (debug_name=0x7f7195a063ae "malloc", size=<optimized out>) at malloc/malloc_hook.c:222
#5  ucm_malloc (size=<optimized out>, caller=<optimized out>) at malloc/malloc_hook.c:263
#6  0x00007f71947b30cd in operator new(unsigned long) () from /lib64/libstdc++.so.6



```

**Comment by yosefe** [comment] 2016-10-09 10:52
probably need to replace ptmalloc2 by an allocator with TLS / fine-grained lock

**Comment by shamisp** [comment] 2016-10-09 14:47
Jemalloc ?

**Comment by shssf** [comment] 2016-10-09 14:52
@shamisp tcmalloc might be faster if threads aren't static (created/destructed). Currently I'm not sure that the problem is in xxmalloc. It might be relative one.

**Comment by shamisp** [comment] 2016-10-10 14:19
I'm concerned about the fact that UCX_MEM_MALLOC_HOOKS=no and we still get
into UCX malloc logic.

**Comment by shamisp** [comment] 2016-10-10 14:20
We should have a robust way fully disable this in runtime

**Comment by yosefe** [comment] 2016-10-10 14:35
@shamisp "I'm concerned about the fact that UCX_MEM_MALLOC_HOOKS=no and we still get
into UCX malloc logic."
Why do you think this is the case?

**Comment by shamisp** [comment] 2016-10-10 14:40
As I read it - this is what is stated in the original issue.

**Comment by yosefe** [comment] 2016-10-10 14:41
"Setting UCX_MEM_MALLOC_HOOKS=no resolves the issue."

**Comment by shamisp** [comment] 2016-10-10 14:44
oh, I didn't read it right.

**Comment by shssf** [comment] 2016-11-22 14:28
@alexvm Could you please check if last PR helps for this issue?

**Comment by yosefe** [comment] 2016-12-10 14:26
@alexvm closing this, pls reopen if needed

**Closed by yosefe** 2016-12-10 14:26 UTC
Labels: optimization
