### ISSUE TITLE
[mtt] timeout exceeded in MPI_Alltoallv_f

### ISSUE THREAD

**Issue by amaslenn** [openucx/ucx#3485] opened 2019-04-15 07:52 UTC
Configuration
```
MOFED: MLNX_OFED_LINUX-4.5-1.0.1.0
OMPI: 4.0.2a1
Job: ucx-roce
Nodes: jazz x2 (ppn=28(x2), nodelist=jazz[17,32])
```

MTT log: http://hpcweb.lab.mtl.com/hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20190410_183023_60980_19987_jazz17/html/test_stdout_Xnir8E.txt

The issue looks unstable, able to reproduce only in a loop (~10 iterations).

Cmd:
`mpirun -np 56 --display-map -mca btl self --tag-output --timestamp-output -mca pml ucx -mca coll '^hcoll' --bind-to core -x UCX_NET_DEVICES=mlx5_3:1 -mca osc ucx -x UCX_IB_REG_METHODS=rcache,direct -x UCX_TLS=dc_x,self,sm -mca pmix_base_async_modex 1 -mca mpi_add_procs_cutoff 0 -mca pmix_base_collect_data 0 --map-by node /hpc/local/benchmarks/hpcx_install_2019-04-10/mtt-tests-gcc/installs/YVKj/tests/intel/intel_tests/src/MPI_Alltoallv_f`

Output:
```sh
Wed Apr 10 21:35:21 2019[1,0]<stdout>: MPITEST_INFO (         0): Starting test MPI_Alltoallv()          
Wed Apr 10 21:35:21 2019[1,0]<stdout>: MPITEST_INFO (         0): MPITEST_BYTE_TO_ELEMENT(): Byte length          8 does not divide evenly by type         9 Using          0 elements
Wed Apr 10 21:35:21 2019[1,0]<stdout>: MPITEST_INFO (         0): MPITEST_BYTE_TO_ELEMENT(): Byte length       1016 does not divide evenly by type         9 Using         63 elements
Wed Apr 10 21:35:21 2019[1,0]<stdout>: MPITEST_INFO (         0): MPITEST_BYTE_TO_ELEMENT(): Byte length       1032 does not divide evenly by type         9 Using         64 elements
Wed Apr 10 21:35:21 2019[1,0]<stdout>: MPITEST_INFO (         0): MPITEST_BYTE_TO_ELEMENT(): Byte length          8 does not divide evenly by type         9 Using          0 elements
Wed Apr 10 21:35:21 2019[1,0]<stdout>: MPITEST_INFO (         0): MPITEST_BYTE_TO_ELEMENT(): Byte length       1016 does not divide evenly by type         9 Using         63 elements
Wed Apr 10 21:35:21 2019[1,0]<stdout>: MPITEST_INFO (         0): MPITEST_BYTE_TO_ELEMENT(): Byte length       1032 does not divide evenly by type         9 Using         64 elementsWed Apr 10 21:35:21 2019[1,0]<stdout>: MPITEST_INFO (         0): MPITEST_BYTE_TO_ELEMENT(): Byte length          8 does not divide evenly by type         9 Using          0 elements
Wed Apr 10 21:35:21 2019[1,0]<stdout>: MPITEST_INFO (         0): MPITEST_BYTE_TO_ELEMENT(): Byte length       1016 does not divide evenly by type         9 Using         63 elements
Wed Apr 10 21:35:21 2019[1,0]<stdout>: MPITEST_INFO (         0): MPITEST_BYTE_TO_ELEMENT(): Byte length       1032 does not divide evenly by type         9 Using         64 elementsWed Apr 10 21:35:21 2019[1,0]<stdout>: MPITEST_INFO (         0): MPITEST_BYTE_TO_ELEMENT(): Byte length          8 does not divide evenly by type         9 Using          0 elements
Wed Apr 10 21:35:21 2019[1,0]<stdout>: MPITEST_INFO (         0): MPITEST_BYTE_TO_ELEMENT(): Byte length       1016 does not divide evenly by type         9 Using         63 elements
Wed Apr 10 21:35:21 2019[1,0]<stdout>: MPITEST_INFO (         0): MPITEST_BYTE_TO_ELEMENT(): Byte length       1032 does not divide evenly by type         9 Using         64 elements
Wed Apr 10 21:35:21 2019[1,0]<stdout>: MPITEST_INFO (         0): MPITEST_BYTE_TO_ELEMENT(): Byte length          8 does not divide evenly by type         9 Using          0 elements
Wed Apr 10 21:35:21 2019[1,0]<stdout>: MPITEST_INFO (         0): MPITEST_BYTE_TO_ELEMENT(): Byte length       1016 does not divide evenly by type         9 Using         63 elements
Wed Apr 10 21:35:21 2019[1,0]<stdout>: MPITEST_INFO (         0): MPITEST_BYTE_TO_ELEMENT(): Byte length       1032 does not divide evenly by type         9 Using         64 elements
node=jazz17, pid=155747:
Thread 4 (Thread 0x7fac91aeb700 (LWP 155772)):
#0  0x00007fac94b28923 in epoll_wait () from /usr/lib64/libc.so.6
#1  0x00007fac944e6eb3 in epoll_dispatch (base=0x865750, tv=<optimized out>) at epoll.c:407
#2  0x00007fac944ea900 in opal_libevent2022_event_base_loop (base=0x865750, flags=flags@entry=1) at event.c:1630
#3  0x00007fac944a5f5e in progress_engine (obj=<optimized out>) at runtime/opal_progress_threads.c:105
#4  0x00007fac94dfae25 in start_thread () from /usr/lib64/libpthread.so.0
#5  0x00007fac94b2834d in clone () from /usr/lib64/libc.so.6
Thread 3 (Thread 0x7fac8eb04700 (LWP 155797)):
#0  0x00007fac94b28923 in epoll_wait () from /usr/lib64/libc.so.6
#1  0x00007fac944e6eb3 in epoll_dispatch (base=0x8bf910, tv=<optimized out>) at epoll.c:407
#2  0x00007fac944ea900 in opal_libevent2022_event_base_loop (base=0x8bf910, flags=flags@entry=1) at event.c:1630
#3  0x00007fac90a308ee in progress_engine (obj=<optimized out>) at runtime/pmix_progress_threads.c:109
#4  0x00007fac94dfae25 in start_thread () from /usr/lib64/libpthread.so.0
#5  0x00007fac94b2834d in clone () from /usr/lib64/libc.so.6
Thread 2 (Thread 0x7fac7d9fe700 (LWP 155903)):
#0  0x00007fac94b28923 in epoll_wait () from /usr/lib64/libc.so.6
#1  0x00007fac876867ec in ucs_async_thread_func (arg=0x97d260) at async/thread.c:93
#2  0x00007fac94dfae25 in start_thread () from /usr/lib64/libpthread.so.0
#3  0x00007fac94b2834d in clone () from /usr/lib64/libc.so.6
Thread 1 (Thread 0x7fac963a7740 (LWP 155747)):
#0  0x00007fac879a16d7 in uct_mm_iface_poll_fifo (iface=0x97d470) at sm/mm/base/mm_iface.c:233
#1  uct_mm_iface_progress (arg=0x97d470) at sm/mm/base/mm_iface.c:263
#2  0x00007fac87bcb0a2 in ucs_callbackq_dispatch (cbq=<optimized out>) at /hpc/local/benchmarks/hpcx_install_2019-04-10/src/hpcx-gcc-redhat7.4/ucx-v1.6.x/src/ucs/datastruct/callbackq.h:211
#3  uct_worker_progress (worker=<optimized out>) at /hpc/local/benchmarks/hpcx_install_2019-04-10/src/hpcx-gcc-redhat7.4/ucx-v1.6.x/src/uct/api/uct.h:1806
#4  ucp_worker_progress (worker=0x7fac962fc010) at core/ucp_worker.c:1632
#5  0x00007fac8c0ca767 in mca_pml_ucx_progress () at pml_ucx.c:510
#6  0x00007fac944a00dc in opal_progress () at runtime/opal_progress.c:231
#7  0x00007fac954ac945 in ompi_request_wait_completion (req=0xa06a28) at ../ompi/request/request.h:415
#8  ompi_request_default_wait (req_ptr=0x7ffe6e1c5aa0, status=0x7ffe6e1c5ab0) at request/req_wait.c:42
#9  0x00007fac954e71e9 in ompi_coll_base_sendrecv_actual (sendbuf=0x61dfc9 <send_buffer.2004+489>, scount=80, sdatatype=sdatatype@entry=0x7fac957358e0 <ompi_mpi_integer1>, dest=6, stag=stag@entry=-14, recvbuf=<optimized out>, rcount=80, rdatatype=rdatatype@entry=0x7fac957358e0 <ompi_mpi_integer1>, source=source@entry=11, rtag=rtag@entry=-14, comm=comm@entry=0x9f23b0, status=status@entry=0x0) at base/coll_base_util.c:59
#10 0x00007fac954ec913 in ompi_coll_base_sendrecv (stag=-14, rtag=-14, status=0x0, myid=18, comm=0x9f23b0, source=11, rdatatype=0x7fac957358e0 <ompi_mpi_integer1>, rcount=<optimized out>, recvbuf=<optimized out>, dest=6, sdatatype=0x7fac957358e0 <ompi_mpi_integer1>, scount=<optimized out>, sendbuf=<optimized out>) at base/coll_base_util.h:67
#11 ompi_coll_base_alltoallv_intra_pairwise (sbuf=0x61dde0 <send_buffer.2004>, scounts=0x7ffe6e1c6920, sdisps=0x7ffe6e1c6720, sdtype=0x7fac957358e0 <ompi_mpi_integer1>, rbuf=0x63ede0 <recv_buffer.1997>, rcounts=0x7ffe6e1c6d20, rdisps=0x7ffe6e1c6b20, rdtype=0x7fac957358e0 <ompi_mpi_integer1>, comm=0x9f23b0, module=0xa0d4d0) at base/coll_base_alltoallv.c:162
#12 0x00007fac954bf2c1 in PMPI_Alltoallv (sendbuf=sendbuf@entry=0x61dde0 <send_buffer.2004>, sendcounts=sendcounts@entry=0x7ffe6e1c6920, sdispls=sdispls@entry=0x7ffe6e1c6720, sendtype=sendtype@entry=0x7fac957358e0 <ompi_mpi_integer1>, recvbuf=<optimized out>, recvcounts=recvcounts@entry=0x7ffe6e1c6d20, rdispls=rdispls@entry=0x7ffe6e1c6b20, recvtype=recvtype@entry=0x7fac957358e0 <ompi_mpi_integer1>, comm=comm@entry=0x9f23b0) at palltoallv.c:129
#13 0x00007fac957970c8 in ompi_alltoallv_f (sendbuf=0x61dde0 <send_buffer.2004> '\022' <repeats 80 times>, "\032", '\023' <repeats 81 times>, "#", '\024' <repeats 37 times>..., sendcounts=0x7ffe6e1c6920, sdispls=0x7ffe6e1c6720, sendtype=<optimized out>, recvbuf=<optimized out>, recvcounts=0x7ffe6e1c6d20, rdispls=0x7ffe6e1c6b20, recvtype=0x61d3c0 <mpit_+576>, comm=0x7ffe6e1c7178, ierr=0x7ffe6e1c7150) at palltoallv_f.c:97
#14 0x0000000000402006 in MAIN__ () at MPI_Alltoallv_f.F:261
```

**Comment by brminich** [comment] 2019-04-18 18:10
Reproduced, duplicate of #2934 

```
----------
function #1:
number of qps 274
qp: 0x23b22 - Not OK - diff=2, diff type: CI   (SXDC vs. SQPC.CI)
```

**Closed by brminich** 2019-04-18 18:10 UTC
Labels: Bug, MTT
