### ISSUE TITLE
[mtt] transport retry count exceeded on (synd 0x15 vend 0x81 hw_synd 0/0)

### ISSUE THREAD

**Issue by amaslenn** [openucx/ucx#4184] opened 2019-09-11 14:25 UTC
```
OMPI: 4.0.2rc1
MOFED: MLNX_OFED_LINUX-4.6-1.0.1.1
Module: hpcx-gcc (2019-09-07)
Test module: none
Nodes: orion x24 (ppn=28(x24), nodelist=clx-orion-[031-032,049-054,056-064,075-081])
```

MTT log: http://e2e-gw.mellanox.com:4080/hpc/scrap/users/mtt/scratch/shmem/20190908_022600_5788_455545_clx-orion-031/html/test_stdout_LceVNV.txt

Cmd:
`oshrun -np 672 --display-map --bind-to core -mca oshmem_proc_group_cache_size 10000 -mca sshmem ucx -mca atomic ucx -mca coll_hcoll_enable 1 -x HCOLL_POLLING_LEVEL=1 -x HCOLL_ENABLE_MCAST_ALL=0 -x HCOLL_BCOL=basesmuma,ucx_p2p -x HCOLL_SBGP=basesmsocket,p2p -mca spml ucx -mca pml ucx -x UCX_TLS=dc_x,self,sm -x UCX_DC_MLX5_TX_POLICY=rand -x UCX_NET_DEVICES=mlx5_0:1 -x UCX_UNIFIED_MODE=y --map-by slot -x SHMEM_SYMMETRIC_HEAP_SIZE=128M /hpc/scrap/users/mtt/scratch/shmem/20190908_022600_5788_455545_clx-orion-031/installs/9bQp/tests/verifier/tests-mellanox.git/verifier/install/bin/oshmem_test exec --no-colour --task=analysis:tc2 --task=analysis:tc3 --task=analysis:tc4 --task=analysis:tc5 --duration 10`

Output:
```sh
Reduce performance: 
duration = 10 
     msize       op/sec     wall sec        yield /PE  yield aggregate 
      8  B    5.730e-05    5.730e-04    136.34 KB/sec     89.34 MB/sec
     16  B    2.380e-05    2.380e-04    656.51 KB/sec    430.20 MB/sec
     32  B    2.310e-05    2.310e-04      1.32 MB/sec    886.46 MB/sec
     64  B    2.600e-05    2.600e-04      2.35 MB/sec      1.54 GB/sec
    128  B    2.740e-05    2.740e-04      4.46 MB/sec      2.92 GB/sec
    256  B    3.409e-04    3.409e-03    733.35 KB/sec    480.55 MB/sec
    512  B    3.250e-05    3.250e-04     15.02 MB/sec      9.84 GB/sec
      1 KB    3.390e-05    3.390e-04     28.81 MB/sec     18.88 GB/sec
      2 KB    4.290e-05    4.290e-04     45.53 MB/sec     29.83 GB/sec      4 KB    7.765e-04    7.765e-03      5.03 MB/sec      3.30 GB/sec
PASS   analysis   reduce         Reduce performance.
[clx-orion-059:19430:0:19430] ib_mlx5_log.c:139  Transport retry count exceeded on mlx5_0:1/IB (synd 0x15 vend 0x81 hw_synd 0/0)
[clx-orion-059:19430:0:19430] ib_mlx5_log.c:139  DCI QP 0x1ac8c wqe[362]: RDMA_WRITE s-- [rqpn 0x1cf57 rlid 187] [rva 0xff440b98 rkey 0x4e94b] [inl len 8]
[clx-orion-059:19422:0:19422] ib_mlx5_log.c:139  Transport retry count exceeded on mlx5_0:1/IB (synd 0x15 vend 0x81 hw_synd 0/0)
[clx-orion-059:19422:0:19422] ib_mlx5_log.c:139  DCI QP 0x1ac8b wqe[18]: RDMA_WRITE s-- [rqpn 0x1cf19 rlid 187] [rva 0xff414158 rkey 0x4849f] [inl len 8]
[clx-orion-059:19441:0:19441] ib_mlx5_log.c:139  Transport retry count exceeded on mlx5_0:1/IB (synd 0x15 vend 0x81 hw_synd 0/0)
[clx-orion-059:19441:0:19441] ib_mlx5_log.c:139  DCI QP 0x1ac8d wqe[152]: RDMA_WRITE s-- [rqpn 0x1cf19 rlid 187] [rva 0xff438df0 rkey 0x4849f] [inl len 8]
[clx-orion-059:19436:0:19436] ib_mlx5_log.c:139  Transport retry count exceeded on mlx5_0:1/IB (synd 0x15 vend 0x81 hw_synd 0/0)
[clx-orion-059:19436:0:19436] ib_mlx5_log.c:139  DCI QP 0x1ac8e wqe[479]: RDMA_WRITE s-- [rqpn 0x1cf63 rlid 187] [rva 0xff4696c8 rkey 0x4ef5a] [inl len 8]
[clx-orion-059:19429:0:19429] ib_mlx5_log.c:139  Transport retry count exceeded on mlx5_0:1/IB (synd 0x15 vend 0x81 hw_synd 0/0)
```

**Comment by brminich** [comment] 2019-09-13 14:58
Did not manage to reproduce but looks very similar to #3305 
https://redmine.mellanox.com/issues/1706553 (mlnx internal link)

This issue was seen on both IB and RoCE. It is not fixed yet

**Comment by brminich** [comment] 2019-09-13 14:58
duplicate of #3305

**Closed** 2019-09-13 14:59 UTC
Labels: Bug, Duplicate, External, MTT
