### ISSUE TITLE
hang on ud on gatherv (msg size = 4M)

### ISSUE THREAD

**Issue by alinask** [openucx/ucx#955] opened 2016-09-08 08:18 UTC
There is a hang on the imb (and imb_datacheck) test when running with ud, roce and a message of 4MB.

- Hangs on 4 nodes with ppn=8 (np=32).
- Smaller messages work fine.
- The hang happens even on 1 iteration.
- Works with an IB port on a small scale.
- Happens without rndv as well.
- Works with pml yalla.

To reproduce:

/hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20160907_203028_13244_100793_boo11/installs/Fw1N/install/bin/mpirun -np 32 -mca btl_openib_warn_default_gid_prefix 0 --bind-to core --display-map -mca pml ucx  -x UCX_RNDV_THRESH=41943040 -x UCX_NET_DEVICES=mlx4_0:2  -mca coll_hcoll_enable 0 -x UCX_TLS=ud  --map-by node /hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20160907_203028_13244_100793_boo11/installs/Fw1N/tests/imb/IMB.git/src/IMB-MPI1 -npmin 32 -iter 1 -mem 0.9 gatherv -msglen msg_4m

```
$cat msg_4m
4194304
```

When running with logging (UCX_LOG_LEVEL=debug) the following comments are printed many times during the hang:
```
[1473321621.823566] [boo13:17932:1]          ud_ep.c:817  UCX  DEBUG ep(0x781be0): resending rt_psn 2669 rt_max_psn 2767 acked_psn 2664 max_psn 2670 ack_req 0
[1473321621.823570] [boo13:17932:1]          ud_ep.c:774  UCX  DEBUG ep(0x781be0): out of window(psn=2670/max_psn=2670) - can not resend more
[1473321621.815473] [boo12:19275:1]          ud_ep.c:68   UCX  DEBUG ep: 0x7819c0 ca drop@cwnd = 13 in flight: 109
```

**Comment by alinask** [comment] 2016-09-11 11:09
Reproduces on a large scale (np=896) with IB as well - gatherv with a message of 524288B

http://e2e-gw.mellanox.com:4080/hpc/scrap/users/mtt/scratch/ucx_ompi/20160908_190648_7660_42336_clx-orion-020/html/test_stdout_usbtUu.txt

**Comment by yosefe** [comment] 2016-09-14 08:48
duplicate of #843

**Closed by yosefe** 2016-09-14 08:48 UTC
Labels: bug
