### ISSUE TITLE
[mtt] hang in ctxalloc

### ISSUE THREAD

**Issue by amaslenn** [openucx/ucx#4323] opened 2019-10-23 12:17 UTC
Configuration
```
OMPI: 4.0.2rc3
MOFED: MLNX_OFED_LINUX-4.6-1.0.1.1
Module: hpcx-armcc (2019-10-22)
Test module: mtt-tests/hpcx-armcc
Nodes: hp-arm x3 (ppn=224(x3), nodelist=hpc-arm-hp[01-03])
```

MTT log: http://hpcweb.lab.mtl.com/hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20191022_184249_74836_10464_hpc-arm-hp01/html/test_stdout_f34QOO.txt

Cmd:
`mpirun -np 168 --display-map -mca btl self --tag-output --timestamp-output -mca pml ucx -mca coll '^hcoll' -x UCX_ERROR_SIGNALS=SIGILL,SIGSEGV,SIGBUS,SIGFPE,SIGABRT -x UCX_HANDLE_ERRORS=bt --bind-to hwthread -x UCX_NET_DEVICES=mlx5_0:1,mlx5_3:1 -mca osc ucx -x UCX_IB_ADDR_TYPE=ib_global -x UCX_IB_REG_METHODS=rcache,direct -x UCX_UD_TIMEOUT=10m -mca pmix_base_async_modex 0 -mca mpi_add_procs_cutoff 100000 -mca pmix_base_collect_data 1 --map-by node /hpc/local/benchmarks/daily/next/2019-10-22/mtt-tests-armcc/installs/QhED/tests/mpi-small-tests/mtt-tests.git/mpi-small-tests/misc/ctxalloc 2 1500 100`

All processes reported complition:
```sh
...
Tue Oct 22 21:14:09 2019[1,0]<stdout>:round 0 completed
Tue Oct 22 21:14:11 2019[1,1]<stdout>:round 0 completed
...
```
But the mpirun process didn't finish.

**Comment by yosefe** [comment] 2019-10-24 11:52
duplicate of https://redmine.mellanox.com/issues/1608258 (Mellanox internal link)

**Comment by shamisp** [comment] 2019-10-24 13:45
@yosefe do you see the same problem with clang ?

**Comment by yosefe** [comment] 2019-10-24 13:47
it's not related to compiler
its rh 7.6 bug in rhashtable rht_deferred_worker kworker taking 100% cpu

**Comment by shamisp** [comment] 2019-10-24 14:22
Ah, let's remove Armcc from the title, otherwise it is confusing.

**Comment by yosefe** [comment] 2020-01-26 11:08
doesnt hang after patching th ekernel

**Closed by yosefe** 2020-01-26 11:08 UTC
Labels: Bug, External, MTT
