### ISSUE TITLE
[mtt][ucx-emulation] Fail on oshmem_test

### ISSUE THREAD

**Issue by avildema** [openucx/ucx#6808] opened 2021-05-14 11:15 UTC
Configuration
```
OMPI: 4.1.1rc1
MOFED: MLNX_OFED_LINUX-5.2-2.2.0.0
Module: hpcx-gcc (2021-05-13)
Test module: none
Nodes: hp-arm x2 (ppn=224(x2), nodelist=hpc-arm-hp[02-03])
```
 
MTT log:
http://hpcweb.lab.mtl.com/hpc/mtr_scrap/users/mtt/scratch/shmem/20210513_125821_14623_11734_hpc-arm-hp02/html/test_stdout_n3eIGU.txt
 
Cmd:
`/hpc/local/benchmarks/daily/next/2021-05-13/hpcx-gcc-redhat7.6/ompi/bin/oshrun -np 224 --display-map --bind-to hwthread -mca oshmem_proc_group_cache_size 10000 -mca sshmem ucx -mca atomic ucx -mca coll '^hcoll' -mca coll_hcoll_enable 0 -mca spml ucx -mca pml ucx -x UCX_HANDLE_ERRORS=bt -x UCX_TLS=ud_x -x UCX_UD_TIMEOUT=10m -x UCX_NET_DEVICES=mlx5_0:1,mlx5_3:1 -x UCX_UNIFIED_MODE=y --map-by node -x SHMEM_SYMMETRIC_HEAP_SIZE=710M /hpc/mtr_scrap/users/mtt/scratch/shmem/20210513_125821_14623_11734_hpc-arm-hp02/installs/HtvW/tests/verifier/tests-mellanox.git/verifier/install/bin/oshmem_test exec --no-colour --task=data`
 
Output:
```sh
[hpc-arm-hp02:16060:async:16475] ib_mlx5_log.c:147  Local QP operation on mlx5_0:1/IB (synd 0x2 vend 0x11 hw_synd 0/1)
[hpc-arm-hp02:16060:async:16475] ib_mlx5_log.c:147  UD QP 0x1000a wqe[39626]: opcode RECV[hpc-arm-hp02:16039:async:16487] ib_mlx5_log.c:147  Local QP operation on mlx5_0:1/IB (synd 0x2 vend 0x60 hw_synd 0/0)
[hpc-arm-hp02:16039:async:16487] ib_mlx5_log.c:147  UD QP 0x1000b wqe[867]: SEND s-e [rqpn 0x1122 rlid 31] [inl len 8] [va 0xffff9bfde7d8 len 8 lkey 0xbf8e7]==== backtrace (tid:  16475) ====
 0 0x000000000005577c ucs_log_print()  /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/ucs/debug/log.c:219
 1 0x0000000000023040 uct_ib_mlx5_completion_with_err()  /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/uct/ib/mlx5/ib_mlx5_log.c:140 2 0x0000000000055d3c uct_ib_mlx5_poll_cq()  /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/uct/ib/mlx5/ib_mlx5.inl:81
 3 0x0000000000055d3c uct_ud_mlx5_iface_async_progress()  /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/uct/ib/ud/accel/ud_mlx5.c:578
 4 0x000000000004c438 uct_ud_iface_async_progress()  /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/uct/ib/ud/base/ud_iface.c:229
 5 0x000000000004c438 uct_ud_iface_async_handler()  /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/uct/ib/ud/base/ud_iface.c:240
 6 0x0000000000040410 ucs_async_handler_invoke()  /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/ucs/async/async.c:249
 7 0x0000000000040410 ucs_async_handler_dispatch()  /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/ucs/async/async.c:271
 8 0x0000000000040410 ucs_async_dispatch_handlers()  /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/ucs/async/async.c:303
 9 0x00000000000430c0 ucs_async_thread_ev_handler()  /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/ucs/async/thread.c:87
10 0x0000000000059ccc ucs_event_set_wait()  /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/ucs/sys/event_set.c:215
11 0x00000000000433b4 ucs_async_thread_func()  /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/ucs/async/thread.c:130
12 0x0000000000007c48 start_thread()  :0
13 0x00000000000df600 thread_start()  :0
=================================
[hpc-arm-hp02:16060] *** Process received signal ***
[hpc-arm-hp02:16060] Signal: Aborted (6)
[hpc-arm-hp02:16060] Signal code:  (-6)
[hpc-arm-hp02:16060] [ 0] [0xffff89a9066c]
[hpc-arm-hp02:16060] [ 1] /lib64/libc.so.6(gsignal+0x4c)[0xffff893750e8]
[hpc-arm-hp02:16060] [ 2] /lib64/libc.so.6(abort+0x11c)[0xffff89376760]
[hpc-arm-hp02:16060] [ 3] /hpc/local/benchmarks/daily/next/2021-05-13/hpcx-gcc-redhat7.6/ucx/lib/libucs.so.0(ucs_fatal_error_message+0x58)[0xffff86c30f94]
[hpc-arm-hp02:16060] [ 4] /hpc/local/benchmarks/daily/next/2021-05-13/hpcx-gcc-redhat7.6/ucx/lib/libucs.so.0(ucs_log_default_handler+0x450)[0xffff86c3577c]
[hpc-arm-hp02:16060] [ 5] /hpc/local/benchmarks/daily/next/2021-05-13/hpcx-gcc-redhat7.6/ucx/lib/libucs.so.0(ucs_log_dispatch+0xf0)[0xffff86c35974]
[hpc-arm-hp02:16060] [ 6] /hpc/local/benchmarks/daily/next/2021-05-13/hpcx-gcc-redhat7.6/ucx/lib/ucx/libuct_ib.so.0(uct_ib_mlx5_completion_with_err+0x3cc)[0xffff86ad3040]
[hpc-arm-hp02:16060] [ 7] /hpc/local/benchmarks/daily/next/2021-05-13/hpcx-gcc-redhat7.6/ucx/lib/ucx/libuct_ib.so.0(+0x55d3c)[0xffff86b05d3c]
[hpc-arm-hp02:16060] [ 8] /hpc/local/benchmarks/daily/next/2021-05-13/hpcx-gcc-redhat7.6/ucx/lib/ucx/libuct_ib.so.0(+0x4c438)[0xffff86afc438]
[hpc-arm-hp02:16060] [ 9] /hpc/local/benchmarks/daily/next/2021-05-13/hpcx-gcc-redhat7.6/ucx/lib/libucs.so.0(ucs_async_dispatch_handlers+0xb8)[0xffff86c20410]
[hpc-arm-hp02:16060] [10] /hpc/local/benchmarks/daily/next/2021-05-13/hpcx-gcc-redhat7.6/ucx/lib/libucs.so.0(+0x430c0)[0xffff86c230c0]
[hpc-arm-hp02:16060] [11] /hpc/local/benchmarks/daily/next/2021-05-13/hpcx-gcc-redhat7.6/ucx/lib/libucs.so.0(ucs_event_set_wait+0xa0)[0xffff86c39ccc]
[hpc-arm-hp02:16060] [12] /hpc/local/benchmarks/daily/next/2021-05-13/hpcx-gcc-redhat7.6/ucx/lib/libucs.so.0(+0x433b4)[0xffff86c233b4]
[hpc-arm-hp02:16060] [13] /lib64/libpthread.so.0(+0x7c48)[0xffff894d7c48]
[hpc-arm-hp02:16060] [14] /lib64/libc.so.6(+0xdf600)[0xffff8941f600]
[hpc-arm-hp02:16060] *** End of error message ***--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
```

**Comment by yosefe** [comment] 2021-10-31 16:20
seems similar to #7595

**Comment by rakhmets** [comment] 2022-02-03 11:09
The issue is fixed in frames of another issue. Here is a link to the corresponding issue: https://redmine.mellanox.com/issues/2865981 (NVIDIA internal link).

**Closed by rakhmets** 2022-02-03 11:09 UTC
Labels: Bug, MTT
