### ISSUE TITLE
[mtt] ud_ep.c:270  Fatal: UD endpoint 0x973660 to jazz25:70567: unhandled timeout error

### ISSUE THREAD

**Issue by avildema** [openucx/ucx#6679] opened 2021-04-20 08:06 UTC
Configuration
```
OMPI: 4.1.1rc1
MOFED: MLNX_OFED_LINUX-5.1-2.5.8.0
Module: hpcx-gcc-debug (2021-04-19)
Test module: mtt-tests/hpcx-gcc
Nodes: jazz x2 (ppn=28(x2), nodelist=jazz[24-25])
```
 
MTT log:
http://hpcweb.lab.mtl.com/hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20210420_002601_55154_7291_jazz24.swx.labs.mlnx/html/test_stdout_0mN_d5.txt
 
Cmd:
`/hpc/local/benchmarks/daily/next/2021-04-19/hpcx-gcc-redhat7.6/ompi/bin/mpirun -np 56 --display-map -mca btl self --tag-output --timestamp-output -mca pml ucx -mca coll '^hcoll' -x UCX_ERROR_SIGNALS=SIGILL,SIGSEGV,SIGBUS,SIGFPE,SIGABRT -x UCX_HANDLE_ERRORS=bt -x UCX_IB_PCI_RELAXED_ORDERING=off --bind-to socket -x UCX_NET_DEVICES=mlx5_3:1 -mca osc ucx -x UCX_IB_REG_METHODS=rcache,direct -x UCX_TLS=ud_x,self,sm -x UCX_UD_TIMEOUT=10m -mca pmix_base_async_modex 0 -mca mpi_add_procs_cutoff 100000 -mca pmix_base_collect_data 1 --map-by node /hpc/local/benchmarks/daily/next/2021-04-19/mtt-tests-gcc/installs/DqAE/tests/mpi-small-tests/mtt-tests.git/mpi-small-tests/misc/mpiring`
 
Output:
```sh

Tue Apr 20 06:14:31 2021[1,36]<stderr>:[jazz24:140516] *** Process received signal ***
Tue Apr 20 06:14:31 2021[1,36]<stderr>:[jazz24:140516] Signal: Aborted (6)
Tue Apr 20 06:14:31 2021[1,36]<stderr>:[jazz24:140516] Signal code:  (-6)Tue Apr 20 06:14:31 2021[1,36]<stderr>:[jazz24:140516] [ 0] Tue Apr 20 06:14:31 2021[1,36]<stderr>:/lib64/libpthread.so.0(+0xf5d0)[0x7f40e9f5c5d0]
Tue Apr 20 06:14:31 2021[1,36]<stderr>:[jazz24:140516] [ 1] Tue Apr 20 06:14:31 2021[1,36]<stderr>:/lib64/libc.so.6(gsignal+0x37)[0x7f40e9bb6207]
Tue Apr 20 06:14:31 2021[1,36]<stderr>:[jazz24:140516] [ 2] Tue Apr 20 06:14:31 2021[1,36]<stderr>:/lib64/libc.so.6(abort+0x148)[0x7f40e9bb78f8]
Tue Apr 20 06:14:31 2021[1,36]<stderr>:[jazz24:140516] [ 3] Tue Apr 20 06:14:31 2021[1,36]<stderr>:/hpc/local/benchmarks/daily/next/2021-04-19/hpcx-gcc-redhat7.6/ucx/debug/lib/libucs.so.0(ucs_fatal_error_message+0x5d)[0x7f40dba8ac6d]
Tue Apr 20 06:14:31 2021[1,36]<stderr>:[jazz24:140516] [ 4] Tue Apr 20 06:14:31 2021[1,36]<stderr>:/hpc/local/benchmarks/daily/next/2021-04-19/hpcx-gcc-redhat7.6/ucx/debug/lib/libucs.so.0(ucs_fatal_error_format+0xd6)[0x7f40dba8adf6]
Tue Apr 20 06:14:31 2021[1,36]<stderr>:[jazz24:140516] [ 5] Tue Apr 20 06:14:31 2021[1,36]<stderr>:/hpc/local/benchmarks/daily/next/2021-04-19/hpcx-gcc-redhat7.6/ucx/debug/lib/ucx/libuct_ib.so.0(+0x81801)[0x7f40db3ce801]
Tue Apr 20 06:14:31 2021[1,36]<stderr>:[jazz24:140516] [ 6] Tue Apr 20 06:14:31 2021[1,36]<stderr>:/hpc/local/benchmarks/daily/next/2021-04-19/hpcx-gcc-redhat7.6/ucx/debug/lib/libucs.so.0(+0x53c4b)[0x7f40dba80c4b]
Tue Apr 20 06:14:31 2021[1,36]<stderr>:[jazz24:140516] [ 7] Tue Apr 20 06:14:31 2021[1,36]<stderr>:/hpc/local/benchmarks/daily/next/2021-04-19/hpcx-gcc-redhat7.6/ucx/debug/lib/libucp.so.0(ucp_worker_progress+0x6a)[0x7f40e00dc06a]
Tue Apr 20 06:14:31 2021[1,36]<stderr>:[jazz24:140516] [ 8] Tue Apr 20 06:14:31 2021[1,36]<stderr>:/hpc/local/benchmarks/daily/next/2021-04-19/hpcx-gcc-redhat7.6/ompi/lib/libopen-pal.so.40(opal_progress+0x2c)[0x7f40e93ed5dc]
Tue Apr 20 06:14:31 2021[1,36]<stderr>:[jazz24:140516] [ 9] Tue Apr 20 06:14:31 2021[1,36]<stderr>:/hpc/local/benchmarks/daily/next/2021-04-19/hpcx-gcc-redhat7.6/ompi/lib/libmpi.so.40(ompi_request_default_wait+0x125)[0x7f40ea1b60d5]
Tue Apr 20 06:14:31 2021[1,36]<stderr>:[jazz24:140516] [10] Tue Apr 20 06:14:31 2021[1,24]<stderr>:==== backtrace (tid: 140502) ====
Tue Apr 20 06:14:31 2021[1,24]<stderr>: 0 0x0000000000081801 uct_ud_ep_deferred_timeout_handler()  /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/uct/ib/ud/base/ud_ep.c:268
Tue Apr 20 06:14:31 2021[1,24]<stderr>: 1 0x0000000000053c4b ucs_callbackq_slow_proxy()  /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/ucs/datastruct/callbackq.c:402
Tue Apr 20 06:14:31 2021[1,24]<stderr>: 2 0x000000000004806a ucs_callbackq_dispatch()  /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/ucs/datastruct/callbackq.h:211
Tue Apr 20 06:14:31 2021[1,24]<stderr>: 3 0x000000000004806a uct_worker_progress()  /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/uct/api/uct.h:2592
Tue Apr 20 06:14:31 2021[1,24]<stderr>: 4 0x000000000004806a ucp_worker_progress()  /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/ucp/core/ucp_worker.c:2530
Tue Apr 20 06:14:31 2021[1,24]<stderr>: 5 0x00000000000365dc opal_progress()  /build-result/src/hpcx-gcc-redhat7.6/ompi-ae74eaa/opal/runtime/opal_progress.c:231
Tue Apr 20 06:14:31 2021[1,36]<stderr>:/hpc/local/benchmarks/daily/next/2021-04-19/hpcx-gcc-redhat7.6/ompi/lib/libmpi.so.40(ompi_coll_base_barrier_intra_recursivedoubling+0x33e)[0x7f40ea1fb44e]
Tue Apr 20 06:14:31 2021[1,36]<stderr>:[jazz24:140516] [11] Tue Apr 20 06:14:31 2021[1,24]<stderr>: 6 0x000000000004d0d5 ompi_request_wait_completion()  /build-result/src/hpcx-gcc-redhat7.6/ompi-ae74eaa/ompi/../ompi/request/request.h:415
Tue Apr 20 06:14:31 2021[1,24]<stderr>: 7 0x000000000004d0d5 ompi_request_default_wait()  /build-result/src/hpcx-gcc-redhat7.6/ompi-ae74eaa/ompi/request/req_wait.c:42
Tue Apr 20 06:14:31 2021[1,24]<stderr>: 8 0x00000000000922c4 ompi_coll_base_sendrecv_zero()  /build-result/src/hpcx-gcc-redhat7.6/ompi-ae74eaa/ompi/mca/coll/base/coll_base_barrier.c:64
Tue Apr 20 06:14:31 2021[1,24]<stderr>: 9 0x00000000000922c4 ompi_coll_base_barrier_intra_recursivedoubling()  /build-result/src/hpcx-gcc-redhat7.6/ompi-ae74eaa/ompi/mca/coll/base/coll_base_barrier.c:219
Tue Apr 20 06:14:31 2021[1,24]<stderr>:10 0x0000000000060128 PMPI_Barrier()  /build-result/src/hpcx-gcc-redhat7.6/ompi-ae74eaa/ompi/mpi/c/profile/pbarrier.c:74
Tue Apr 20 06:14:31 2021[1,24]<stderr>:11 0x00000000004010ad main()  /build-result/mtt-tests-gcc/installs/DqAE/tests/mpi-small-tests/mtt-tests.git/mpi-small-tests/misc/mpiring.c:77
Tue Apr 20 06:14:31 2021[1,24]<stderr>:12 0x00000000000223d5 __libc_start_main()  ???:0
Tue Apr 20 06:14:31 2021[1,24]<stderr>:13 0x0000000000400ae9 _start()  ???:0
```

**Comment by brminich** [comment] 2021-07-01 19:31
can't reproduce in 10 hrs, closing

**Closed by brminich** 2021-07-01 19:31 UTC
Labels: Bug, MTT
