### ISSUE TITLE
OpenMPI 4.0.1 fails to build against ucx-1.6.1

### ISSUE THREAD

**Issue by ca-taylor** [openucx/ucx#4156] opened 2019-09-04 16:32 UTC
[chasman@login4 SPECS]$ rpm -qa | grep ucx
ucx-cma-1.6.1-1.el75.x86_64
ucx-ib-1.6.1-1.el75.x86_64
ucx-ib-cm-1.6.1-1.el75.x86_64
ucx-devel-1.6.1-1.el75.x86_64
ucx-rdmacm-1.6.1-1.el75.x86_64
ucx-1.6.1-1.el75.x86_64

  $ ./configure --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/apps/mpi/intel/2018.1.163/openmpi/4.0.1 --exec-prefix=/apps/mpi/intel/2018.1.163/openmpi/4.0.1 --bindir=/apps/mpi/intel/2018.1.163/openmpi/4.0.1/bin --sbindir=/apps/mpi/intel/2018.1.163/openmpi/4.0.1/sbin --sysconfdir=/apps/mpi/intel/2018.1.163/openmpi/4.0.1/etc --datadir=/apps/mpi/intel/2018.1.163/openmpi/4.0.1/share --includedir=/apps/mpi/intel/2018.1.163/openmpi/4.0.1/include --libdir=/apps/mpi/intel/2018.1.163/openmpi/4.0.1/lib64 --libexecdir=/apps/mpi/intel/2018.1.163/openmpi/4.0.1/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/apps/mpi/intel/2018.1.163/openmpi/4.0.1/share/man --infodir=/apps/mpi/intel/2018.1.163/openmpi/4.0.1/share/info C=icc CXX=icpc FC=ifort FFLAGS=-O2 -g -warn -m64 LDFLAGS= --enable-static --enable-orterun-prefix-by-default --with-slurm=/opt/slurm --with-pmix=/opt/pmix/3.1.2 --with-pmi=/opt/slurm --with-libevent=external --with-hwloc=external --without-verbs --with-libfabric --with-ucx --with-mxm=no --with-cuda=no --enable-openib-udcm --enable-openib-rdmacm

make[2]: Leaving directory `/home/chasman/rpmbuild/BUILD/openmpi-4.0.1/opal'
Making all in tools/wrappers
make[2]: Entering directory `/home/chasman/rpmbuild/BUILD/openmpi-4.0.1/opal/tools/wrappers'
  CC       opal_wrapper.o
  GENERATE opal_wrapper.1
  CCLD     opal_wrapper
../../../opal/.libs/libopen-pal.so: undefined reference to `uct_ep_create_connected'
make[2]: *** [opal_wrapper] Error 1
make[2]: Leaving directory `/home/chasman/rpmbuild/BUILD/openmpi-4.0.1/opal/tools/wrappers'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/chasman/rpmbuild/BUILD/openmpi-4.0.1/opal'
make: *** [all-recursive] Error 1
error: Bad exit status from /var/tmp/rpm-tmp.SV53C9 (%build)

**Comment by yosefe** [comment] 2019-09-04 16:44
duplicate of #4020

**Closed by yosefe** 2019-09-04 16:44 UTC

**Comment by ca-taylor** [comment] 2019-09-04 16:55
Hmmm.  I read through #4020 and can't really say I understand.  I filed the bug here because OpenMPI 4.0.1 (and 4.0.0) built without issue with ucx-1.4.0 so it seemed like a UCX issue to me.

The issue doesn't appear fixed in the OpenMPI bug so it appears we are just disabling the code with the issue.   I'm hoping that won't affect existing apps but I guess we'll find out.
