### ISSUE TITLE
failure on no_ud_ud_x/test_ucp_sockaddr.onesided_disconnect_s2c/7

### ISSUE THREAD

**Issue by alinask** [openucx/ucx#4768] opened 2020-02-12 15:23 UTC
### Describe the bug
failure on no_ud_ud_x/test_ucp_sockaddr.onesided_disconnect_s2c/7 

```
16:33:21 [ RUN      ] no_ud_ud_x/test_ucp_sockaddr.onesided_disconnect_s2c/7 <dc_x,mm>
16:33:21 [     INFO ] Testing 11.151.71.0:53145
16:33:21 [     INFO ] ignoring error Connection reset by remote peer on endpoint 0x7fffe8afc000
16:33:31 /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-test-node-gpu/worker/3/contrib/../test/gtest/ucp/test_ucp_sockaddr.cc:471: Failure
16:33:31 Value of: status
16:33:31   Actual: 1
16:33:31 Expected: UCS_OK
16:33:31 Which is: 0
16:33:31 [1581518011.922946] [hpc-test-node-gpu02:2008 :0]          mpool.c:43   UCX  WARN  object 0x8843100 was not returned to mpool ucp_requests
16:33:31 /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-test-node-gpu/worker/3/contrib/../test/gtest/common/test.cc:273: Failure
16:33:31 Failed
16:33:31 Got 1 warnings during the test
16:33:31 
[  FAILED  ] no_ud_ud_x/test_ucp_sockaddr.onesided_disconnect_s2c/7, where GetParam() = dc_x,mm (10137 ms)
```
http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/14476/label=hpc-test-node-gpu,worker=3/consoleFull

HOSTNAME=hpc-test-node-gpu02

**Comment by evgeny-leksikov** [comment] 2020-02-12 15:25
should be fixed by https://github.com/openucx/ucx/pull/4761

**Comment by evgeny-leksikov** [comment] 2020-02-18 07:30
@alinask the issue is fixed by https://github.com/openucx/ucx/pull/4761, I think we can close it.

**Closed** 2020-02-18 07:59 UTC
Labels: Bug, Jenkins
