### ISSUE TITLE
Performance regression introduced by #3973

### ISSUE THREAD

**Issue by lyu** [openucx/ucx#3987] opened 2019-07-31 18:19 UTC
Since #3973, I am seeing a significant reduction in all-to-all performance in our OpenSHMEM implementation.

OS: CentOS 7.5.1804 x86_64
Network: Connect-IB MT27600
[OSSS-UCX](https://github.com/openshmem-org/osss-ucx/): Master HEAD

Test program:
```
#include <iostream>
#include <chrono>

#include <shmem.h>

long pSync[SHMEM_ALLTOALL_SYNC_SIZE];

int main()
{
    for (int i = 0; i < SHMEM_ALLTOALL_SYNC_SIZE; i++) {
        pSync[i] = SHMEM_SYNC_VALUE;
    }

    const int N = 80000;

    shmem_init();

    const int mype = shmem_my_pe();
    const int npes = shmem_n_pes();

    auto buf_s = (double*)shmem_malloc(N * sizeof(double) * npes);
    auto buf_r = (double*)shmem_malloc(N * sizeof(double) * npes);

    shmem_barrier_all();

    const auto t0 = std::chrono::steady_clock::now();

    shmem_alltoall64(buf_r, buf_s, N, 0, 0, npes, pSync);

    const auto t1 = std::chrono::steady_clock::now();

    const double T = std::chrono::duration<double>(t1 - t0).count();

    shmem_barrier_all();

    if (mype == 0) {
        std::cout << T << '\n';
    }

    shmem_free(buf_s);
    shmem_free(buf_r);

    shmem_finalize();
}
```

Run on two nodes: `oshrun -n 32 --map-by node:span ./a.out`

UCX: b121067
`0.0620651`

UCX: acf0152
`0.0335261`

Edit: Simple point-to-point tests using `ucx_perftest` didn't show much of a change. It seems that this only affects more intensive communications.

Edit 2: Fix pSync initialization in example.

**Comment by shamisp** [comment] 2019-07-31 18:52
@yosefe , FYI

**Comment by hoopoepg** [comment] 2019-08-01 08:58
really strange: how pointer to datatype instead of set of parameters may affect to performance?

**Comment by yosefe** [comment] 2019-08-01 13:01
@lyu i could not reproduce the difference on my setup..
1. What is the output of "rpm -q libibverbs" and "ucx_info -v -b -d" on your machine?
1. the test should initialize pSync to _SHMEM_SYNC_VALUE
1. I guess you increase the symmetric heap size when running on 32 PEs?
1. Can you still see performance difference with less PEs, e.g 8 or 16?

**Comment by hoopoepg** [comment] 2019-08-01 13:19
@lyu and one more test: try to set
```UCX_BUILTIN_MEMCPY_MIN=inf```
and test degradation

thank you

**Comment by lyu** [comment] 2019-08-01 13:27
> What is the output of "rpm -q libibverbs" and "ucx_info -v -b -d" on your machine?
```
libibverbs-41mlnx1-OFED.4.4.2.0.1.44207.x86_64
libibverbs-41mlnx1-OFED.4.4.2.0.1.44207.i686
```
[info.txt](https://github.com/openucx/ucx/files/3456912/info.txt)


> the test should initialize pSync to _SHMEM_SYNC_VALUE

Oops, fixed. But this didn't affect the performance difference.

>I guess you increase the symmetric heap size when running on 32 PEs?

I have `SHMEM_SYMMETRIC_SIZE=2048M` for all my tests.

>Can you still see performance difference with less PEs, e.g 8 or 16?

8 PEs & acf0152: `0.00317`

8 PEs & b121067: `0.00331`

16 PEs & acf0152: `0.0094`

16 PEs & b121067: `0.0135`

Like I said this is not just all-to-all. I discovered this issue in other benchmarks with complicated communication patterns, and all-to-all is the easiest way to reproduce it.

@hoopoepg `UCX_BUILTIN_MEMCPY_MIN=inf` has no effect on both versions.

**Comment by yosefe** [comment] 2019-08-01 13:39
@lyu sorry, one more question: can you see the difference when running on single node, 16 PEs, and setting UCX_TLS=rc_x?

**Comment by lyu** [comment] 2019-08-01 13:46
@yosefe Aha! On a single node and 16 PEs, UCX acf0152

With `UCX_TLS=rc_x`: `0.02548`

Without `UCX_TLS=rc_x`: `0.00787`

**Comment by yosefe** [comment] 2019-08-01 14:48
@lyu that narrows down the problem (looks like shared memory is not being used), but i still can't reproduce it.. can you pls try the following:
1. Run b121067 with UCX_TLS=sm
1. Run `<ucx>/src/tools/info/ucx_info -m 2048M -u ar`. What is the output?

**Comment by shamisp** [comment] 2019-08-01 14:51
@lyu I guess you are running with xpmem ?

**Comment by lyu** [comment] 2019-08-01 14:53
> Run with UCX_TLS=sm

Single node, 16 PEs

acf0152: `0.01219`

b121067: `0.01306`

@shamisp We don't have xpmem on our cluster

**Comment by lyu** [comment] 2019-08-01 14:55
@tonycurtis Could you please try to reproduce this?

**Comment by yosefe** [comment] 2019-08-01 15:04
@lyu can you pls check if #3991 fixes this?

**Comment by lyu** [comment] 2019-08-01 15:14
@yosefe Yes, it fixed the issue for both single and double nodes. Thank you!

Closing.

**Comment by yosefe** [comment] 2019-08-01 15:14
(reopening until fix is merged)

**Closed** 2019-08-02 10:10 UTC
Labels: Optimization
