### ISSUE TITLE
[mtt] Transport retry count exceeded on Hercules

### ISSUE THREAD

**Issue by amaslenn** [openucx/ucx#3305] opened 2019-03-05 08:34 UTC
Configuration
```
OMPI: 4.0.1rc1
MOFED: MLNX_OFED_LINUX-4.5-1.0.1.0
Module: hpcx-gcc (2019-02-27)
Test module: mtt-tests/hpcx-gcc
Nodes: hercules x76 (ppn=32(x76), nodelist=clx-hercules-[002-006,008-015,017-025,027-080])
```

MTT log: http://e2e-gw.mellanox.com:4080/hpc/scrap/users/mtt/scratch/ucx_ompi/20190228_072622_618_318271_clx-hercules-002/html/test_stdout_oVT7X_.txt

Cmd:
`mpirun -np 3 --report-bindings -mca btl self --tag-output --timestamp-output -mca pml ucx -mca coll '^hcoll' --bind-to core -x UCX_NET_DEVICES=mlx5_2:1,mlx5_3:1 -mca osc ucx -x UCX_IB_REG_METHODS=rcache,direct -x UCX_TLS=dc_x,self,sm -x UCX_DC_MLX5_TX_POLICY=dcs_quota -x UCX_RC_TM_ENABLE=n -mca pmix_base_async_modex 1 -mca mpi_add_procs_cutoff 0 -mca pmix_base_collect_data 0 -x UCX_MAX_EAGER_LANES=3 -x UCX_MAX_RNDV_LANES=3 --map-by node /hpc/local/benchmarks/hpcx_install_2019-02-27/mtt-tests-gcc/installs/Bnby/tests/mpich_tests/mtt-tests.git/mpich/test/mpi/basic/adapt`

Output:
```sh
Tue Mar  5 10:18:50 2019[1,2]<stdout>:159: 536870914 bytes    7 times --> Tue Mar  5 10:18:55 2019[1,0]<stdout>:159: 536870914 bytes    7 times --> Tue Mar  5 10:18:55 2019[1,2]<stdout>:   0.00 Mbps in 0.042620157 sec
Tue Mar  5 10:19:00 2019[1,0]<stdout>:   0.00 Mbps in 0.042628198 sec
Tue Mar  5 10:19:00 2019[1,0]<stdout>:159: 536870914 bytes    7 times --> Tue Mar  5 10:19:09 2019[1,0]<stdout>: 0.085559623Tue Mar  5 10:19:18 2019[1,0]<stdout>: 0.085550393Tue Mar  5 10:19:21 2019[1,0]<stderr>:[clx-hercules-001:5663 :0:5663] ib_mlx5_log.c:139  Transport retry count exceeded on mlx5_2:1/IB (synd 0x15 vend 0x83 hw_synd 0/0)
Tue Mar  5 10:19:21 2019[1,0]<stderr>:[clx-hercules-001:5663 :0:5663] ib_mlx5_log.c:139  DCI QP 0x2394a wqe[375]: RDMA_READ s-- [rqpn 0x16ae5 rlid 100] [rva 0x7fffbb968000 rkey 0x159e] [va 0x7fff9b964000 len 268435968 lkey 0x1502]
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 5663 on node clx-hercules-001 exited on signal 11 (Segmentation fault).
--------------------------------------------------------------------------
```

MLNX tracker: https://redmine.mellanox.com/issues/1684815

**Comment by yosefe** [comment] 2019-03-05 09:30
maybe be related to https://redmine.mellanox.com/issues/1684815 (Mellanox internal link)

**Comment by brminich** [comment] 2019-03-05 12:34
looks like a different one. Reproduced on hercules, but ib_send_lat works.
dmesg contains just:
[Tue Mar  5 14:19:54 2019] adapt[13893]: segfault at 20 ip 00007ffff7de6d16 sp 00007fffffffa740 error 4 in ld-2.17.so[7ffff7ddb000+22000]

**Comment by yosefe** [comment] 2019-03-05 12:37
is RoCE lossless?

**Comment by amaslenn** [comment] 2019-03-06 03:14
Seems verification script doesn't exist anymore:
```
# /hpc/local/bin/lossless_roce_hca.sh ens3f1
bash: /hpc/local/bin/lossless_roce_hca.sh: No such file or directory
```
(the script is a symlink which is broken, I addressed it with devops).

**Comment by brminich** [comment] 2019-03-07 09:58
This is from hercules nodes:
```
Priority trust state is cofigured to Lossless: dscp
PFC is NOT cofigured to Lossless: 00000000. Expected 00010000
Traffic Class is cofigured to Lossless: Global tclass=106
TCP ECN is NOT cofigured to Lossless: 2. Expected 1
RDMA-CM ToS is cofigured to Lossless: 106
```

**Comment by brminich** [comment] 2019-03-17 08:01
https://redmine.mellanox.com/issues/1706553
(MLNX internal link)

**Comment by amaslenn** [comment] 2019-03-17 09:59
Found in shmem tests:

Configuration
```
OMPI: 4.0.1rc1
MOFED: MLNX_OFED_LINUX-4.5-1.0.1.0
Module: hpcx-gcc (2019-03-16)
Test module: none
Nodes: jazz x8 (ppn=28(x8), nodelist=jazz[10,12-13,19-23])
```

Cmd:
`oshrun -np 224 --report-bindings -mca btl self --bind-to core -mca oshmem_proc_group_cache_size 10000 -x UCX_NET_DEVICES=mlx5_0:1 -mca sshmem mmap -mca spml_ucx_heap_reg_nb 0 -mca coll '^hcoll' -mca coll_hcoll_enable 0 -mca spml ucx -mca pml ucx -x UCX_TLS=ud_x --map-by node -x SHMEM_SYMMETRIC_HEAP_SIZE=2797M /hpc/mtr_scrap/users/mtt/scratch/shmem/20190316_220747_151117_18736_jazz10/installs/H9y5/tests/verifier/tests-mellanox.git/verifier/install/bin/oshmem_test exec --no-colour --task=sync`

Output:
```sh
PASS   sync       wait_until     Wait Until Synchronization Routine.
[jazz10:93813:0:93813]    ud_iface.c:746  Fatal: transport error: Endpoint timeout

/hpc/local/benchmarks/hpcx_install_2019-03-16/src/hpcx-gcc-redhat7.4/ucx-master/src/ucs/debug/assert.c: [ ucs_fatal_error_message() ]
      ...       33     }
       34 
       35     ucs_handle_error(message_buf);
==>    36     abort();
       37 }
       38 
       39 void ucs_fatal_error_format(const char *file, unsigned line,
==== backtrace ====
 0 0x00000000000482e8 ucs_fatal_error_message()  /hpc/local/benchmarks/hpcx_install_2019-03-16/src/hpcx-gcc-redhat7.4/ucx-master/src/ucs/debug/assert.c:36
 1 0x0000000000048449 ucs_fatal_error_format()  /hpc/local/benchmarks/hpcx_install_2019-03-16/src/hpcx-gcc-redhat7.4/ucx-master/src/ucs/debug/assert.c:52
 2 0x000000000003c171 uct_ud_ep_dispatch_err_comp()  /hpc/local/benchmarks/hpcx_install_2019-03-16/src/hpcx-gcc-redhat7.4/ucx-master/src/uct/ib/ud/base/ud_iface.c:746
 3 0x0000000000044574 uct_ud_iface_dispatch_zcopy_comps()  /hpc/local/benchmarks/hpcx_install_2019-03-16/src/hpcx-gcc-redhat7.4/ucx-master/src/uct/ib/ud/base/ud_iface.h:447
 4 0x0000000000019132 ucs_callbackq_dispatch()  /hpc/local/benchmarks/hpcx_install_2019-03-16/src/hpcx-gcc-redhat7.4/ucx-master/src/ucs/datastruct/callbackq.h:211
 5 0x0000000000003767 mca_pml_ucx_progress()  /hpc/local/benchmarks/hpcx_install_2019-03-16/src/hpcx-gcc-redhat7.4/ompi/ompi/mca/pml/ucx/pml_ucx.c:510
 6 0x00000000000370dc opal_progress()  /hpc/local/benchmarks/hpcx_install_2019-03-16/src/hpcx-gcc-redhat7.4/ompi/opal/runtime/opal_progress.c:231
 7 0x000000000004b945 ompi_request_wait_completion()  /hpc/local/benchmarks/hpcx_install_2019-03-16/src/hpcx-gcc-redhat7.4/ompi/ompi/../ompi/request/request.h:415
 8 0x000000000008ffc9 ompi_coll_base_sendrecv_zero()  /hpc/local/benchmarks/hpcx_install_2019-03-16/src/hpcx-gcc-redhat7.4/ompi/ompi/mca/coll/base/coll_base_barrier.c:64
 9 0x0000000000002373 mca_scoll_mpi_barrier()  /hpc/local/benchmarks/hpcx_install_2019-03-16/src/hpcx-gcc-redhat7.4/ompi/oshmem/mca/scoll/mpi/scoll_mpi_ops.c:25
10 0x000000000005d10f pshmem_barrier_all()  /hpc/local/benchmarks/hpcx_install_2019-03-16/src/hpcx-gcc-redhat7.4/ompi/oshmem/shmem/c/profile/pshmem_barrier.c:61
11 0x000000000003accc _shfree()  /hpc/local/benchmarks/hpcx_install_2019-03-16/src/hpcx-gcc-redhat7.4/ompi/oshmem/shmem/c/profile/pshmem_free.c:53
12 0x000000000003accc pshfree()  /hpc/local/benchmarks/hpcx_install_2019-03-16/src/hpcx-gcc-redhat7.4/ompi/oshmem/shmem/c/profile/pshmem_free.c:38
13 0x00000000004b2cd0 test_group()  /hpc/mtr_scrap/users/mtt/scratch/shmem/20190316_220747_151117_18736_jazz10/installs/H9y5/tests/verifier/tests-mellanox.git/verifier/sync/osh_sync_tc4.c:284
14 0x00000000004b2cd0 osh_sync_tc4()  /hpc/mtr_scrap/users/mtt/scratch/shmem/20190316_220747_151117_18736_jazz10/installs/H9y5/tests/verifier/tests-mellanox.git/verifier/sync/osh_sync_tc4.c:81
15 0x0000000000406b29 __do_exec()  /hpc/mtr_scrap/users/mtt/scratch/shmem/20190316_220747_151117_18736_jazz10/installs/H9y5/tests/verifier/tests-mellanox.git/verifier/osh_exec.c:287
16 0x0000000000406b29 proc_mode_exec()  /hpc/mtr_scrap/users/mtt/scratch/shmem/20190316_220747_151117_18736_jazz10/installs/H9y5/tests/verifier/tests-mellanox.git/verifier/osh_exec.c:128
17 0x00000000004057ae main()  /hpc/mtr_scrap/users/mtt/scratch/shmem/20190316_220747_151117_18736_jazz10/installs/H9y5/tests/verifier/tests-mellanox.git/verifier/osh_main.c:138
18 0x0000000000021c05 __libc_start_main()  ???:0
19 0x00000000004059c1 _start()  ???:0
===================
```
Full log: http://hpcweb.lab.mtl.com/hpc/mtr_scrap/users/mtt/scratch/shmem/20190316_220747_151117_18736_jazz10/html/test_stdout_fcQlBa.txt

**Comment by amaslenn** [comment] 2019-03-18 04:57
Reproduced on Jazz RoCE:

Configuration
```
OMPI: 4.0.1rc1
MOFED: MLNX_OFED_LINUX-4.5-1.0.1.0
Module: hpcx-gcc (2019-03-15)
Test module: mtt-tests/hpcx-gcc
Nodes: jazz x3 (ppn=28(x3), nodelist=jazz[03,09,32])
```

MTT log: http://hpcweb.lab.mtl.com/hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20190316_002332_167047_18715_jazz03/html/test_stdout_6QeZYU.txt

Cmd:
`$ mpirun -np 9 -mca btl self --tag-output --timestamp-output -mca pml ucx -mca coll '^hcoll' --bind-to core -x UCX_NET_DEVICES=mlx5_3:1 -mca osc ucx -x UCX_IB_REG_ME
THODS=rcache,direct -x UCX_TLS=dc_x,self,sm -x UCX_DC_MLX5_TX_POLICY=dcs_quota -mca pmix_base_async_modex 1 -mca mpi_add_procs_cutoff 0 -mca pmix_base_collect_data 0
 --map-by node /hpc/local/benchmarks/hpcx_install_2019-03-15/hpcx-gcc-redhat7.4/ompi/tests/osu-micro-benchmarks-5.6/osu_alltoallv`

```sh
Mon Mar 18 06:53:56 2019[1,0]<stdout>:
Mon Mar 18 06:53:56 2019[1,0]<stdout>:# OSU MPI All-to-Allv Personalized Exchange Latency Test v5.6
Mon Mar 18 06:53:56 2019[1,0]<stdout>:# Size       Avg Latency(us)
Mon Mar 18 06:53:56 2019[1,0]<stdout>:1                      12.08
Mon Mar 18 06:53:56 2019[1,0]<stdout>:2                      11.11
Mon Mar 18 06:53:56 2019[1,0]<stdout>:4                      11.11
Mon Mar 18 06:53:56 2019[1,0]<stdout>:8                      11.00
Mon Mar 18 06:53:59 2019[1,0]<stdout>:16                   2111.58
Mon Mar 18 06:53:59 2019[1,0]<stdout>:32                     12.09
Mon Mar 18 06:53:59 2019[1,0]<stdout>:64                     13.30
Mon Mar 18 06:53:59 2019[1,0]<stdout>:128                    13.60
Mon Mar 18 06:53:59 2019[1,0]<stdout>:256                    15.55
Mon Mar 18 06:53:59 2019[1,0]<stdout>:512                    16.64
Mon Mar 18 06:53:59 2019[1,0]<stdout>:1024                   19.44
Mon Mar 18 06:54:16 2019[1,0]<stderr>:[jazz06:64666:0:64666] ib_mlx5_log.c:139  Transport retry count exceeded on mlx5_3:1/RoCE (synd 0x15 vend 0x81 hw_synd 0/0)
Mon Mar 18 06:54:16 2019[1,0]<stderr>:[jazz06:64666:0:64666] ib_mlx5_log.c:139  DCI QP 0x19fed wqe[361]: SEND s-e [rqpn 0x1b20a rmac ec:0d:9a:46:9e:25 sgix 3 dgid ::2.1.3.7 tc 106] [va 0x7
f810bdf9d40 len 2058 lkey 0x13e90b]
Mon Mar 18 06:54:16 2019[1,0]<stderr>:
Mon Mar 18 06:54:16 2019[1,0]<stderr>:/hpc/local/benchmarks/hpcx_install_2019-03-17/src/hpcx-gcc-redhat7.4/ucx-master/src/ucs/debug/assert.c: [ ucs_fatal_error_message() ]
Mon Mar 18 06:54:16 2019[1,0]<stderr>:      ...
Mon Mar 18 06:54:16 2019[1,0]<stderr>:       33     }
Mon Mar 18 06:54:16 2019[1,0]<stderr>:       34
Mon Mar 18 06:54:16 2019[1,0]<stderr>:       35     ucs_handle_error(message_buf);
Mon Mar 18 06:54:16 2019[1,0]<stderr>:==>    36     abort();
Mon Mar 18 06:54:16 2019[1,0]<stderr>:       37 }
Mon Mar 18 06:54:16 2019[1,0]<stderr>:       38
Mon Mar 18 06:54:16 2019[1,0]<stderr>:       39 void ucs_fatal_error_format(const char *file, unsigned line,
Mon Mar 18 06:54:16 2019[1,0]<stderr>:
Mon Mar 18 06:54:16 2019[1,0]<stderr>:==== backtrace ====
Mon Mar 18 06:54:16 2019[1,0]<stderr>: 0 0x00000000000482e8 ucs_fatal_error_message()  /hpc/local/benchmarks/hpcx_install_2019-03-17/src/hpcx-gcc-redhat7.4/ucx-master/src/ucs/debug/assert.
c:36
Mon Mar 18 06:54:16 2019[1,0]<stderr>: 1 0x000000000004b34c ucs_log_default_handler()  /hpc/local/benchmarks/hpcx_install_2019-03-17/src/hpcx-gcc-redhat7.4/ucx-master/src/ucs/debug/log.c:1
40
Mon Mar 18 06:54:16 2019[1,0]<stderr>: 2 0x000000000004b474 ucs_log_dispatch()  /hpc/local/benchmarks/hpcx_install_2019-03-17/src/hpcx-gcc-redhat7.4/ucx-master/src/ucs/debug/log.c:193
Mon Mar 18 06:54:16 2019[1,0]<stderr>: 3 0x000000000001cdb3 uct_ib_mlx5_completion_with_err()  /hpc/local/benchmarks/hpcx_install_2019-03-17/src/hpcx-gcc-redhat7.4/ucx-master/src/uct/ib/ml
x5/ib_mlx5_log.c:132
Mon Mar 18 06:54:16 2019[1,0]<stderr>: 4 0x00000000000387f5 uct_ib_mlx5_poll_cq()  /hpc/local/benchmarks/hpcx_install_2019-03-17/src/hpcx-gcc-redhat7.4/ucx-master/src/uct/ib/mlx5/ib_mlx5.i
nl:38
Mon Mar 18 06:54:16 2019[1,0]<stderr>: 5 0x00000000000190a2 ucs_callbackq_dispatch()  /hpc/local/benchmarks/hpcx_install_2019-03-17/src/hpcx-gcc-redhat7.4/ucx-master/src/ucs/datastruct/cal
lbackq.h:211
Mon Mar 18 06:54:16 2019[1,0]<stderr>: 6 0x0000000000003767 mca_pml_ucx_progress()  /hpc/local/benchmarks/hpcx_install_2019-03-17/src/hpcx-gcc-redhat7.4/ompi/ompi/mca/pml/ucx/pml_ucx.c:510
Mon Mar 18 06:54:16 2019[1,0]<stderr>: 7 0x00000000000370dc opal_progress()  /hpc/local/benchmarks/hpcx_install_2019-03-17/src/hpcx-gcc-redhat7.4/ompi/opal/runtime/opal_progress.c:231
Mon Mar 18 06:54:16 2019[1,0]<stderr>: 8 0x000000000004b945 ompi_request_wait_completion()  /hpc/local/benchmarks/hpcx_install_2019-03-17/src/hpcx-gcc-redhat7.4/ompi/ompi/../ompi/request/r
equest.h:415
Mon Mar 18 06:54:16 2019[1,0]<stderr>: 9 0x0000000000087339 ompi_coll_base_sendrecv_actual()  /hpc/local/benchmarks/hpcx_install_2019-03-17/src/hpcx-gcc-redhat7.4/ompi/ompi/mca/coll/base/c
oll_base_util.c:59
Mon Mar 18 06:54:16 2019[1,0]<stderr>:10 0x000000000008ca63 ompi_coll_base_sendrecv()  /hpc/local/benchmarks/hpcx_install_2019-03-17/src/hpcx-gcc-redhat7.4/ompi/ompi/mca/coll/base/coll_bas
e_util.h:67
Mon Mar 18 06:54:16 2019[1,0]<stderr>:11 0x000000000005f411 PMPI_Alltoallv()  /hpc/local/benchmarks/hpcx_install_2019-03-17/src/hpcx-gcc-redhat7.4/ompi/ompi/mpi/c/profile/palltoallv.c:129
Mon Mar 18 06:54:16 2019[1,0]<stderr>:12 0x0000000000401a1b main()  /hpc/local/benchmarks/hpcx_install_2019-03-15/src/hpcx-gcc-redhat7.4/ompi/mpi_tests/mpitests/osu-micro-benchmarks-5.6/mp
i/collective/osu_alltoallv.c:129
Mon Mar 18 06:54:16 2019[1,0]<stderr>:13 0x0000000000021c05 __libc_start_main()  ???:0
Mon Mar 18 06:54:16 2019[1,0]<stderr>:14 0x0000000000401e11 _start()  ???:0
Mon Mar 18 06:54:16 2019[1,0]<stderr>:===================
```

All devices were active during the testing.

**Comment by amaslenn** [comment] 2020-04-09 10:57
Configuration
```
OMPI: 4.0.3rc4
MOFED: MLNX_OFED_LINUX-5.0-1.0.0.0
Module: hpcx-gcc (2020-04-06)
Test module: mtt-tests/hpcx-gcc
Nodes: hercules x8 (ppn=32(x8), nodelist=clx-hercules-[003,005-006,010-014])
```

MTT log: http://e2e-gw.mellanox.com:4080/mnt/lustre/users/mtt/scratch/ucx_ompi/20200406_144228_5979_577228_clx-hercules-003/html/test_stdout_9SqwzJ.txt

Doesn't always reproduce, had to run 4 iterations to catch.

Cmd:
`mpirun -np 256 --display-map -mca btl self --tag-output --timestamp-output -mca pml ucx -mca coll '^hcoll' -x UCX_ERROR_SIGNALS=SIGILL,SIGSEGV,SIGBUS,SIGFPE,SIGABRT -x UCX_HANDLE_ERRORS=bt -x UCX_IB_PCI_RELAXED_ORDERING=off --bind-to core -x UCX_NET_DEVICES=mlx5_2:1 -mca osc ucx -x UCX_IB_REG_METHODS=rcache,direct -x UCX_TLS=rc_x,self,sm -x UCX_RC_MLX5_TM_ENABLE=y -x UCX_IB_SL=2 -mca pmix_base_async_modex 1 -mca mpi_add_procs_cutoff 0 -mca pmix_base_collect_data 0 --map-by node /hpc/local/benchmarks/daily/next/2020-04-06/mtt-tests-gcc/installs/_WAn/tests/hash/mtt-tests.git/kmi_hash/tests/BENCH_QUERY -n 4000 -m 4000`

Output:
```
Thu Apr  9 13:46:55 2020[1,0]<stdout>:Histogram sort sampling finish, num_pivots = 1532, screw ratio=1.097875
Thu Apr  9 13:52:31 2020[1,215]<stderr>:[clx-hercules-025:13793:0:13793]    ud_iface.c:752  Fatal: transport error: Endpoint timeout
Thu Apr  9 13:52:31 2020[1,215]<stderr>:==== backtrace (tid:  13793) ====
Thu Apr  9 13:52:31 2020[1,215]<stderr>: 0 0x0000000000050da5 ucs_debug_print_backtrace()  /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/ucs/debug/debug.c:656
Thu Apr  9 13:52:31 2020[1,215]<stderr>: 1 0x000000000004507c uct_ud_ep_dispatch_err_comp()  /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/uct/ib/ud/base/ud_iface.c:752
Thu Apr  9 13:52:31 2020[1,215]<stderr>: 2 0x000000000004507c uct_ud_iface_dispatch_async_comps_do()  /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/uct/ib/ud/base/ud_iface.c:771
Thu Apr  9 13:52:31 2020[1,215]<stderr>: 3 0x000000000004c31e uct_ud_iface_dispatch_async_comps()  /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/uct/ib/ud/base/ud_iface.h:469
Thu Apr  9 13:52:31 2020[1,215]<stderr>: 4 0x000000000004c31e uct_ud_mlx5_iface_progress()  /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/uct/ib/ud/accel/ud_mlx5.c:513
Thu Apr  9 13:52:31 2020[1,215]<stderr>: 5 0x0000000000023192 ucs_callbackq_dispatch()  /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/ucs/datastruct/callbackq.h:211
Thu Apr  9 13:52:31 2020[1,215]<stderr>: 6 0x0000000000023192 uct_worker_progress()  /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/uct/api/uct.h:2317
Thu Apr  9 13:52:31 2020[1,215]<stderr>: 7 0x0000000000023192 ucp_worker_progress()  /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/ucp/core/ucp_worker.c:1957
Thu Apr  9 13:52:31 2020[1,215]<stderr>: 8 0x00000000000056e8 mca_pml_ucx_send_nbr()  /build-result/src/hpcx-gcc-redhat7.6/ompi-v4.0.x/ompi/mca/pml/ucx/pml_ucx.c:822
Thu Apr  9 13:52:31 2020[1,215]<stderr>: 9 0x00000000000056e8 mca_pml_ucx_send_nbr()  /build-result/src/hpcx-gcc-redhat7.6/ompi-v4.0.x/ompi/mca/pml/ucx/pml_ucx.c:822
Thu Apr  9 13:52:31 2020[1,215]<stderr>:10 0x00000000000056e8 mca_pml_ucx_send()  /build-result/src/hpcx-gcc-redhat7.6/ompi-v4.0.x/ompi/mca/pml/ucx/pml_ucx.c:843
Thu Apr  9 13:52:31 2020[1,215]<stderr>:11 0x000000000007043d PMPI_Send()  /build-result/src/hpcx-gcc-redhat7.6/ompi-v4.0.x/ompi/mpi/c/profile/psend.c:81
Thu Apr  9 13:52:31 2020[1,215]<stderr>:12 0x00000000004063c2 KMI_table_commit_fixed_length()  /build-result/mtt-tests-gcc/installs/_WAn/tests/hash/mtt-tests.git/kmi_hash/src/table.c:874
Thu Apr  9 13:52:31 2020[1,215]<stderr>:13 0x0000000000406db5 KMI_table_commit()  /build-result/mtt-tests-gcc/installs/_WAn/tests/hash/mtt-tests.git/kmi_hash/src/table.c:1271
Thu Apr  9 13:52:31 2020[1,215]<stderr>:14 0x0000000000401363 main()  ???:0
Thu Apr  9 13:52:31 2020[1,215]<stderr>:15 0x00000000000223d5 __libc_start_main()  ???:0
Thu Apr  9 13:52:31 2020[1,215]<stderr>:16 0x0000000000401501 _start()  ???:0
Thu Apr  9 13:52:31 2020[1,215]<stderr>:=================================
Thu Apr  9 13:52:31 2020[1,215]<stderr>:[clx-hercules-025:13793] *** Process received signal ***
Thu Apr  9 13:52:31 2020[1,215]<stderr>:[clx-hercules-025:13793] Signal: Aborted (6)
Thu Apr  9 13:52:31 2020[1,215]<stderr>:[clx-hercules-025:13793] Signal code:  (-6)
Thu Apr  9 13:52:31 2020[1,215]<stderr>:[clx-hercules-025:13793] [ 0] /usr/lib64/libpthread.so.0(+0xf5d0)[0x7ffff78da5d0]
Thu Apr  9 13:52:31 2020[1,215]<stderr>:[clx-hercules-025:13793] [ 1] /usr/lib64/libc.so.6(gsignal+0x37)[0x7ffff7534207]
Thu Apr  9 13:52:31 2020[1,215]<stderr>:[clx-hercules-025:13793] [ 2] /usr/lib64/libc.so.6(abort+0x148)[0x7ffff75358f8]
Thu Apr  9 13:52:31 2020[1,215]<stderr>:[clx-hercules-025:13793] [ 3] /hpc/local/benchmarks/daily/next/2020-04-09/hpcx-gcc-redhat7.6/ucx/lib/libucs.so.0(ucs_fatal_error_message+0x55)[0x7fffea01caa5]
Thu Apr  9 13:52:31 2020[1,215]<stderr>:[clx-hercules-025:13793] [ 4] /hpc/local/benchmarks/daily/next/2020-04-09/hpcx-gcc-redhat7.6/ucx/lib/libucs.so.0(+0x4fc29)[0x7fffea01cc29]
Thu Apr  9 13:52:31 2020[1,215]<stderr>:[clx-hercules-025:13793] [ 5] /hpc/local/benchmarks/daily/next/2020-04-09/hpcx-gcc-redhat7.6/ucx/lib/ucx/libuct_ib.so.0(uct_ud_iface_dispatch_async_comps_do+0x11c)[0x7fffe998b07c]
Thu Apr  9 13:52:31 2020[1,215]<stderr>:[clx-hercules-025:13793] [ 6] /hpc/local/benchmarks/daily/next/2020-04-09/hpcx-gcc-redhat7.6/ucx/lib/ucx/libuct_ib.so.0(+0x4c31e)[0x7fffe999231e]
Thu Apr  9 13:52:31 2020[1,215]<stderr>:[clx-hercules-025:13793] [ 7] /hpc/local/benchmarks/daily/next/2020-04-09/hpcx-gcc-redhat7.6/ucx/lib/libucp.so.0(ucp_worker_progress+0x22)[0x7fffea584192]
Thu Apr  9 13:52:31 2020[1,215]<stderr>:[clx-hercules-025:13793] [ 8] /hpc/local/benchmarks/daily/next/2020-04-09/hpcx-gcc-redhat7.6/ompi/lib/openmpi/mca_pml_ucx.so(mca_pml_ucx_send+0x108)[0x7fffea9c96e8]
Thu Apr  9 13:52:31 2020[1,215]<stderr>:[clx-hercules-025:13793] [ 9] /hpc/local/benchmarks/daily/next/2020-04-09/hpcx-gcc-redhat7.6/ompi/lib/libmpi.so.40(PMPI_Send+0x2d)[0x7ffff7b5743d]
Thu Apr  9 13:52:31 2020[1,215]<stderr>:[clx-hercules-025:13793] [10] /hpc/local/benchmarks/daily/next/2020-04-06/mtt-tests-gcc/installs/_WAn/tests/hash/mtt-tests.git/kmi_hash/tests/BENCH_QUERY[0x4063c2]
Thu Apr  9 13:52:31 2020[1,215]<stderr>:[clx-hercules-025:13793] [11] /hpc/local/benchmarks/daily/next/2020-04-06/mtt-tests-gcc/installs/_WAn/tests/hash/mtt-tests.git/kmi_hash/tests/BENCH_QUERY[0x406db5]
Thu Apr  9 13:52:31 2020[1,215]<stderr>:[clx-hercules-025:13793] [12] /hpc/local/benchmarks/daily/next/2020-04-06/mtt-tests-gcc/installs/_WAn/tests/hash/mtt-tests.git/kmi_hash/tests/BENCH_QUERY[0x401363]
Thu Apr  9 13:52:31 2020[1,215]<stderr>:[clx-hercules-025:13793] [13] /usr/lib64/libc.so.6(__libc_start_main+0xf5)[0x7ffff75203d5]
Thu Apr  9 13:52:31 2020[1,215]<stderr>:[clx-hercules-025:1379Thu Apr  9 13:52:31 2020[1,215]<stderr>:3] [14] /hpc/local/benchmarks/daily/next/2020-04-06/mtt-tests-gcc/installs/_WAn/tests/hash/mtt-tests.git/kmi_hash/tests/BENCH_QUERY[0x401501]
Thu Apr  9 13:52:31 2020[1,215]<stderr>:[clx-hercules-025:13793] *** End of error message ***
Thu Apr  9 13:52:31 2020[1,187]<stderr>:[clx-hercules-021:17879:0:17879]    ud_iface.c:752  Fatal: transport error: Endpoint timeout
Thu Apr  9 13:52:31 2020[1,203]<stderr>:[clx-hercules-021:17883:0:17883]    ud_iface.c:752  Fatal: transport error: Endpoint timeout
Thu Apr  9 13:52:31 2020[1,129]<stderr>:[clx-hercules-019:18154:0:18154]    ud_iface.c:752  Fatal: transport error: Endpoint timeout
Thu Apr  9 13:52:31 2020[1,187]<stderr>:==== backtrace (tid:  17879) ====
```

**Comment by yosefe** [comment] 2020-04-11 19:49
seems to be fixed by #5016 :
-default ucx - fails after ~5 iterations
-with fixes - passes 38 iterations (for now..)

**Closed** 2020-04-11 21:02 UTC
Labels: Bug, External, MTT

**Comment by kpamnany** [comment] 2020-04-15 20:48
Hi @yosefe. We're seeing this error intermittently with our runs, but it doesn't seem as though the fix made it into 1.8.0. Will you be tagging a new release that includes this fix?

Cc: @simonbyrne

**Comment by yosefe** [comment] 2020-04-15 20:51
@kpamnany the issue didn't exist in 1.8.0. Transport retry exceeded is a generic error which means you could be seeing a different issue.
I'd suggest to file a new bug report for the issue you see, with all system details, and additional symptoms if any.

**Comment by kpamnany** [comment] 2020-04-15 20:57
Thanks @yosefe. We'll try with 1.8.0 and see if it recurs. We only see it intermittently which makes it difficult to track down. I'll open a bug report if we see it again.
