### ISSUE TITLE
Error using UCT short message protocol

### ISSUE THREAD

**Issue by hjelmn** [openucx/ucx#2937] opened 2018-10-09 19:43 UTC
In btl/uct I am using ```uct_ep_put_short``` for small puts when ```size <= uct_iface_attr.cap.put.max_short```. This works with the dc transport but gives me the following error with using dc_mlx5:

```
[1539114158.001969] [cn824:21469:4]        dc_mlx5.c:527  UCX  ERROR Invalid put_short length: 256 (expected: <= 172)
```

I checked and the reported max short in the capabilities is 2048. For the dc transport it is 108. Looks like a bug to me.

**Comment by yosefe** [comment] 2018-10-10 07:53
@hoopoepg looks like an issue with MEMIC

**Comment by hoopoepg** [comment] 2018-10-10 07:56
@hjelmn what is HCA you got error?
and could you provide reproducer for issue?

thank you

**Comment by hjelmn** [comment] 2018-10-10 15:35
```
hca_id:	mlx5_0
	transport:			InfiniBand (0)
	fw_ver:				16.23.1400
	node_guid:			ec0d:9a03:0098:a3e2
	sys_image_guid:			ec0d:9a03:0098:a3e2
	vendor_id:			0x02c9
	vendor_part_id:			4119
	hw_ver:				0x0
	board_id:			MT_0000000093
	phys_port_cnt:			1
	max_mr_size:			0xffffffffffffffff
	page_size_cap:			0xfffffffffffff000
	max_qp:				262144
	max_qp_wr:			32768
	device_cap_flags:		0xe17e1c36
					BAD_PKEY_CNTR
					BAD_QKEY_CNTR
					AUTO_PATH_MIG
					CHANGE_PHY_PORT
					PORT_ACTIVE_EVENT
					SYS_IMAGE_GUID
					RC_RNR_NAK_GEN
					XRC
					Unknown flags: 0xe16e0000
	device_cap_exp_flags:		0x5248F8F100000000
					EXP_DC_TRANSPORT
					EXP_CROSS_CHANNEL
					EXP_MR_ALLOCATE
					EXT_ATOMICS
					EXT_SEND NOP
					EXP_UMR
					EXP_ODP
					EXP_RX_CSUM_TCP_UDP_PKT
					EXP_RX_CSUM_IP_PKT
					EXP_DC_INFO
					EXP_MASKED_ATOMICS
					EXP_RX_TCP_UDP_PKT_TYPE
					EXP_PHYSICAL_RANGE_MR
					EXP_UMR_FIXED_SIZE
					Unknown flags: 0x200000000000
	max_sge:			30
	max_sge_rd:			30
	max_cq:				16777216
	max_cqe:			4194303
	max_mr:				16777216
	max_pd:				16777216
	max_qp_rd_atom:			16
	max_ee_rd_atom:			0
	max_res_rd_atom:		4194304
	max_qp_init_rd_atom:		16
	max_ee_init_rd_atom:		0
	atomic_cap:			ATOMIC_HCA (1)
	log atomic arg sizes (mask)		0x8
	masked_log_atomic_arg_sizes (mask)	0x3c
	masked_log_atomic_arg_sizes_network_endianness (mask)	0x34
	max fetch and add bit boundary	64
	log max atomic inline		5
	max_ee:				0
	max_rdd:			0
	max_mw:				16777216
	max_raw_ipv6_qp:		0
	max_raw_ethy_qp:		0
	max_mcast_grp:			2097152
	max_mcast_qp_attach:		240
	max_total_mcast_qp_attach:	503316480
	max_ah:				2147483647
	max_fmr:			0
	max_srq:			8388608
	max_srq_wr:			32767
	max_srq_sge:			31
	max_pkeys:			128
	local_ca_ack_delay:		16
	hca_core_clock:			78125
	max_klm_list_size:		65536
	max_send_wqe_inline_klms:	20
	max_umr_recursion_depth:	4
	max_umr_stride_dimension:	1
	general_odp_caps:
					ODP_SUPPORT
					ODP_SUPPORT_IMPLICIT
	max_size:			0xFFFFFFFFFFFFFFFF
	rc_odp_caps:
					SUPPORT_SEND
					SUPPORT_RECV
					SUPPORT_WRITE
					SUPPORT_READ
	uc_odp_caps:
					NO SUPPORT
	ud_odp_caps:
					SUPPORT_SEND
	dc_odp_caps:
					SUPPORT_SEND
					SUPPORT_WRITE
					SUPPORT_READ
	xrc_odp_caps:
					NO SUPPORT
	raw_eth_odp_caps:
					NO SUPPORT
	max_dct:			262144
	max_device_ctx:			508
	Multi-Packet RQ supported
		Supported for objects type:
			IBV_EXP_MP_RQ_SUP_TYPE_SRQ_TM
			IBV_EXP_MP_RQ_SUP_TYPE_WQ_RQ
		Supported payload shifts:
			2 bytes
		Log number of strides for single WQE: 3 - 16
		Log number of bytes in single stride: 6 - 13
	rx_pad_end_addr_align:	64
	tso_caps:
	max_tso:			0
	packet_pacing_caps:
	qp_rate_limit_min:		0kbps
	qp_rate_limit_max:		0kbps
	ooo_caps:
	ooo_rc_caps  = 0x1
	ooo_xrc_caps = 0x1
	ooo_dc_caps  = 0x1
	ooo_ud_caps  = 0x0
					SUPPORT_RC_RW_DATA_PLACEMENT
					SUPPORT_XRC_RW_DATA_PLACEMENT
					SUPPORT_DC_RW_DATA_PLACEMENT
	sw_parsing_caps:
	supported_qp:
	max_rndv_hdr_size:		0x40
	max_num_tags:			0x7f
	max_ops:			0x8000
	max_sge:			0x1
	capability_flags:
					IBV_EXP_TM_CAP_RC
					IBV_EXP_TM_CAP_DC
	tunnel_offloads_caps:
	UMR fixed size:
		max entity size:	2147483648
	Device ports:
		port:	1
			state:			PORT_ACTIVE (4)
			max_mtu:		4096 (5)
			active_mtu:		4096 (5)
			sm_lid:			2
			port_lid:		53
			port_lmc:		0x00
			link_layer:		InfiniBand
			max_msg_sz:		0x40000000
			port_cap_flags:		0x2651e848
			max_vl_num:		4 (3)
			bad_pkey_cntr:		0x0
			qkey_viol_cntr:		0x0
			sm_sl:			0
			pkey_tbl_len:		128
			gid_tbl_len:		8
			subnet_timeout:		18
			init_type_reply:	0
			active_width:		4X (2)
			active_speed:		25.0 Gbps (32)
			phys_state:		LINK_UP (5)
			GID[  0]:		fe80:0000:0000:0000:ec0d:9a03:0098:a3e2

```

**Comment by hjelmn** [comment] 2018-10-10 15:36
Reproducer is NetPipe with Open MPI master run with:

```
mpirun  --mca pml ob1 --mca btl self,vader,uct --mca btl_uct_memory_domains ib/mlx5_0 -n 2 -N 1 ./NPmpi
```

**Comment by hjelmn** [comment] 2018-10-10 15:37
Reproducer is really RMA-MT run with:

```mpirun --mca pml ob1 --mca btl self,vader,uct --mca btl_uct_memory_domains ib/mlx5_0 -n 2 -N 1 ./rmamt_bw -o put -s flush_thread -x -t 32 -i 1000```

**Comment by hjelmn** [comment] 2018-10-10 15:48
Also, this is interesting. ucx_info shows the correct short size for all tls. So the problem is attr.cap.put.max_short is wrong:

```
ucx_info -c | grep SHORT
UCX_SELF_MAX_SHORT=128
UCX_TCP_MAX_SHORT=128
UCX_RC_VERBS_MAX_SHORT=128
UCX_RC_MLX5_MAX_SHORT=128
UCX_DC_VERBS_MAX_SHORT=128
UCX_DC_MLX5_MAX_SHORT=128
UCX_UD_VERBS_MAX_SHORT=128
UCX_UD_MLX5_MAX_SHORT=128
UCX_CM_MAX_SHORT=128
UCX_MM_MAX_SHORT=128
UCX_MAX_SHORT=128
UCX_MAX_SHORT=128
```

**Comment by hoopoepg** [comment] 2018-10-11 11:55
@hjelmn I looked at ob1 implementation and found issue: assumption that all ifaces created for same device will have similar attributes is not correct: we have set of resources for optimization (Device Memory, MEMIC) which are shared across all infaces, and in case if you create several infaces then some of them will not able to allocate memory on device and will use different put/send short limits

I prepared fix for this issue: https://github.com/open-mpi/ompi/pull/5895
not sure if it is optimal by design/implementation, but you may use it as reference fix: there added own copy of iface attributes for every EP to select appropriate API for uct_put[short]

**Comment by hjelmn** [comment] 2018-10-11 16:45
@hoopoepg Thanks for the explanation. Didn't see that before commenting on the PR. Makes sense. I opened open-mpi/ompi#5901 to address the issue. Now storing attributes per TL instance.

**Comment by yosefe** [comment] 2018-10-14 08:48
closing this, fixed in OMPI

**Closed by yosefe** 2018-10-14 08:48 UTC
Labels: Bug
