### ISSUE TITLE
test_ucp_sockaddr_protocols_err failed to send wireup message

### ISSUE THREAD

**Issue by dmitrygx** [openucx/ucx#6334] opened 2021-02-13 18:02 UTC
```
[2021-02-13T11:37:50.187Z] [ RUN      ] dcudx/test_ucp_sockaddr_protocols_err.tag_zcopy_4k_unexp/2 <dc_x,ud,cuda_copy,rocm_copy/recv_stop>
[2021-02-13T11:37:50.187Z] [     INFO ] server listening on 65.65.65.12:55424
[2021-02-13T11:37:50.444Z] [1613216270.230449] [r-vmb-ppc-jenkins:3086 :0]          wireup.c:137  UCX  ERROR failed to send wireup: Unsupported operation
[2021-02-13T11:37:51.007Z] [     INFO ] ignoring error Connection reset by remote peer on endpoint 0x3fff9f590000
[2021-02-13T11:37:51.007Z] [     INFO ] < operation returned error: Endpoint timeout >
[2021-02-13T11:37:51.007Z] /scrap/jenkins/workspace/ucx-3/contrib/../test/gtest/common/test.cc:353: Failure
[2021-02-13T11:37:51.007Z] Failed
[2021-02-13T11:37:51.007Z] Got 1 errors and 0 warnings during the test
[2021-02-13T11:37:51.007Z] [     INFO ] < /scrap/jenkins/workspace/ucx-3/contrib/../src/ucp/wireup/wireup.c:137 failed to send wireup: Unsupported operation >
```
Job link: http://hpc-master.lab.mtl.com:8080/blue/organizations/jenkins/ucx/detail/ucx/10063/pipeline
Job log link: http://hpc-master.lab.mtl.com:8080/blue/rest/organizations/jenkins/pipelines/ucx/runs/10063/nodes/53/steps/367/log/?start=0

**Comment by dmitrygx** [comment] 2021-02-13 18:16
```
[ RUN      ] ud/test_ucp_sockaddr_protocols_err.tag_eager_32_unexp/5 <ud_v,cuda_copy,rocm_copy/bidi_stop,mt>
[New Thread 0x3fffb676f100 (LWP 29799)]
[     INFO ] server listening on 65.65.65.12:44192
[1613239419.972648] [r-vmb-ppc-jenkins:19675:0]          wireup.c:137  UCX  ERROR failed to send wireup: Unsupported operation
[     INFO ] ignoring error Connection reset by remote peer on endpoint 0x3fffb5c60000
[Thread 0x3fffb676f100 (LWP 29799) exited]
common/test.cc:353: Failure
Failed
Got 1 errors and 0 warnings during the test
```

**Comment by brminich** [comment] 2021-02-15 06:12
duplicate of #6320

**Closed** 2021-02-15 06:12 UTC
Labels: Bug, CI (AZP/Jenkins)
