### ISSUE TITLE
ucp_client_server didn't honor UCX_NET_DEVICES

### ISSUE THREAD

**Issue by Akshay-Venkatesh** [openucx/ucx#3463] opened 2019-04-09 17:57 UTC
Hi, 

We have a machine which has several mlx5 devices. One of which (`mlx5_4`) is in `PORT_DOWN` state. I'm trying to run `ucp_client_server` from `test/examples` but I see the following error even when I try to restrict the devices being used to just `mlx5_0:1`:

```
akvenkatesh@abc:~/akvenkatesh/ucx-1.5.1/build$  UCX_NET_DEVICES=mlx5_0:1 ./ucp_client_server.out -a 172.22.1.27
[1554831347.602987] [abc:48104:1]      wireup_ep.c:467  UCX  ERROR no supported sockaddr auxiliary transports found for mlx5_4:1
[1554831347.603009] [abc:48104:1]     ucp_worker.c:495  UCX  ERROR error 'Destination is unreachable' will not be handled for ep 0x7f1890d4a048 - /�gV
stream_send_cb returned with status -6 (Destination is unreachable)
```
Is there another env parameter for `sockaddr` TLs so that I can ignore `mlx5_4:1`?

**Comment by evgeny-leksikov** [comment] 2019-04-09 19:01
Hi @Akshay-Venkatesh 
Which device is configured with IP address 172.22.1.27? Is this mlx5?
You can match network interface with device by sys path like this: /sys/class/infiniband/mlx5_0/device/net/ib0/
Where mlx5_0 is device name and ib0 is network interface, then run 
$ ip address
To match interface to IP address

**Comment by Akshay-Venkatesh** [comment] 2019-04-09 19:28
Hi @evgeny-leksikov 

> Hi @Akshay-Venkatesh
> Which device is configured with IP address 172.22.1.27? Is this mlx5?
This machine has a bonded device named `bond0` which has the IP 172.22.1.27. I don't know the full details of this device on this particular machine. 

There are other instances of a similar machine where there is a similar bonded device whose IP corresponds to IP assigned to an `mlx5` device. I assumed that there's a similar bonding on the machine I'm currently working on (where I see the above issue) but I'll come back to you with more details on this.

**Comment by evgeny-leksikov** [comment] 2019-04-09 19:48
My guessing is you pass IP address of device with down port. From example above 172.22.1.27 was bound to mlx5_4:1

**Comment by evgeny-leksikov** [comment] 2019-04-09 19:52
But on the other hand, rdmacm returns that device name and it looks strange :) pls send details about your configuration

**Comment by evgeny-leksikov** [comment] 2019-04-09 20:03
Probably, that's iwarp device, ucx doesn't support it yet

**Comment by Akshay-Venkatesh** [comment] 2019-04-09 20:23
> My guessing is you pass IP address of device with down port. From example above 172.22.1.27 was bound to mlx5_4:1

Agreed. This would explain the situation we're seeing where we're trying to force just mlx5_0:1 to be used but the IP provided is may be mlx5_4:1's.

I'm checking internally for the details. Will update here when I get that.

**Comment by Akshay-Venkatesh** [comment] 2019-04-15 19:28
@evgeny-leksikov You were right. This issue went away on the machine we were testing when IPs were correctly assigned to the IB devices.

@yosefe I'm fine closing this issue since we're not blocked after the re-assignment. 
General question - should UCX be throwing a warning when I start up the server and try to get it tries to listen on an IP that cannot do so?

**Comment by yosefe** [comment] 2019-04-15 20:30
the problem is the we can listen on the device (because it supports rdma_cm), but later on - cannot create data transport on it.
this may also happen if we're listening to 0.0.0.0, and getting connection request on an "unsupported" device.
the plan is to add support to iWarp device as well, so basically every device which supports rdma_cm will work.

**Comment by evgeny-leksikov** [comment] 2019-04-18 15:33
@yosefe can we close this?

**Closed** 2019-04-18 17:28 UTC
Labels: Waiting for Author Response
