### ISSUE TITLE
hang in dcx/test_ucp_tag_xfer.contig_unexp_sync/4

### ISSUE THREAD

**Issue by brminich** [openucx/ucx#2293] opened 2018-02-09 11:01 UTC
Happened on hpc-test-node-3 here:
http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6231/label=hpc-test-node3,worker=3/consoleFull#-853622487b816df86-9afc-46eb-984f-1a9a125d73bb

```
08:55:13 [       OK ] dcx/test_ucp_tag_xfer.send_contig_recv_generic_unexp_sync_rndv_truncated/3 (323 ms)
08:55:13 [ RUN      ] dcx/test_ucp_tag_xfer.contig_unexp_sync/4
08:55:14 [     INFO ] 0 50x10^1 50x10^2 50x10^3 50x10^4 15x10^5 5x10^6 make: *** [test] Terminated
11:21:33 
Build step 'Execute shell' marked build as failure
```

**Comment by yosefe** [comment] 2018-02-09 11:42
@alex-mikheev @hoopoepg can this be related to the DC/multi-rail arbiter issue (for now fixed only in 1.3.x)?

**Comment by hoopoepg** [comment] 2018-02-09 11:58
Yes, could be same reason

**Comment by yosefe** [comment] 2018-02-09 12:44
duplicate of #2275

**Comment by brminich** [comment] 2018-02-09 13:13
But there were not any error from UCT. I'd get an assertion if UCP tries to perform GET on small size, right?

**Comment by yosefe** [comment] 2018-02-09 13:15
right. 
this issue is possibly related to #2257

**Comment by brminich** [comment] 2018-02-09 13:16
yes, this one looks similar

**Comment by yosefe** [comment] 2018-02-11 14:23
@hoopoepg can you pls check if this issue is solved by the DC arbiter fix?

**Comment by hoopoepg** [comment] 2018-02-12 08:21
can't reproduce with & without fix

**Comment by yosefe** [comment] 2018-04-15 15:05
not reproduced for ~2 months, closing

**Closed by yosefe** 2018-04-15 15:05 UTC
Labels: bug, jenkins
