### ISSUE TITLE
No cudaIpcCloseMemHandle called in cuda_ipc

### ISSUE THREAD

**Issue by Kur0x** [openucx/ucx#3030] opened 2018-11-09 02:30 UTC
cuda ipc failed after contiguous zcopy with increasing buffer size. Although I reg(`cudaMalloc ` `uct_md_mem_reg`) and dereg(`uct_md_mem_dereg` `cudaFree`) each loop, but it always fails after several loop.
![image](https://user-images.githubusercontent.com/9768369/48239299-53688f00-e409-11e8-80c0-a0bc0bc47ca3.png)
When I dig into the code, I found that there is no `cudaIpcCloseMemHandle` called in the code. I think it may be related to this problem.
![image](https://user-images.githubusercontent.com/9768369/48239444-e0abe380-e409-11e8-9ac0-fddbab2318c1.png)

**Comment by Akshay-Venkatesh** [comment] 2018-11-09 17:14
@Kur0x Can you please provide the code that you're using to reproduce this error? You're indicating you use `uct_md_mem_reg` to dereg. I hope that's a typo. 

Also, we use driver API `cuIpcCloseMemHandle` in uct code. `uct_md_mem_reg` and `uct_md_mem_dereg` doesn't translate to opening and closing cuda ipc memory handles. Opening occurs when rkey is unpacked and deferred to the point of first transfer using the rkey. 

You can also run `nvprof` on your test to find which cuda*/cu* calls have been made.

**Comment by Kur0x** [comment] 2018-11-13 10:49
> @Kur0x Can you please provide the code that you're using to reproduce this error? You're indicating you use `uct_md_mem_reg` to dereg. I hope that's a typo.
> 
> Also, we use driver API `cuIpcCloseMemHandle` in uct code. `uct_md_mem_reg` and `uct_md_mem_dereg` doesn't translate to opening and closing cuda ipc memory handles. Opening occurs when rkey is unpacked and deferred to the point of first transfer using the rkey.
> 
> You can also run `nvprof` on your test to find which cuda*/cu* calls have been made.

`uct_md_mem_reg` is a typo.(fixed) 

Here is the `nvprof` result. I called `cuMemAlloc` 101 times and `cudaFree` 113 times. But `cuIpc*MemHandle` shows much less.
```
======== Profiling result:
            Type  Time(%)      Time     Calls       Avg       Min       Max  Name
 GPU activities:   93.91%  89.981ms         8  11.248ms  1.6960us  23.855ms  [CUDA memcpy HtoD]
                    5.49%  5.2587ms       209  25.161us  13.101us  37.901us  [CUDA memcpy PtoP]
                    0.60%  576.03us       202  2.8510us  2.3680us  3.2640us  kernel_add(float const *, float const *, int, float*)
                    0.00%  3.8400us         2  1.9200us  1.5680us  2.2720us  [CUDA memset]
      API calls:   81.99%  1.09656s       113  9.7041ms  13.763us  1.08249s  cudaFree
                    6.94%  92.809ms         8  11.601ms  35.392us  24.836ms  cudaMemcpy
                    3.69%  49.287ms      1104  44.643us     211ns  6.2088ms  cuDeviceGetAttribute
                    1.77%  23.643ms       202  117.04us  8.4730us  273.48us  cudaStreamSynchronize
                    1.59%  21.248ms     17155  1.2380us     622ns  23.517us  cuEventQuery
                    0.98%  13.081ms        11  1.1892ms  22.251us  1.7309ms  cudaMalloc
                    0.81%  10.885ms        12  907.09us  597.16us  1.5238ms  cuDeviceTotalMem
                    0.57%  7.6663ms       599  12.798us  1.3500us  44.693us  cuMemcpyDtoDAsync
                    0.48%  6.4297ms       202  31.830us  13.874us  46.997us  cudaLaunch
                    0.31%  4.1947ms        12  349.56us  129.50us  643.04us  cuDeviceGetName
                    0.17%  2.2786ms       101  22.560us  12.795us  40.107us  cuMemAlloc
                    0.13%  1.6885ms         2  844.27us  755.80us  932.74us  cudaIpcOpenMemHandle
                    0.12%  1.6509ms         2  825.43us  824.54us  826.31us  cudaIpcCloseMemHandle
                    0.12%  1.5904ms      1205  1.3190us     206ns  910.74us  cuCtxGetDevice
                    0.10%  1.3365ms         2  668.24us  561.63us  774.86us  cuIpcOpenMemHandle
                    0.08%  1.0458ms       606  1.7250us     559ns  2.9260us  cuIpcGetMemHandle
                    0.03%  461.66us       606     761ns     348ns  1.4070us  cuMemGetAddressRange
                    0.03%  343.00us       808     424ns     158ns  19.863us  cudaSetupArgument
                    0.02%  314.58us       209  1.5050us     659ns  2.2340us  cuEventRecord
                    0.02%  257.23us       202  1.2730us     549ns  2.1730us  cudaConfigureCall
                    0.02%  212.90us       390     545ns     275ns  10.017us  cuGetErrorString
                    0.01%  98.041us         2  49.020us  30.927us  67.114us  cudaMemset
                    0.01%  85.963us       128     671ns     351ns  2.4520us  cuEventCreate
                    0.01%  83.347us         1  83.347us  83.347us  83.347us  cudaStreamCreate
                    0.00%  64.061us         4  16.015us  10.115us  32.748us  cuStreamCreate
                    0.00%  21.634us         9  2.4030us     498ns  5.8800us  cudaGetDevice
                    0.00%  15.712us        16     982ns     348ns  4.0940us  cuDeviceGet
                    0.00%  11.076us         3  3.6920us  1.9510us  4.7880us  cudaDeviceGetPCIBusId
                    0.00%  10.080us         1  10.080us  10.080us  10.080us  cudaEventDestroy
                    0.00%  8.3220us         1  8.3220us  8.3220us  8.3220us  cudaEventCreateWithFlags
                    0.00%  6.7440us         6  1.1240us     196ns  3.1570us  cudaGetDeviceCount
                    0.00%  5.7100us         6     951ns     209ns  2.0770us  cuDeviceGetCount
                    0.00%  5.0560us         4  1.2640us     763ns  1.9630us  cudaDeviceGetAttribute
                    0.00%  4.7740us         2  2.3870us  1.3070us  3.4670us  cudaIpcGetMemHandle
                    0.00%  4.4670us         1  4.4670us  4.4670us  4.4670us  cuPointerGetAttributes
                    0.00%  4.0050us         2  2.0020us  1.7650us  2.2400us  cuDriverGetVersion
                    0.00%  3.0720us         2  1.5360us  1.3380us  1.7340us  cuInit

```

**Comment by Akshay-Venkatesh** [comment] 2018-11-14 00:29
@Kur0x `cuIpc*Mem*` is expected to be less than `alloc/free` because a caching mechanism avoids opening/closing of memhandles when it's possible to reuse an existing mapping.

**Comment by Kur0x** [comment] 2018-11-14 01:41
@Akshay-Venkatesh It seems caching mechanism goes wrong. When the buffer size decreasing test goes fine, when the buffer size increasing test goes wrong. I think it may because when buffer increasing, mapping become invalid, but caching mechanism doesn't update it.
Here is the gtest case. `j *sizeof(float)` is the buffer size.
![image](https://user-images.githubusercontent.com/9768369/48453754-9e124e80-e7ef-11e8-84b4-3b19328c35d2.png)

**Comment by Akshay-Venkatesh** [comment] 2018-11-14 02:52
@Kur0x would it be possible to provide a small MPI reproducer?
I'm using the [following](https://gist.github.com/Akshay-Venkatesh/ff34ea8f190625917651d889e400717b) to reproduce your conditions but I don't see an error. Can you check at your end?
I run using:
```
orterun -np 2 --hostfile ./hostfile --mca pml ucx --mca btl ^openib -x LD_LIBRARY_PATH -x ./cuda_allreduce_increasing.out
```
where hostfile is:
```
hsw-host slots=2 max-slots=2
```

**Comment by bureddy** [comment] 2019-04-24 16:23
@Kur0x @Akshay-Venkatesh  is this still an issue?

**Comment by yosefe** [comment] 2019-08-11 07:45
closing due to no response from issue author

**Closed by yosefe** 2019-08-11 07:45 UTC
Labels: Bug
